"use client";
import { useCallback, useEffect, useState } from "react";
import { useZhaoXiLocale } from "@zhaoxi/i18n";
import { Surface, ActionButton } from "@zhaoxi/ui";
import { money, percent, type AnalyticsOverview } from "@zhaoxi/analytics";
const text={
 "vi-VN":{title:"Phân tích vận hành",sub:"Tổng quan sức khỏe nền tảng theo dữ liệu thực tế.",days:"Khoảng thời gian",orders:"Đơn hàng",gmv:"Tổng giá trị đơn",revenue:"Đã thu",completion:"Tỷ lệ hoàn thành",partners:"Đối tác",drivers:"Tài xế hoạt động",delivery:"Đã giao",support:"Hỗ trợ đang mở",modules:"Theo mảng dịch vụ",status:"Trạng thái đơn",payments:"Thanh toán",refresh:"Làm mới",d7:"7 ngày",d30:"30 ngày",d90:"90 ngày"},
 "en-US":{title:"Operations analytics",sub:"Platform health from live operational data.",days:"Period",orders:"Orders",gmv:"Gross order value",revenue:"Collected",completion:"Completion rate",partners:"Partners",drivers:"Active drivers",delivery:"Delivered",support:"Open support",modules:"By service area",status:"Order status",payments:"Payments",refresh:"Refresh",d7:"7 days",d30:"30 days",d90:"90 days"},
 "zh-CN":{title:"运营分析",sub:"基于真实运营数据的平台健康概览。",days:"时间范围",orders:"订单",gmv:"订单总额",revenue:"已收款",completion:"完成率",partners:"合作商家",drivers:"在线司机",delivery:"已送达",support:"待处理客服",modules:"按服务分类",status:"订单状态",payments:"支付",refresh:"刷新",d7:"7天",d30:"30天",d90:"90天"},
 "zh-TW":{title:"營運分析",sub:"依實際營運資料顯示平台健康狀況。",days:"時間範圍",orders:"訂單",gmv:"訂單總額",revenue:"已收款",completion:"完成率",partners:"合作商家",drivers:"上線司機",delivery:"已送達",support:"待處理客服",modules:"依服務分類",status:"訂單狀態",payments:"付款",refresh:"重新整理",d7:"7天",d30:"30天",d90:"90天"}
} as const;
function Metric({label,value}:{label:string;value:string|number}){return <Surface style={{padding:14}}><small style={{color:"#64748b"}}>{label}</small><strong style={{display:"block",fontSize:22,marginTop:5}}>{value}</strong></Surface>}
export default function AnalyticsDashboard(){
 const {locale}=useZhaoXiLocale(); const t=text[locale]; const [days,setDays]=useState(30); const [data,setData]=useState<AnalyticsOverview|null>(null); const [error,setError]=useState("");
 const load=useCallback(async()=>{try{const r=await fetch(`/api/platform-analytics?days=${days}`,{cache:"no-store"});const p=await r.json();if(!r.ok)throw new Error(p?.error?.message||"Load failed");setData(p.data);setError("")}catch(e){setError(e instanceof Error?e.message:"Load failed")}},[days]);
 useEffect(()=>{void load();const timer=window.setInterval(load,30000);return()=>window.clearInterval(timer)},[load]);
 return <section className="zx-native-workspace"><header style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"end",flexWrap:"wrap",marginBottom:16}}><div><h1 style={{margin:"0 0 6px"}}>{t.title}</h1><p style={{margin:0,color:"#64748b"}}>{t.sub}</p></div><div style={{display:"flex",gap:8,alignItems:"center"}}><select value={days} onChange={e=>setDays(Number(e.target.value))} style={{padding:10,borderRadius:12,border:"1px solid #dbe3df"}}><option value={7}>{t.d7}</option><option value={30}>{t.d30}</option><option value={90}>{t.d90}</option></select><ActionButton tone="neutral" onClick={load}>{t.refresh}</ActionButton><a href="/incidents" style={{padding:"10px 12px",borderRadius:12,background:"#17211b",color:"#fff",fontWeight:800,textDecoration:"none"}}>⚠ Incident</a></div></header>{error&&<p style={{padding:12,borderRadius:12,background:"#fff1f2",color:"#be123c"}}>{error}</p>}{!data?<Surface>…</Surface>:<><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(135px,1fr))",gap:10}}><Metric label={t.orders} value={data.totals.orders}/><Metric label={t.gmv} value={money(data.totals.gmv,locale)}/><Metric label={t.revenue} value={money(data.totals.collectedRevenue,locale)}/><Metric label={t.completion} value={percent(data.totals.completionRate)}/><Metric label={t.partners} value={data.totals.partners}/><Metric label={t.drivers} value={`${data.totals.activeDrivers}/${data.totals.drivers}`}/><Metric label={t.delivery} value={`${data.totals.delivered}/${data.totals.deliveries}`}/><Metric label={t.support} value={data.totals.openSupport}/></div><Surface style={{marginTop:14}}><h2>{t.modules}</h2><div style={{display:"grid",gap:8}}>{data.modules.map(m=><div key={m.code} style={{display:"grid",gridTemplateColumns:"1fr auto auto",gap:10,padding:"9px 0",borderBottom:"1px solid #edf2ef"}}><b>{m.name||m.code}</b><span>{m.orders} {t.orders.toLowerCase()}</span><strong>{money(m.gmv,locale)}</strong></div>)}</div></Surface><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:12,marginTop:14}}><Surface><h2>{t.status}</h2>{data.orderStatus.map(x=><p key={x.status} style={{display:"flex",justifyContent:"space-between"}}><span>{x.status}</span><b>{x.count}</b></p>)}</Surface><Surface><h2>{t.payments}</h2>{data.paymentStatus.map(x=><p key={x.status} style={{display:"flex",justifyContent:"space-between",gap:8}}><span>{x.status}</span><b>{x.count} · {money(x.amount,locale)}</b></p>)}</Surface></div></>}</section>
}
