"use client";import{useEffect,useMemo,useState}from"react";import{useZhaoXiLocale}from"@zhaoxi/i18n";

const C={
"vi-VN":{title:"Customer Operations",tasks:"Tasks",follow:"Follow-up hôm nay",overdue:"Quá hạn",recovery:"Service Recovery",critical:"Critical",unassigned:"Chưa phân công",queue:"Follow-up Queue",customers:"Customer Workspace",search:"Tìm Customer",task:"Tạo task",taskTitle:"Nội dung task",due:"Deadline",priority:"Ưu tiên",assignee:"Người xử lý",save:"Tạo",status:"Trạng thái",segments:"Segments",newSegment:"Tạo segment",recoveryNew:"Mở Service Recovery",reason:"Lý do",summary:"Tóm tắt vấn đề",severity:"Mức độ",resolve:"Đã xử lý",empty:"Chưa có dữ liệu",policy:"Vận hành nội bộ; không tự liên hệ Customer, không tự bồi thường và không có quyền tài chính."},
"zh-CN":{title:"客户运营中心",tasks:"任务",follow:"今日跟进",overdue:"逾期",recovery:"服务恢复",critical:"关键",unassigned:"未分配",queue:"跟进队列",customers:"客户工作区",search:"搜索客户",task:"创建任务",taskTitle:"任务内容",due:"截止时间",priority:"优先级",assignee:"处理人员",save:"创建",status:"状态",segments:"客户分群",newSegment:"创建分群",recoveryNew:"创建服务恢复案例",reason:"原因",summary:"问题摘要",severity:"严重程度",resolve:"已解决",empty:"暂无数据",policy:"仅限内部运营；不会自动联系客户、自动赔偿或执行财务操作。"},
"zh-TW":{title:"客戶營運中心",tasks:"任務",follow:"今日跟進",overdue:"逾期",recovery:"服務恢復",critical:"關鍵",unassigned:"未分配",queue:"跟進佇列",customers:"客戶工作區",search:"搜尋客戶",task:"建立任務",taskTitle:"任務內容",due:"截止時間",priority:"優先級",assignee:"處理人員",save:"建立",status:"狀態",segments:"客戶分群",newSegment:"建立分群",recoveryNew:"建立服務恢復案例",reason:"原因",summary:"問題摘要",severity:"嚴重程度",resolve:"已解決",empty:"暫無資料",policy:"僅限內部營運；不會自動聯絡客戶、自動賠償或執行財務操作。"},
"en-US":{title:"Customer Operations",tasks:"Tasks",follow:"Follow-ups today",overdue:"Overdue",recovery:"Service Recovery",critical:"Critical",unassigned:"Unassigned",queue:"Follow-up Queue",customers:"Customer Workspace",search:"Search customers",task:"Create task",taskTitle:"Task title",due:"Due",priority:"Priority",assignee:"Assignee",save:"Create",status:"Status",segments:"Segments",newSegment:"Create segment",recoveryNew:"Open Service Recovery",reason:"Reason",summary:"Issue summary",severity:"Severity",resolve:"Resolved",empty:"No data",policy:"Internal operations only; no automatic customer contact, compensation, or financial actions."}
}as const;

export default function CustomerOperationsHub(){
 const{locale}=useZhaoXiLocale(),t=C[locale];
 const[q,setQ]=useState(""),[customers,setCustomers]=useState<any[]>([]),[customerId,setCustomerId]=useState(""),[workspace,setWorkspace]=useState<any>(null),[queue,setQueue]=useState<any>({tasks:[],recoveries:[],agents:[],segments:[],summary:{}}),[view,setView]=useState<"tasks"|"recovery">("tasks");
 const[task,setTask]=useState<any>({title:"",taskType:"follow_up",priority:"normal",assignedAdminUserId:"",dueAt:""});
 const[recovery,setRecovery]=useState<any>({reason:"",summary:"",severity:"normal",assignedAdminUserId:"",dueAt:""});
 const[newSegment,setNewSegment]=useState("");

 async function loadQueue(){const r=await fetch("/api/admin-customer-operations/queue",{cache:"no-store"}),j=await r.json();if(j?.ok)setQueue(j.data)}
 async function loadWorkspace(id=customerId){if(!id){setWorkspace(null);return}const r=await fetch(`/api/admin-customer-operations/customer/${id}`,{cache:"no-store"}),j=await r.json();if(j?.ok)setWorkspace(j.data)}
 useEffect(()=>{void loadQueue()},[]);
 useEffect(()=>{const h=setTimeout(()=>fetch(`/api/admin-customer-relationships?q=${encodeURIComponent(q)}`,{cache:"no-store"}).then(r=>r.json()).then(j=>j?.ok&&setCustomers(j.data||[])).catch(()=>{}),180);return()=>clearTimeout(h)},[q]);
 useEffect(()=>{void loadWorkspace()},[customerId]);
 const selectedSegments=new Set((workspace?.segments||[]).map((x:any)=>x.segmentId));

 async function createTask(){if(!customerId||!task.title.trim())return;const r=await fetch(`/api/admin-customer-operations/customer/${customerId}/tasks`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...task,dueAt:task.dueAt||null,assignedAdminUserId:task.assignedAdminUserId||null})});if(r.ok){setTask({title:"",taskType:"follow_up",priority:"normal",assignedAdminUserId:"",dueAt:""});await Promise.all([loadQueue(),loadWorkspace()])}}
 async function updateTask(x:any,body:any){await fetch(`/api/admin-customer-operations/tasks/${x.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(body)});await Promise.all([loadQueue(),loadWorkspace()])}
 async function createRecovery(){if(!customerId||!recovery.reason.trim()||!recovery.summary.trim())return;const r=await fetch(`/api/admin-customer-operations/customer/${customerId}/recovery`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...recovery,dueAt:recovery.dueAt||null,assignedAdminUserId:recovery.assignedAdminUserId||null})});if(r.ok){setRecovery({reason:"",summary:"",severity:"normal",assignedAdminUserId:"",dueAt:""});await Promise.all([loadQueue(),loadWorkspace()])}}
 async function updateRecovery(x:any,body:any){await fetch(`/api/admin-customer-operations/recovery/${x.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(body)});await Promise.all([loadQueue(),loadWorkspace()])}
 async function toggleSegment(x:any){if(!customerId)return;await fetch(`/api/admin-customer-operations/customer/${customerId}/segments/${x.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({enabled:!selectedSegments.has(x.id)})});await loadWorkspace()}
 async function addSegment(){if(!newSegment.trim())return;await fetch("/api/admin-customer-operations/segments",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:newSegment})});setNewSegment("");await loadQueue()}

 const visible=view==="tasks"?queue.tasks:queue.recoveries;
 return <section className="zx-native-workspace zx-transaction-workflow zx-native-complete" style={{display:"grid",gap:10}}>
  <header><h1 style={{margin:"0 0 4px"}}>🧭 {t.title}</h1><small style={{color:"#64748b"}}>{t.policy}</small></header>
  <div style={metrics}><M l={t.tasks} v={queue.summary?.openTasks||0}/><M l={t.follow} v={queue.summary?.followUpsDueToday||0}/><M l={t.overdue} v={queue.summary?.overdueTasks||0}/><M l={t.recovery} v={queue.summary?.openRecovery||0}/><M l={t.critical} v={queue.summary?.criticalRecovery||0}/><M l={t.unassigned} v={queue.summary?.unassigned||0}/></div>
  <div style={two}>
   <section style={box}>
    <div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><b>📋 {t.queue}</b><div><button onClick={()=>setView("tasks")} style={chip(view==="tasks")}>{t.tasks}</button><button onClick={()=>setView("recovery")} style={chip(view==="recovery")}>{t.recovery}</button></div></div>
    <div style={scroll}>{visible.map((x:any)=><article key={x.id} style={{...row,borderColor:x.overdue?"#f59e0b":"#e5ebe7"}}><div><b>{view==="tasks"?x.title:x.reason}</b><small style={{display:"block"}}>{x.customer?.nickname||x.customer?.email||x.customerId}</small><small style={{color:"#64748b"}}>{view==="tasks"?`${x.taskType} · ${x.priority}`:`${x.severity} · ${x.status}`}{x.dueAt?` · ${new Date(x.dueAt).toLocaleString(locale)}`:""}</small></div><div style={{display:"grid",gap:4,justifyItems:"end"}}>{x.overdue&&<small>⚠ {t.overdue}</small>}<select value={x.status} onChange={e=>view==="tasks"?void updateTask(x,{status:e.target.value}):void updateRecovery(x,{status:e.target.value})}>{view==="tasks"?<><option value="open">open</option><option value="in_progress">in_progress</option><option value="completed">completed</option><option value="cancelled">cancelled</option></>:<><option value="open">open</option><option value="in_progress">in_progress</option><option value="resolved">resolved</option><option value="cancelled">cancelled</option></>}</select></div></article>)}{!visible.length&&<div style={empty}>{t.empty}</div>}</div>
   </section>

   <section style={box}>
    <b>👤 {t.customers}</b><input value={q} onChange={e=>setQ(e.target.value)} placeholder={t.search} style={input}/>
    <div style={{display:"grid",gridTemplateColumns:"190px 1fr",gap:8,marginTop:7}}>
     <div style={{maxHeight:520,overflowY:"auto",display:"grid",gap:4}}>{customers.map(x=><button key={x.customer.id} onClick={()=>setCustomerId(x.customer.id)} style={{...customerButton,background:customerId===x.customer.id?"#eefbf3":"#fff"}}><b>{x.customer.nickname||x.customer.id.slice(0,8)}</b><small>{x.serviceRequests} req · {x.supportThreads} support</small></button>)}</div>
     <div>{!workspace?<div style={empty}>{t.empty}</div>:<>
      <div style={{display:"grid",gap:3}}><b>{workspace.customer.nickname||workspace.customer.email||workspace.customer.id}</b><small>{workspace.relationship?.relationshipStage||"active"}</small></div>
      <section style={mini}><b>{t.segments}</b><div style={{display:"flex",gap:5,flexWrap:"wrap",marginTop:5}}>{(queue.segments||[]).map((x:any)=><button key={x.id} onClick={()=>void toggleSegment(x)} style={{...chip,opacity:selectedSegments.has(x.id)?1:.45}}>#{x.name}</button>)}</div><div style={{display:"flex",gap:5,marginTop:6}}><input value={newSegment} onChange={e=>setNewSegment(e.target.value)} placeholder={t.newSegment}/><button onClick={()=>void addSegment()}>＋</button></div></section>
      <section style={mini}><b>✅ {t.task}</b><input value={task.title} onChange={e=>setTask({...task,title:e.target.value})} placeholder={t.taskTitle}/><div style={formGrid}><select value={task.taskType} onChange={e=>setTask({...task,taskType:e.target.value})}><option value="follow_up">follow_up</option><option value="callback">callback</option><option value="review">review</option><option value="service_recovery">service_recovery</option></select><select value={task.priority} onChange={e=>setTask({...task,priority:e.target.value})}><option value="low">low</option><option value="normal">normal</option><option value="high">high</option><option value="urgent">urgent</option></select><input type="datetime-local" value={task.dueAt} onChange={e=>setTask({...task,dueAt:e.target.value})}/><select value={task.assignedAdminUserId} onChange={e=>setTask({...task,assignedAdminUserId:e.target.value})}><option value="">{t.unassigned}</option>{(queue.agents||[]).map((a:any)=><option key={a.id} value={a.id}>{a.name}</option>)}</select></div><button onClick={()=>void createTask()}>{t.save}</button></section>
      <section style={{...mini,background:"#fff7ed"}}><b>🛟 {t.recoveryNew}</b><input value={recovery.reason} onChange={e=>setRecovery({...recovery,reason:e.target.value})} placeholder={t.reason}/><textarea rows={2} value={recovery.summary} onChange={e=>setRecovery({...recovery,summary:e.target.value})} placeholder={t.summary}/><div style={formGrid}><select value={recovery.severity} onChange={e=>setRecovery({...recovery,severity:e.target.value})}><option value="normal">normal</option><option value="high">high</option><option value="critical">critical</option></select><input type="datetime-local" value={recovery.dueAt} onChange={e=>setRecovery({...recovery,dueAt:e.target.value})}/><select value={recovery.assignedAdminUserId} onChange={e=>setRecovery({...recovery,assignedAdminUserId:e.target.value})}><option value="">{t.unassigned}</option>{(queue.agents||[]).map((a:any)=><option key={a.id} value={a.id}>{a.name}</option>)}</select></div><button onClick={()=>void createRecovery()}>{t.save}</button></section>
      {(workspace.tasks||[]).length>0&&<section style={mini}><b>{t.tasks}</b>{workspace.tasks.slice(0,6).map((x:any)=><small key={x.id} style={{display:"block"}}>{x.status==="completed"?"✓":"•"} {x.title}{x.overdue?" ⚠":""}</small>)}</section>}
      {(workspace.recoveries||[]).length>0&&<section style={mini}><b>{t.recovery}</b>{workspace.recoveries.slice(0,5).map((x:any)=><small key={x.id} style={{display:"block"}}>{x.severity==="critical"?"⚠":"•"} {x.reason} · {x.status}</small>)}</section>}
     </>}</div>
    </div>
   </section>
  </div>
 </section>
}

function M({l,v}:{l:string;v:number}){return <div style={{padding:8,border:"1px solid #e3eae6",borderRadius:11,background:"#fff"}}><small>{l}</small><b style={{display:"block",fontSize:18}}>{v}</b></div>}
const metrics={display:"grid",gridTemplateColumns:"repeat(6,minmax(0,1fr))",gap:6}as const,two={display:"grid",gridTemplateColumns:"minmax(320px,.8fr) minmax(0,1.2fr)",gap:10}as const,box={padding:10,border:"1px solid #e3eae6",borderRadius:14,background:"#fff"}as const,scroll={display:"grid",gap:5,maxHeight:640,overflowY:"auto",marginTop:8}as const,row={display:"grid",gridTemplateColumns:"1fr auto",gap:7,padding:8,border:"1px solid #e5ebe7",borderRadius:10}as const,chip=(a:boolean)=>({border:"1px solid #dbe5df",borderRadius:999,padding:"5px 7px",background:a?"#07c160":"#fff",color:a?"#fff":"#475569",fontSize:8})as const,input={width:"100%",boxSizing:"border-box",padding:8,border:"1px solid #dbe5df",borderRadius:9,marginTop:6}as const,customerButton={display:"grid",textAlign:"left",gap:2,padding:7,border:"1px solid #e5ebe7",borderRadius:9}as const,mini={display:"grid",gap:5,padding:8,border:"1px solid #edf1ef",borderRadius:10,marginTop:7}as const,formGrid={display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:5}as const,empty={padding:24,textAlign:"center",color:"#64748b"}as const;
