"use client";import{useEffect,useMemo,useState}from"react";import{useZhaoXiLocale}from"@zhaoxi/i18n";
const T:any={
"vi-VN":{title:"Operations Command Center",sub:"Toàn cảnh backlog, workload, SLA và điểm nghẽn vận hành ZhaoXi",backlog:"Backlog",overdue:"Quá hạn",due2:"Đến hạn ≤2h",due24:"Đến hạn ≤24h",unassigned:"Chưa phân công",recovery:"Recovery Critical",overloaded:"Agent quá tải",forecast:"SLA Forecast",workload:"Workload Planning",bottleneck:"Bottlenecks",queue:"Unified Work Queue",capacity:"Capacity/ngày",load:"Tải",active:"Đang xử lý",save:"Lưu",all:"Tất cả",healthy:"Ổn định",policy:"Dashboard quản trị và dự báo; không tự phân công, không tự thay đổi workflow và không có quyền tài chính."},
"zh-CN":{title:"运营指挥中心",sub:"统一查看 ZhaoXi 积压、工作量、SLA 与运营瓶颈",backlog:"待办总量",overdue:"已逾期",due2:"≤2小时到期",due24:"≤24小时到期",unassigned:"未分配",recovery:"关键恢复案例",overloaded:"超负荷人员",forecast:"SLA 预测",workload:"工作量规划",bottleneck:"运营瓶颈",queue:"统一工作队列",capacity:"每日容量",load:"负载",active:"处理中",save:"保存",all:"全部",healthy:"正常",policy:"仅用于管理与预测；不会自动分配、自动改变业务流程或执行财务操作。"},
"zh-TW":{title:"營運指揮中心",sub:"統一查看 ZhaoXi 積壓、工作量、SLA 與營運瓶頸",backlog:"待辦總量",overdue:"已逾期",due2:"≤2小時到期",due24:"≤24小時到期",unassigned:"未分配",recovery:"關鍵恢復案例",overloaded:"超負荷人員",forecast:"SLA 預測",workload:"工作量規劃",bottleneck:"營運瓶頸",queue:"統一工作佇列",capacity:"每日容量",load:"負載",active:"處理中",save:"儲存",all:"全部",healthy:"正常",policy:"僅用於管理與預測；不會自動分配、自動改變業務流程或執行財務操作。"},
"en-US":{title:"Operations Command Center",sub:"Unified ZhaoXi backlog, workload, SLA and operational bottlenecks",backlog:"Backlog",overdue:"Overdue",due2:"Due ≤2h",due24:"Due ≤24h",unassigned:"Unassigned",recovery:"Critical Recovery",overloaded:"Overloaded agents",forecast:"SLA Forecast",workload:"Workload Planning",bottleneck:"Bottlenecks",queue:"Unified Work Queue",capacity:"Daily capacity",load:"Load",active:"Active",save:"Save",all:"All",healthy:"Healthy",policy:"Management and forecasting only; no automatic assignment, workflow mutation, or financial authority."}
};
const kinds:any={support:"💬 Support",customer_task:"✅ Customer Task",service_recovery:"🛟 Service Recovery",housing:"🏠 Housing",travel:"✈️ Travel"};
export default function OperationsCommandCenter(){
 const{locale}=useZhaoXiLocale(),t=T[locale]||T["en-US"],[data,setData]=useState<any>(null),[kind,setKind]=useState(""),[risk,setRisk]=useState("");
 async function load(){const r=await fetch("/api/admin-operations-command-center",{cache:"no-store"}),j=await r.json();if(j?.ok)setData(j.data)}
 useEffect(()=>{void load()},[]);
 const items=useMemo(()=>((data?.items||[])as any[]).filter(x=>(!kind||x.kind===kind)&&(!risk||x.risk===risk)),[data,kind,risk]);
 async function cap(a:any,v:number){await fetch(`/api/admin-operations-command-center/agents/${a.id}/capacity`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({dailyCapacity:v,warningLoadPercent:a.warningLoadPercent,criticalLoadPercent:a.criticalLoadPercent,isAvailable:a.isAvailable})});await load()}
 if(!data)return <section className="zx-native-workspace" style={box}><b>🧭 {t.title}</b><p>Loading…</p></section>;
 const s=data.summary||{},f=data.forecast||{};
 return <section style={{display:"grid",gap:10}}>
  <header style={{display:"flex",alignItems:"flex-start",justifyContent:"space-between",gap:16}}><div><h1 style={{margin:"0 0 3px"}}>🧭 {t.title}</h1><small style={{color:"#64748b"}}>{t.sub}</small><small style={{display:"block",color:"#64748b",marginTop:3}}>{t.policy}</small></div><a href="/onboarding" style={{display:"inline-flex",alignItems:"center",whiteSpace:"nowrap",padding:"10px 14px",borderRadius:10,background:"#087f5b",color:"#fff",fontWeight:700,textDecoration:"none"}}>Duyệt Partner</a></header>
  <div style={metrics}><M l={t.backlog} v={s.totalBacklog}/><M l={t.overdue} v={s.overdue}/><M l={t.due2} v={s.due2h}/><M l={t.due24} v={s.due24h}/><M l={t.unassigned} v={s.unassigned}/><M l={t.recovery} v={s.criticalRecovery}/><M l={t.overloaded} v={s.overloadedAgents}/></div>
  <div style={three}>
   <section style={box}><b>⏱ {t.forecast}</b><div style={forecast}><M l="2h" v={f.next2Hours}/><M l="24h" v={f.next24Hours}/><M l="72h" v={f.next72Hours}/><M l={t.overdue} v={f.alreadyOverdue}/></div><strong style={{display:"block",marginTop:7}}>Risk: {f.forecastRisk}</strong></section>
   <section style={box}><b>🧩 Modules</b><div style={{display:"grid",gap:4,marginTop:7}}>{Object.entries(data.byKind||{}).map(([k,v])=><div key={k} style={line}><span>{kinds[k]||k}</span><b>{String(v)}</b></div>)}</div></section>
   <section style={box}><b>⚠ {t.bottleneck}</b><div style={{display:"grid",gap:5,marginTop:7}}>{(data.bottlenecks||[]).map((x:any)=><div key={x.code} style={{...line,padding:6,borderRadius:8,background:"#fff7ed"}}><span>{x.code}</span><b>{x.count}</b></div>)}{!data.bottlenecks?.length&&<small>✓ {t.healthy}</small>}</div></section>
  </div>
  <section style={box}><b>👥 {t.workload}</b><div style={agentGrid}>{(data.workload||[]).map((a:any)=><article key={a.id} style={{padding:8,border:"1px solid #e5ebe7",borderRadius:10}}><div style={line}><b>{a.name}</b><strong>{a.loadPercent}%</strong></div><div style={{height:7,borderRadius:99,background:"#eef2f0",overflow:"hidden",margin:"7px 0"}}><i style={{display:"block",height:"100%",width:`${Math.min(100,a.loadPercent)}%`,background:a.loadState==="critical"?"#ef4444":a.loadState==="warning"?"#f59e0b":"#07c160"}}/></div><small>{t.active}: {a.active} · {t.overdue}: {a.overdue} · 24h: {a.due24h}</small><label style={{display:"flex",gap:5,alignItems:"center",marginTop:6,fontSize:9}}>{t.capacity}<input type="number" min={1} max={500} defaultValue={a.dailyCapacity} onBlur={e=>void cap(a,Number(e.target.value))} style={{width:64}}/></label></article>)}</div></section>
  <section style={box}><div style={line}><b>📋 {t.queue}</b><div style={{display:"flex",gap:5}}><select value={kind} onChange={e=>setKind(e.target.value)}><option value="">{t.all}</option>{Object.keys(kinds).map(k=><option key={k} value={k}>{kinds[k]}</option>)}</select><select value={risk} onChange={e=>setRisk(e.target.value)}><option value="">{t.all} risk</option><option value="overdue">overdue</option><option value="critical">critical</option><option value="warning">warning</option><option value="healthy">healthy</option><option value="none">none</option></select></div></div>
   <div style={{display:"grid",gap:5,marginTop:8,maxHeight:650,overflowY:"auto"}}>{items.map((x:any)=><article key={`${x.kind}:${x.id}`} style={{display:"grid",gridTemplateColumns:"110px 1fr 150px 90px",gap:7,alignItems:"center",padding:8,border:"1px solid #e5ebe7",borderRadius:9}}><b>{kinds[x.kind]||x.kind}</b><div><b>{x.title}</b><small style={{display:"block",color:"#64748b"}}>{x.status} · {x.priority}</small></div><small>{x.assignee?.name||t.unassigned}</small><div style={{textAlign:"right"}}><b>{x.risk}</b>{x.dueAt&&<small style={{display:"block"}}>{new Date(x.dueAt).toLocaleString(locale)}</small>}</div></article>)}</div>
  </section>
 </section>
}
function M({l,v}:{l:string;v:any}){return <div style={{padding:8,border:"1px solid #e3eae6",borderRadius:10,background:"#fff"}}><small>{l}</small><b style={{display:"block",fontSize:18}}>{v??0}</b></div>}
const metrics={display:"grid",gridTemplateColumns:"repeat(7,minmax(0,1fr))",gap:6}as const,three={display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:8}as const,forecast={display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:5,marginTop:7}as const,agentGrid={display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:7,marginTop:8}as const,box={padding:10,border:"1px solid #e3eae6",borderRadius:14,background:"#fff"}as const,line={display:"flex",justifyContent:"space-between",gap:7,alignItems:"center"}as const;
