"use client";
import{useEffect,useState}from"react";
import{useZhaoXiLocale}from"@zhaoxi/i18n";
import{logoutZhaoXiSession}from"@zhaoxi/auth";
import OperationsBoard from"./OperationsBoard";import AnalyticsDashboard from"./AnalyticsDashboard";import CustomerExperiencePanel from"./CustomerExperiencePanel";import CustomerSupportPanel from"./CustomerSupportPanel";import DeliveryPricingPanel from"./DeliveryPricingPanel";import RestaurantOversightPanel from"./RestaurantOversightPanel";import SettlementPanel from"./SettlementPanel";import HousingOversightPanel from"./HousingOversightPanel";import TravelOversightPanel from"./TravelOversightPanel";import CustomerRelationshipHub from"./CustomerRelationshipHub";import CustomerOperationsHub from"./CustomerOperationsHub";import OperationsCommandCenter from"./OperationsCommandCenter";import OperationsRoutingPanel from"./OperationsRoutingPanel";import OperationsWorkflowCenter from"./OperationsWorkflowCenter";import PartnerPaymentGatewayOversight from"./PartnerPaymentGatewayOversight";import PaymentProviderHealthPanel from"./PaymentProviderHealthPanel";
import styles from"./adminGlass.module.css";
type Tab="overview"|"services"|"carRental"|"visa"|"passport"|"translation"|"otherServices"|"paymentGateways"|"command"|"routing"|"workflow"|"analytics"|"operations"|"customer"|"customerOps"|"support"|"restaurants"|"housing"|"travel"|"settlements"|"payments"|"delivery"|"relationships";
const L:any={
"vi-VN":{title:"Quản trị nền tảng",hello:"Chào mừng trở lại!",sub:"Đây là tổng quan hoạt động của nền tảng ZhaoXi.",overview:"Tổng quan",command:"Chỉ huy",routing:"Điều phối AI",workflow:"Workflow",analytics:"Phân tích",operations:"Vận hành",customer:"Giao diện",customerOps:"Customer Ops",support:"Hỗ trợ",restaurants:"Nhà hàng",housing:"Nhà ở",travel:"Du lịch",settlements:"Đối soát & phí",payments:"Thanh toán",delivery:"Phí giao hàng (Tạm ẩn)",relationships:"Quan hệ KH",ops:"VẬN HÀNH",services:"DỊCH VỤ",finance:"TÀI CHÍNH & THANH TOÁN",customers:"Khách hàng",partners:"Đối tác",transactions:"Giao dịch dịch vụ",gmv:"Doanh thu (GMV)",topPartners:"Top đối tác",serviceOverview:"Tổng quan dịch vụ",seeAll:"Xem tất cả",days:"7 ngày qua",other:"Dịch vụ khác",logout:"Đăng xuất"},
"zh-CN":{title:"平台管理",hello:"欢迎回来！",sub:"这是 ZhaoXi 平台的运营总览。",overview:"总览",command:"指挥中心",routing:"智能路由",workflow:"工作流",analytics:"分析",operations:"运营",customer:"界面",customerOps:"客户运营",support:"支持",restaurants:"餐厅",housing:"住房",travel:"旅游",settlements:"结算与费率",payments:"支付",delivery:"配送费 (暂隐)",relationships:"客户关系",ops:"运营",services:"服务",finance:"财务与支付",customers:"客户",partners:"合作伙伴",transactions:"服务交易",gmv:"GMV",topPartners:"合作伙伴排行",serviceOverview:"服务总览",seeAll:"查看全部",days:"最近7天",other:"其他服务",logout:"退出登录"},
"zh-TW":{title:"平台管理",hello:"歡迎回來！",sub:"這是 ZhaoXi 平台的營運總覽。",overview:"總覽",command:"指揮中心",routing:"智慧路由",workflow:"工作流",analytics:"分析",operations:"營運",customer:"介面",customerOps:"客戶營運",support:"支援",restaurants:"餐廳",housing:"住房",travel:"旅遊",settlements:"結算與費率",payments:"支付",delivery:"配送費 (暫隱)",relationships:"客戶關係",ops:"營運",services:"服務",finance:"財務與支付",customers:"客戶",partners:"合作夥伴",transactions:"服務交易",gmv:"GMV",topPartners:"合作夥伴排行",serviceOverview:"服務總覽",seeAll:"查看全部",days:"最近7天",other:"其他服務",logout:"登出"},
"en-US":{title:"Platform Admin",hello:"Welcome back!",sub:"This is the ZhaoXi platform activity overview.",overview:"Overview",command:"Command",routing:"AI Routing",workflow:"Workflow",analytics:"Analytics",operations:"Operations",customer:"Interface",customerOps:"Customer Ops",support:"Support",restaurants:"Restaurants",housing:"Housing",travel:"Travel",settlements:"Settlement & fees",payments:"Payments",delivery:"Delivery pricing (Paused)",relationships:"Relationships",ops:"OPERATIONS",services:"SERVICES",finance:"FINANCE & PAYMENTS",customers:"Customers",partners:"Partners",transactions:"Service transactions",gmv:"GMV",topPartners:"Top partners",serviceOverview:"Service overview",seeAll:"See all",days:"Last 7 days",other:"Other services",logout:"Sign out"}};
const spark={green:"M1 20 L10 17 L18 19 L27 14 L38 18 L50 15 L61 16 L73 13 L85 15 L98 10",purple:"M1 18 L10 20 L20 15 L30 19 L41 16 L54 18 L66 14 L78 17 L88 12 L98 14",blue:"M1 18 L12 21 L24 16 L36 20 L47 17 L58 19 L70 15 L82 17 L92 12 L99 14",orange:"M1 17 L11 20 L22 15 L34 19 L46 17 L58 18 L69 14 L80 16 L90 11 L99 13"};
export default function AdminHome(){
  const{locale}=useZhaoXiLocale(),t=L[locale]||L["en-US"],[tab,setTab]=useState<Tab>("overview"),[menuOpen,setMenuOpen]=useState(false);
  const [visitedTabs, setVisitedTabs] = useState<Set<Tab>>(() => new Set<Tab>(["overview"]));
  const groups:[string,[Tab,string,string][]][]=[["",[["overview","⌂",t.overview]]],[t.ops,[["command","◉",t.command],["routing","✦",t.routing],["workflow","▦",t.workflow],["analytics","▥",t.analytics],["operations","◎",t.operations],["customerOps","♙",t.customerOps],["customer","◈",t.customer],["support","◌",t.support]]],[t.services,[["restaurants","♨",t.restaurants],["housing","⌂",t.housing],["travel","✈",t.travel]]],[t.finance,[["settlements","◉",t.settlements],["payments","▣",t.payments],["delivery","⌖",t.delivery],["relationships","♙",t.relationships]]]];
  useEffect(()=>{
    const view=new URLSearchParams(window.location.search).get("view") as Tab|null;
    if(view&&["services","command","analytics","payments","workflow","customerOps"].includes(view)){
      setTab(view);
      setVisitedTabs(prev=>new Set(prev).add(view));
    }
    const open=()=>setMenuOpen(true);
    window.addEventListener("zhaoxi:mobile-menu",open);
    const mark=()=>{const w=window.innerWidth;document.documentElement.dataset.zxDevice=w<768?"phone":w<1200?"tablet":"desktop"};
    mark();
    window.addEventListener("resize",mark);
    return()=>{window.removeEventListener("zhaoxi:mobile-menu",open);window.removeEventListener("resize",mark)}
  },[]);
  const choose=(id:Tab)=>{
    setTab(id);
    setVisitedTabs(prev=>new Set(prev).add(id));
    setMenuOpen(false);
    if(["overview","services","command","analytics","payments","workflow","customerOps"].includes(id)){
      const u=id==="overview"?"/":`/?view=${id}`;
      window.history.replaceState({},"",u);
    }
  };
  return <main className={styles.shell}><aside className={styles.sidebar}><div className={styles.brand}><i>喜</i><b>ZHAOXI</b></div><nav>{groups.map(([g,items])=><section key={g||"home"}>{g&&<small>{g}</small>}{items.map(([id,icon,label])=><button key={id} className={tab===id?styles.active:""} onClick={()=>choose(id)}><i>{icon}</i><span>{label}</span><b>›</b></button>)}</section>)}</nav><div className={styles.adminId}><i>喜</i><span><b>Admin ZhaoXi</b><small>Super Administrator</small><em>● Online</em></span></div></aside><section className={styles.workspace}><header className={styles.localHead}><b>{t.title}</b><small>Customer · Partner · Admin</small></header>
    <div style={{ display: tab === "overview" ? "block" : "none" }}><Overview t={t}/></div>
    {visitedTabs.has("services") && <div style={{ display: tab === "services" ? "block" : "none" }}><ServiceHub t={t} choose={choose}/></div>}
    {visitedTabs.has("payments") && <div style={{ display: tab === "payments" ? "block" : "none" }}><PaymentHub t={t} choose={choose}/></div>}
    {visitedTabs.has("paymentGateways") && <div style={{ display: tab === "paymentGateways" ? "block" : "none" }} className={styles.module}><PartnerPaymentGatewayOversight/><PaymentProviderHealthPanel/></div>}
    {["carRental","visa","passport","translation","otherServices"].map((tKey) => visitedTabs.has(tKey as Tab) ? <div key={tKey} style={{ display: tab === tKey ? "block" : "none" }}><GenericServicePanel tab={tKey as Tab}/></div> : null)}
    {visitedTabs.has("workflow") && <div style={{ display: tab === "workflow" ? "block" : "none" }} className={styles.module}><OperationsWorkflowCenter/></div>}
    {visitedTabs.has("routing") && <div style={{ display: tab === "routing" ? "block" : "none" }} className={styles.module}><OperationsRoutingPanel/></div>}
    {visitedTabs.has("command") && <div style={{ display: tab === "command" ? "block" : "none" }} className={styles.module}><OperationsCommandCenter/></div>}
    {visitedTabs.has("analytics") && <div style={{ display: tab === "analytics" ? "block" : "none" }} className={styles.module}><AnalyticsDashboard/></div>}
    {visitedTabs.has("operations") && <div style={{ display: tab === "operations" ? "block" : "none" }} className={styles.module}><OperationsBoard/></div>}
    {visitedTabs.has("restaurants") && <div style={{ display: tab === "restaurants" ? "block" : "none" }} className={styles.module}><RestaurantOversightPanel/></div>}
    {visitedTabs.has("housing") && <div style={{ display: tab === "housing" ? "block" : "none" }} className={styles.module}><HousingOversightPanel/></div>}
    {visitedTabs.has("travel") && <div style={{ display: tab === "travel" ? "block" : "none" }} className={styles.module}><TravelOversightPanel/></div>}
    {visitedTabs.has("settlements") && <div style={{ display: tab === "settlements" ? "block" : "none" }} className={styles.module}><SettlementPanel/></div>}
    {visitedTabs.has("customer") && <div style={{ display: tab === "customer" ? "block" : "none" }} className={styles.module}><CustomerExperiencePanel/></div>}
    {visitedTabs.has("relationships") && <div style={{ display: tab === "relationships" ? "block" : "none" }} className={styles.module}><CustomerRelationshipHub/></div>}
    {visitedTabs.has("customerOps") && <div style={{ display: tab === "customerOps" ? "block" : "none" }} className={styles.module}><CustomerOperationsHub/></div>}
    {visitedTabs.has("support") && <div style={{ display: tab === "support" ? "block" : "none" }} className={styles.module}><CustomerSupportPanel/></div>}
    {visitedTabs.has("delivery") && <div style={{ display: tab === "delivery" ? "block" : "none" }} className={styles.module}><DeliveryPricingPanel/></div>}
  </section>{menuOpen&&<div className={styles.drawerBackdrop} onClick={()=>setMenuOpen(false)}><aside className={styles.drawer} onClick={e=>e.stopPropagation()}><header><div><i>喜</i><span><b>ZHAOXI</b><small>{t.title}</small></span></div><button onClick={()=>setMenuOpen(false)}>×</button></header><nav>{groups.map(([g,items])=><section key={g||"drawer-home"}>{g&&<small>{g}</small>}{items.map(([id,icon,label])=><button key={id} className={tab===id?styles.active:""} onClick={()=>choose(id)}><i>{icon}</i><span>{label}</span><b>›</b></button>)}</section>)}</nav><button className={styles.drawerLogout} onClick={()=>void logoutZhaoXiSession().finally(()=>{window.location.href="/"})}>↪ {t.logout}</button></aside></div>}</main>}
function GenericServicePanel({tab}:{tab:Tab}){const map:any={carRental:["🚗","Thuê xe","Quản lý nhà cung cấp xe, sản phẩm thuê xe, giá và trạng thái dịch vụ."],visa:["▣","Gia hạn Visa","Quản lý yêu cầu gia hạn visa, Partner xử lý và trạng thái hồ sơ."],passport:["▤","Làm mới hộ chiếu","Quản lý yêu cầu hộ chiếu, hồ sơ và tiến trình xử lý."],translation:["◌","Phiên dịch","Quản lý dịch vụ phiên dịch, Partner và yêu cầu khách hàng."],otherServices:["＋","Dịch vụ khác","Quản lý các nhóm dịch vụ đời sống mở rộng của ZhaoXi."]};const x=map[tab];return <section className="zx-native-workspace zx-generic-service-admin"><header><i>{x[0]}</i><div><small>ZHAOXI SERVICES</small><h1>{x[1]}</h1><p>{x[2]}</p></div></header><div className="zx-generic-service-grid"><article><b>Danh mục dịch vụ</b><small>Service catalog</small></article><article><b>Đối tác cung cấp</b><small>Partner providers</small></article><article><b>Yêu cầu khách hàng</b><small>Customer requests</small></article><article><b>Cấu hình & trạng thái</b><small>Configuration & status</small></article></div><p className="zx-service-note">Giao diện quản trị đã được tách đúng nhóm dịch vụ; API nghiệp vụ chuyên biệt sẽ tiếp tục dùng/được mở rộng theo từng module thay vì chuyển sang màn quản lý nhà hàng cũ.</p></section>}
function ServiceHub({t,choose}:{t:any;choose:(id:Tab)=>void}){const items=[
 ["restaurants","🍽","Nhà hàng","Restaurant & food service"],["housing","⌂","Nhà ở / Thuê nhà","Housing & rental"],["travel","✈","Du lịch","Travel services"],["carRental","🚗","Thuê xe","Car rental"],["visa","▣","Gia hạn Visa","Visa renewal"],["passport","▤","Làm mới hộ chiếu","Passport renewal"],["translation","◌","Phiên dịch","Translation"],["otherServices","＋","Dịch vụ khác","Other services"]
] as const;return <section className={`${styles.module} zx-admin-hub`}><header className="zx-hub-head"><div><small>ZHAOXI SERVICES</small><h1>{t.services}</h1><p>Quản lý toàn bộ nhóm dịch vụ của nền tảng, không giới hạn ở nhà hàng.</p></div></header><div className="zx-service-hub-grid">{items.map(([id,icon,name,sub])=><button key={name} onClick={()=>choose(id as Tab)}><i>{icon}</i><span><b>{name}</b><small>{sub}</small></span><em>›</em></button>)}</div></section>}
function PaymentHub({t,choose}:{t:any;choose:(id:Tab)=>void}){const items=[["settlements","◉","Đối soát & phí nền tảng","Hoa hồng, phí nền tảng, quyết toán"],["paymentGateways","▣","Cổng thanh toán","Gateway, provider health, routing"],["delivery","⌖","Phí giao hàng (Tạm ẩn)","Tạm dừng cấu hình · Khách chọn Xanh SM / Grab tự trả"],["support","◌","Hỗ trợ thanh toán","Exception, refund, dispute & support"]] as const;return <section className={`${styles.module} zx-admin-hub`}><header className="zx-hub-head"><div><small>ZHAOXI PAYMENTS</small><h1>{t.payments}</h1><p>Trung tâm quản trị tài chính và thanh toán của toàn nền tảng.</p></div></header><div className="zx-service-hub-grid">{items.map(([id,icon,name,sub])=><button key={name} onClick={()=>choose(id as Tab)}><i>{icon}</i><span><b>{name}</b><small>{sub}</small></span><em>›</em></button>)}</div></section>}
function Overview({t}:{t:any}){const partners=[["1","♙","Công ty TNHH ABC","156.4M"],["2","▣","Cửa hàng Hoa Tươi 24h","98.2M"],["3","♨","Nhà hàng Hải Sản Biển Đông","87.6M"],["4","⌂","Khanh Apartment","64.1M"],["5","☕","Cafe Milano","52.8M"]],services=[["♨",t.restaurants,"23,894 đơn","623.4M","+15.2%"],["⌂",t.housing,"12,543 lead","423.7M","+13.6%"],["✈",t.travel,"8,794 booking","187.9M","+16.1%"],["◫",t.other,"3,218 giao dịch","78.2M","+11.8%"]];return <div className={styles.overview}><section className={styles.heroCard}><div className={styles.heroTitle}><div><h1>👋 {t.hello}</h1><p>{t.sub}</p></div><button>{t.days}<span>⌄</span></button></div><div className={styles.kpis}><K icon="♟" label={t.customers} value="125,430" note="+18.6%" path={spark.green} tone="green"/><K icon="♟" label={t.partners} value="8,762" note="+12.4%" path={spark.purple} tone="purple"/><K icon="▣" label={t.transactions} value="45,231" note="+14.7%" path={spark.blue} tone="blue"/><K icon="◉" label={t.gmv} value="1.234B" note="+9.8%" path={spark.orange} tone="orange"/></div></section><section className={styles.rankCard}><header><h2>{t.topPartners}</h2><button>{t.seeAll} ›</button></header><div>{partners.map(p=><article key={p[0]}><b>{p[0]}</b><i>{p[1]}</i><span>{p[2]}</span><strong>GMV: {p[3]}</strong></article>)}</div></section><section className={styles.serviceCard}><header><h2>{t.serviceOverview}</h2><button>{t.seeAll} ›</button></header><div>{services.map(s=><article key={s[1]}><i>{s[0]}</i><span><b>{s[1]}</b><small>{s[2]}</small></span><strong>{s[3]}</strong><em>● {s[4]}</em><b className={styles.chevron}>›</b></article>)}</div></section></div>}
function K({icon,label,value,note,path,tone}:{icon:string,label:string,value:string,note:string,path:string,tone:string}){return <article className={`${styles.kpi} ${styles[tone]}`}><i>{icon}</i><div><small>{label}</small><p><b>{value}</b><em>{note}</em></p><svg viewBox="0 0 100 28" aria-hidden="true"><path d={path}/></svg></div></article>}
