"use client";
import{useEffect,useMemo,useState}from"react";import{useZhaoXiLocale}from"@zhaoxi/i18n";
type Message={id:string;senderRole:"customer"|"partner";body:string;createdAt:string;customerReadAt?:string|null;partnerReadAt?:string|null};
const C={
"zh-CN":{title:"与房源方沟通",placeholder:"输入消息…",send:"发送",me:"我",partner:"房源方",empty:"暂无消息",unread:"新消息"},
"zh-TW":{title:"與房源方溝通",placeholder:"輸入訊息…",send:"傳送",me:"我",partner:"房源方",empty:"暫無訊息",unread:"新訊息"},
"vi-VN":{title:"Trao đổi với Partner",placeholder:"Nhập tin nhắn…",send:"Gửi",me:"Tôi",partner:"Partner",empty:"Chưa có tin nhắn",unread:"Tin mới"},
"en-US":{title:"Message the housing provider",placeholder:"Type a message…",send:"Send",me:"Me",partner:"Provider",empty:"No messages yet",unread:"New"}} as const;
export default function HousingMessageThread({requestId,messages,onChanged}:{requestId:string;messages:Message[];onChanged:()=>void}){const{locale}=useZhaoXiLocale(),t=C[locale];const[text,setText]=useState(""),[busy,setBusy]=useState(false);const unread=useMemo(()=>messages.filter(m=>m.senderRole==="partner"&&!m.customerReadAt).length,[messages]);
 useEffect(()=>{if(!unread)return;fetch(`/api/customer-housing-inquiries/${requestId}/messages`,{method:"PATCH"}).then(()=>onChanged()).catch(()=>{})},[requestId,unread]);
 async function send(){if(!text.trim())return;setBusy(true);try{const r=await fetch(`/api/customer-housing-inquiries/${requestId}/messages`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({message:text})});if(r.ok){setText("");onChanged()}}finally{setBusy(false)}}
 return <section style={{marginTop:9,padding:9,borderRadius:12,border:"1px solid #e5ebe7",background:"#fff"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><b style={{fontSize:9}}>💬 {t.title}</b>{unread>0&&<span style={{padding:"3px 6px",borderRadius:999,background:"#fff1f2",color:"#b42318",fontSize:7,fontWeight:900}}>{t.unread} {unread}</span>}</div><div style={{display:"grid",gap:5,maxHeight:180,overflowY:"auto",marginTop:7}}>{!messages.length?<small style={{color:"#94a3b8"}}>{t.empty}</small>:messages.slice(-30).map(m=><div key={m.id} style={{justifySelf:m.senderRole==="customer"?"end":"start",maxWidth:"84%",padding:"6px 8px",borderRadius:10,background:m.senderRole==="customer"?"#dcfce7":"#f1f5f9",fontSize:8}}><b style={{display:"block",marginBottom:2}}>{m.senderRole==="customer"?t.me:t.partner}</b><span>{m.body}</span><small style={{display:"block",marginTop:2,color:"#64748b"}}>{new Date(m.createdAt).toLocaleString()}</small></div>)}</div><div style={{display:"grid",gridTemplateColumns:"1fr auto",gap:6,marginTop:7}}><input value={text} onChange={e=>setText(e.target.value)} placeholder={t.placeholder} maxLength={2000} style={{border:"1px solid #dbe5df",borderRadius:9,padding:"7px 8px",fontSize:8}}/><button disabled={busy||!text.trim()} onClick={()=>void send()} style={{border:0,borderRadius:9,padding:"7px 10px",background:"#07c160",color:"#fff",fontWeight:850,fontSize:8}}>{t.send}</button></div></section>
}
