"use client";
import Link from"next/link";import{useCallback,useEffect,useState}from"react";import{useZhaoXiLocale}from"@zhaoxi/i18n";import MiniTabBar from"../../_components/MiniTabBar";import{CustomerServiceIcon}from"../../_components/CustomerServiceIcon";import HousingMessageThread from"./HousingMessageThread";

type Appointment={status:"proposed"|"confirmed"|"completed"|"cancelled";scheduledAt:string;proposedBy:"customer"|"partner";note?:string|null;reminderAt?:string|null};
type History={id?:string;actorRole?:string;action?:string;at?:string;note?:string|null;scheduledAt?:string|null};
type Row={id:string;requestCode:string;status:string;createdAt:string;customerName:string;details?:Record<string,unknown>;housingLeadStage:string;listing?:{id?:string|null;code?:string;imageUrl?:string}};

const C={
"zh-CN":{title:"我的租房意向",back:"租房",empty:"暂无租房意向",new:"已提交",contacted:"房源方已联系",viewing:"预约看房",negotiating:"洽谈中",won:"已达成",lost:"已结束",moveIn:"入住日期",budget:"预算",open:"查看房源",code:"咨询编号",appointment:"看房预约",propose:"提出看房时间",date:"看房时间",note:"备注",send:"发送时间",proposed:"待确认",confirmed:"已确认",completed:"已完成",cancelled:"已取消",partnerProposed:"房源方建议了新的看房时间",accept:"确认这个时间",cancel:"取消预约",history:"跟进记录",reminder:"看房前 2 小时提醒",customer:"我",partner:"房源方",noAppointment:"尚未安排看房",system:"系统"},
"zh-TW":{title:"我的租房意向",back:"租房",empty:"暫無租房意向",new:"已提交",contacted:"房源方已聯絡",viewing:"預約看房",negotiating:"洽談中",won:"已達成",lost:"已結束",moveIn:"入住日期",budget:"預算",open:"查看房源",code:"諮詢編號",appointment:"看房預約",propose:"提出看房時間",date:"看房時間",note:"備註",send:"送出時間",proposed:"待確認",confirmed:"已確認",completed:"已完成",cancelled:"已取消",partnerProposed:"房源方建議了新的看房時間",accept:"確認這個時間",cancel:"取消預約",history:"跟進記錄",reminder:"看房前 2 小時提醒",customer:"我",partner:"房源方",noAppointment:"尚未安排看房",system:"系統"},
"vi-VN":{title:"Yêu cầu thuê nhà của tôi",back:"Thuê nhà",empty:"Bạn chưa gửi yêu cầu thuê nhà",new:"Đã gửi",contacted:"Partner đã liên hệ",viewing:"Đang hẹn xem nhà",negotiating:"Đang thương lượng",won:"Đã chốt",lost:"Đã kết thúc",moveIn:"Ngày vào ở",budget:"Ngân sách",open:"Xem nhà/phòng",code:"Mã yêu cầu",appointment:"Lịch xem nhà",propose:"Đề xuất lịch xem nhà",date:"Thời gian xem nhà",note:"Ghi chú",send:"Gửi đề xuất",proposed:"Chờ xác nhận",confirmed:"Đã xác nhận",completed:"Đã xem nhà",cancelled:"Đã hủy",partnerProposed:"Partner đề xuất một thời gian xem nhà mới",accept:"Xác nhận thời gian này",cancel:"Hủy lịch",history:"Lịch sử trao đổi",reminder:"Hệ thống đánh dấu nhắc trước 2 giờ",customer:"Tôi",partner:"Partner",noAppointment:"Chưa có lịch xem nhà",system:"Hệ thống"},
"en-US":{title:"My rental inquiries",back:"Housing",empty:"No rental inquiries yet",new:"Submitted",contacted:"Provider contacted you",viewing:"Viewing scheduled",negotiating:"Negotiating",won:"Agreed",lost:"Closed",moveIn:"Move-in",budget:"Budget",open:"View property",code:"Inquiry code",appointment:"Viewing appointment",propose:"Propose viewing time",date:"Viewing time",note:"Note",send:"Send proposal",proposed:"Awaiting confirmation",confirmed:"Confirmed",completed:"Completed",cancelled:"Cancelled",partnerProposed:"The provider proposed a new viewing time",accept:"Confirm this time",cancel:"Cancel appointment",history:"Follow-up history",reminder:"Marked for a reminder 2 hours before",customer:"Me",partner:"Provider",noAppointment:"No viewing scheduled",system:"System"}} as const;

const money=(v:unknown)=>`${Number(v||0).toLocaleString("vi-VN")} VND`;
const localInput=(iso?:string)=>{if(!iso)return"";const d=new Date(iso);if(Number.isNaN(d.getTime()))return"";const off=d.getTimezoneOffset();return new Date(d.getTime()-off*60000).toISOString().slice(0,16)};
const displayDate=(iso?:string)=>iso?new Date(iso).toLocaleString(): "—";

export default function HousingInquiryTracker(){
 const{locale}=useZhaoXiLocale(),t=C[locale];const[rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[times,setTimes]=useState<Record<string,string>>({}),[notes,setNotes]=useState<Record<string,string>>({}),[busy,setBusy]=useState("");
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch("/api/customer-housing-inquiries",{cache:"no-store"}),j=await r.json();const next=Array.isArray(j?.data)?j.data:[];setRows(next);try{const current=JSON.parse(localStorage.getItem("zhaoxi-request-codes")||"[]") as string[];const housingCodes=next.map((x:Row)=>x.requestCode).filter(Boolean);localStorage.setItem("zhaoxi-request-codes",JSON.stringify(Array.from(new Set([...current,...housingCodes])).slice(-100)))}catch{}}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 async function appointment(id:string,action:"propose"|"confirm"|"cancel"|"note",scheduledAt?:string){setBusy(id+action);try{const payload:any={action,note:notes[id]||""};if(scheduledAt)payload.scheduledAt=new Date(scheduledAt).toISOString();const r=await fetch(`/api/customer-housing-inquiries/${id}/appointment`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});if(r.ok){setNotes(v=>({...v,[id]:""}));await load()}}finally{setBusy("")}}
 return <main style={{minHeight:"100vh",background:"#f5f7f6",paddingBottom:76,fontFamily:"Inter,Arial,sans-serif"}}><header style={{position:"sticky",top:0,zIndex:10,padding:"10px 14px",background:"rgba(255,255,255,.92)",backdropFilter:"blur(12px)",display:"flex",justifyContent:"space-between",alignItems:"center",borderBottom:"1px solid #EEF2F6"}}><Link href="/housing" style={{display:"inline-flex",alignItems:"center",justifyContent:"center",width:36,height:36,borderRadius:12,background:"#FFF",border:"1px solid #E2E8F0",textDecoration:"none",color:"#1E293B",fontSize:20,lineHeight:1,boxShadow:"none"}}>‹</Link><b style={{fontSize:16,fontWeight:750,color:"#1E293B"}}>{t.title}</b><span style={{width:36}}/></header><section style={{maxWidth:760,margin:"0 auto",padding:"14px 14px 90px"}}>{loading?<p>…</p>:!rows.length?<div style={{padding:28,textAlign:"center",color:"#64748b"}}><CustomerServiceIcon serviceId="housing" size={48}/><p>{t.empty}</p></div>:<div style={{display:"grid",gap:11}}>{rows.map(r=>{const d=r.details||{},stage=(r.housingLeadStage||"new") as keyof typeof t,label=stage in t?String(t[stage]):String(stage),appt=(d.housingAppointment&&typeof d.housingAppointment==="object"?d.housingAppointment:null) as Appointment|null,history=Array.isArray(d.housingFollowupHistory)?d.housingFollowupHistory.filter(x=>x&&typeof x==="object") as History[]:[],messages=Array.isArray(d.housingMessages)?d.housingMessages.filter(x=>x&&typeof x==="object") as any[]:[];const apptLabel=appt?String(t[appt.status]):t.noAppointment;return <article key={r.id} style={{padding:11,border:"1px solid #e4ebe7",borderRadius:16,background:"#fff"}}><div style={{display:"grid",gridTemplateColumns:"72px 1fr",gap:10}}>{r.listing?.imageUrl?<img src={r.listing.imageUrl} alt="" style={{width:72,height:72,objectFit:"cover",borderRadius:11}}/>:<div style={{width:72,height:72,display:"grid",placeItems:"center",background:"#eef8f1",borderRadius:11,fontSize:30}}><CustomerServiceIcon serviceId="housing" size={40}/></div>}<div><div style={{display:"flex",justifyContent:"space-between",gap:8}}><b style={{fontSize:10}}>{t.code}: {r.requestCode}</b><span style={{padding:"3px 6px",borderRadius:999,background:stage==="won"?"#ecfdf5":stage==="lost"?"#f1f5f9":"#eff6ff",color:stage==="won"?"#067647":stage==="lost"?"#64748b":"#1d4ed8",fontSize:7,fontWeight:900}}>{label}</span></div><small style={{display:"block",marginTop:5,color:"#64748b"}}>{t.moveIn}: {String(d.requestedMoveInDate||"—")}</small><small style={{display:"block",color:"#64748b"}}>{t.budget}: {d.budget?money(d.budget):"—"}</small>{r.listing?.id&&<Link href={`/housing/${r.listing.id}`} style={{display:"inline-block",marginTop:6,fontSize:8,fontWeight:850,color:"#078343",textDecoration:"none"}}>{t.open} ›</Link>}</div></div>
 <section style={{marginTop:10,padding:10,borderRadius:13,background:"#f8faf9",border:"1px solid #edf1ef"}}><div style={{display:"flex",justifyContent:"space-between",gap:8,alignItems:"center"}}><b style={{fontSize:10}}>📅 {t.appointment}</b><span style={{fontSize:8,fontWeight:850,color:appt?.status==="confirmed"?"#067647":appt?.status==="cancelled"?"#64748b":"#1d4ed8"}}>{apptLabel}</span></div>{appt&&<><small style={{display:"block",marginTop:5}}>{t.date}: <b>{displayDate(appt.scheduledAt)}</b></small>{appt.reminderAt&&appt.status==="confirmed"&&<small style={{display:"block",marginTop:3,color:"#078343"}}>⏰ {t.reminder}</small>}{appt.status==="proposed"&&appt.proposedBy==="partner"&&<p style={{fontSize:9,color:"#9a3412"}}>{t.partnerProposed}</p>}<div style={{display:"flex",gap:6,marginTop:7,flexWrap:"wrap"}}>{appt.status==="proposed"&&appt.proposedBy==="partner"&&<button disabled={!!busy} onClick={()=>void appointment(r.id,"confirm")} style={good}>{t.accept}</button>}{!["completed","cancelled"].includes(appt.status)&&<button disabled={!!busy} onClick={()=>void appointment(r.id,"cancel")} style={danger}>{t.cancel}</button>}</div></>}
 {(!appt||appt.status==="cancelled")&&<div style={{display:"grid",gridTemplateColumns:"1fr",gap:6,marginTop:8}}><label style={field}>{t.propose}<input type="datetime-local" value={times[r.id]||""} min={localInput(new Date(Date.now()+5*60000).toISOString())} onChange={e=>setTimes(v=>({...v,[r.id]:e.target.value}))}/></label><label style={field}>{t.note}<input value={notes[r.id]||""} onChange={e=>setNotes(v=>({...v,[r.id]:e.target.value}))}/></label><button disabled={!times[r.id]||!!busy} onClick={()=>void appointment(r.id,"propose",times[r.id])} style={good}>{t.send}</button></div>}
 </section>
 <HousingMessageThread requestId={r.id} messages={messages} onChanged={()=>void load()}/>
 {history.length>0&&<details style={{marginTop:8}}><summary style={{cursor:"pointer",fontSize:9,fontWeight:850}}>{t.history} · {history.length}</summary><div style={{display:"grid",gap:5,marginTop:7}}>{[...history].reverse().slice(0,12).map((h,i)=><div key={h.id||i} style={{padding:7,borderRadius:9,background:"#f8faf9",fontSize:8}}><b>{h.actorRole==="customer"?t.customer:h.actorRole==="partner"?t.partner:t.system}</b> · {String(h.action||"")} · {h.at?new Date(h.at).toLocaleString():""}{h.scheduledAt&&<span> · {displayDate(h.scheduledAt)}</span>}{h.note&&<small style={{display:"block",marginTop:2,color:"#64748b"}}>{String(h.note)}</small>}</div>)}</div></details>}
 </article>})}</div>}</section><MiniTabBar/></main>}
const field={display:"grid",gap:4,fontSize:8,color:"#64748b"} as const;
const good={border:0,borderRadius:9,padding:"7px 9px",background:"#07c160",color:"#fff",fontWeight:850,fontSize:8} as const;
const danger={border:0,borderRadius:9,padding:"7px 9px",background:"#fff1f2",color:"#b42318",fontWeight:850,fontSize:8} as const;
