import { qrPairingService } from "@/lib/services/qr-pairing-service";
import { trustedDeviceCookieMaxAge, trustedDeviceCookieName } from "@/lib/services/trusted-device-service";
const esc=(v:string)=>v.replace(/[<>&"']/g,(c)=>({"<":"&lt;",">":"&gt;","&":"&amp;","\"":"&quot;","'":"&#39;"}[c]||c));
const getCookie=(r:Request,name:string)=>r.headers.get("cookie")?.split(";").map(x=>x.trim()).find(x=>x.startsWith(`${name}=`))?.slice(name.length+1);
const copy={"vi-VN":{title:"Xác nhận đăng nhập ZhaoXi",body:"Bạn đã quét mã ZhaoXi. WeChat chỉ được dùng để quét/mở liên kết và không xác minh danh tính WeChat của bạn.",button:"Xác nhận trên thiết bị này",first:"Nếu đây là lần đầu, ZhaoXi sẽ tạo danh tính khách tạm thời trên thiết bị này.",success:"Đã xác nhận. Hãy quay lại thiết bị ban đầu.",known:"Đã nhận diện thiết bị ZhaoXi này.",new:"Đã tạo danh tính ZhaoXi tạm thời.",invalid:"Mã QR không hợp lệ hoặc đã hết hạn."},"en-US":{title:"Confirm ZhaoXi sign-in",body:"You scanned a ZhaoXi code. WeChat is only acting as the scanner/link opener and does not verify your WeChat identity.",button:"Confirm on this device",first:"On first use, ZhaoXi creates a temporary guest identity on this device.",success:"Confirmed. Return to the original device.",known:"This ZhaoXi device was recognized.",new:"A temporary ZhaoXi identity was created.",invalid:"The QR code is invalid or expired."},"zh-CN":{title:"确认赵喜登录",body:"你扫描的是赵喜二维码。微信仅用于扫码/打开链接，不代表赵喜已验证你的微信身份。",button:"在此设备确认",first:"首次使用时，赵喜会在此设备建立临时访客身份。",success:"已确认，请返回原设备。",known:"已识别此赵喜设备。",new:"已建立临时赵喜身份。",invalid:"二维码无效或已过期。"},"zh-TW":{title:"確認趙喜登入",body:"你掃描的是趙喜 QR。微信僅用於掃碼/開啟連結，不代表趙喜已驗證你的微信身分。",button:"在此裝置確認",first:"首次使用時，趙喜會在此裝置建立臨時訪客身分。",success:"已確認，請返回原裝置。",known:"已識別此趙喜裝置。",new:"已建立臨時趙喜身分。",invalid:"QR 無效或已過期。"}} as const;
type Locale=keyof typeof copy;const locale=(r:Request):Locale=>{const x=new URL(r.url).searchParams.get("locale");return x&&x in copy?x as Locale:"vi-VN"};
const page=(lang:string,title:string,body:string,status=200,extra?:HeadersInit)=>{const h=new Headers(extra);h.set("content-type","text/html; charset=utf-8");h.set("cache-control","no-store");h.set("x-frame-options","DENY");return new Response(`<!doctype html><html lang="${esc(lang)}"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><body style="font-family:system-ui;background:#f6faf7;margin:0;display:grid;place-items:center;min-height:100vh"><main style="max-width:420px;margin:18px;padding:28px;background:white;border-radius:24px;box-shadow:0 12px 40px #0001;text-align:center"><div style="font-size:42px;color:#07c160">喜</div><h2>${esc(title)}</h2>${body}</main></body></html>`,{status,headers:h});};
export async function GET(r:Request,{params}:{params:Promise<{id:string}>}){const {id}=await params;const u=new URL(r.url);const l=locale(r),t=copy[l],s=u.searchParams.get("s")||"";return page(l,t.title,`<p>${esc(t.body)}</p><form method="post"><input type="hidden" name="s" value="${esc(s)}"><input type="hidden" name="locale" value="${esc(l)}"><button style="border:0;border-radius:14px;background:#07c160;color:white;padding:14px 24px;font-size:17px;font-weight:700">${esc(t.button)}</button></form><p style="color:#64748b;font-size:13px">${esc(t.first)}</p>`);}
export async function POST(r:Request,{params}:{params:Promise<{id:string}>}){const {id}=await params;const form=await r.formData();const l=(String(form.get("locale")||"vi-VN") in copy?String(form.get("locale")) as Locale:"vi-VN"),t=copy[l];const result=await qrPairingService.confirm({id,secret:String(form.get("s")||""),trustedDeviceToken:getCookie(r,trustedDeviceCookieName)});if(!result.ok)return page(l,t.title,`<p>${esc(t.invalid)}</p>`,400);const h=new Headers();if(result.trustedToken)h.append("set-cookie",`${trustedDeviceCookieName}=${result.trustedToken}; Path=/; Max-Age=${trustedDeviceCookieMaxAge}; HttpOnly; Secure; SameSite=Lax`);return page(l,t.title,`<p>${esc(result.reusedIdentity?t.known:t.new)}</p><p>${esc(t.success)}</p>`,200,h);}
