"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
type Row={app:"customer"|"partner"|"admin";accessMode:"closed"|"beta"|"public";publicRolloutPercent:number;maintenanceEnabled:boolean;maintenanceMessage:Record<string,string>;notice:Record<string,string>;updatedAt:string};
const names={customer:"Customer",partner:"Partner",admin:"Admin"};
export default function LaunchControl(){
 const[rows,setRows]=useState<Row[]>([]);const[busy,setBusy]=useState<string|null>(null);const[error,setError]=useState("");
 const load=async()=>{try{const r=await fetch("/api/platform-runtime-control/admin",{cache:"no-store"});const x=await r.json();if(!r.ok)throw new Error(x?.error?.code||"LOAD_FAILED");setRows((x.data||[]).filter((row:{app:string})=>row.app!=="driver") as Row[])}catch(e){setError(e instanceof Error?e.message:"LOAD_FAILED")}};
 useEffect(()=>{void load()},[]);
 async function patch(row:Row,body:Partial<Row>){setBusy(row.app);setError("");try{const r=await fetch(`/api/platform-runtime-control/admin/${row.app}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const x=await r.json();if(!r.ok)throw new Error(x?.error?.code||"UPDATE_FAILED");await load()}catch(e){setError(e instanceof Error?e.message:"UPDATE_FAILED")}finally{setBusy(null)}}
 return <main style={{width:"min(100%,520px)",margin:"0 auto",minHeight:"100dvh",padding:18,background:"#f5f7fa",fontFamily:"Inter,Arial,sans-serif"}}>
  <Link href="/" style={{textDecoration:"none",color:"#64748b"}}>← Admin</Link>
  <h1 style={{fontSize:24,marginBottom:4}}>Public Beta Launch Control</h1><p style={{color:"#64748b",marginTop:0}}>Open / Beta / Closed · staged Public rollout · Maintenance</p>
  {error&&<div style={{padding:12,background:"#fff1f2",color:"#be123c",borderRadius:12,marginBottom:12}}>{error}</div>}
  <div style={{display:"grid",gap:12}}>{rows.map(row=><article key={row.app} style={{padding:16,borderRadius:18,background:"#fff",border:"1px solid #e5e7eb"}}>
   <div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><b>{names[row.app]}</b><span style={{fontSize:12,padding:"5px 8px",borderRadius:999,background:row.maintenanceEnabled?"#fee2e2":"#dcfce7",color:row.maintenanceEnabled?"#991b1b":"#166534"}}>{row.maintenanceEnabled?"MAINTENANCE":"ONLINE"}</span></div>
   <div style={{display:"flex",gap:6,marginTop:12}}>{(["closed","beta","public"] as const).map(mode=><button key={mode} disabled={busy===row.app||row.app==="admin"&&mode==="closed"} onClick={()=>void patch(row,{accessMode:mode})} style={{flex:1,border:0,borderRadius:10,padding:9,background:row.accessMode===mode?"#07c160":"#f1f5f9",color:row.accessMode===mode?"#fff":"#475569",fontWeight:800}}>{mode.toUpperCase()}</button>)}</div>{row.app!=="admin"&&<div style={{marginTop:12,padding:12,borderRadius:12,background:"#f8fafc"}}><div style={{display:"flex",justifyContent:"space-between",gap:8}}><b>Public rollout</b><b>{row.publicRolloutPercent}%</b></div><input type="range" min="0" max="100" step="5" value={row.publicRolloutPercent} onChange={e=>setRows(v=>v.map(x=>x.app===row.app?{...x,publicRolloutPercent:Number(e.target.value)}:x))} onMouseUp={()=>void patch(row,{publicRolloutPercent:row.publicRolloutPercent})} onTouchEnd={()=>void patch(row,{publicRolloutPercent:row.publicRolloutPercent})} style={{width:"100%",marginTop:8}}/><div style={{display:"grid",gridTemplateColumns:"repeat(5,1fr)",gap:5,marginTop:7}}>{[5,10,25,50,100].map(n=><button key={n} disabled={busy===row.app} onClick={()=>void patch(row,{publicRolloutPercent:n})} style={{border:0,borderRadius:8,padding:"6px 2px",background:row.publicRolloutPercent===n?"#dbeafe":"#fff",fontSize:11,fontWeight:800}}>{n}%</button>)}</div></div>}
   {row.app!=="admin"&&<><button disabled={busy===row.app} onClick={()=>void patch(row,{maintenanceEnabled:!row.maintenanceEnabled})} style={{width:"100%",marginTop:10,border:0,borderRadius:11,padding:10,background:row.maintenanceEnabled?"#7f1d1d":"#fff1f2",color:row.maintenanceEnabled?"#fff":"#be123c",fontWeight:900}}>🛠 Maintenance: {row.maintenanceEnabled?"ON":"OFF"}</button><textarea placeholder="Thông báo bảo trì tiếng Việt" value={row.maintenanceMessage?.["vi-VN"]||""} onChange={e=>setRows(v=>v.map(x=>x.app===row.app?{...x,maintenanceMessage:{...x.maintenanceMessage,"vi-VN":e.target.value}}:x))} onBlur={()=>void patch(row,{maintenanceMessage:row.maintenanceMessage})} style={{width:"100%",marginTop:10,minHeight:70,padding:10,border:"1px solid #dbe3dd",borderRadius:10}}/></>}
  </article>)}</div>
 </main>
}
