import{and,asc,desc,eq,inArray,or}from"drizzle-orm";import{getDb}from"@/db";import{customerOperationEvents,customerOperationTasks,customerRelationshipProfiles,customerSegmentMembers,customerSegments,customerServiceRecoveryCases,operationsAuditLogs,userRoles,users}from"@/db/schema";

type TaskStatus="open"|"in_progress"|"completed"|"cancelled";
type RecoveryStatus="open"|"in_progress"|"resolved"|"cancelled";
const taskStatuses:TaskStatus[]=["open","in_progress","completed","cancelled"];
const recoveryStatuses:RecoveryStatus[]=["open","in_progress","resolved","cancelled"];
const priorities=["low","normal","high","urgent"] as const;
const severities=["normal","high","critical"] as const;
function clean(v:any,n=1000){return String(v??"").trim().slice(0,n)}
function date(v:any){const s=clean(v,40);if(!s)return null;const d=new Date(s);return Number.isFinite(d.getTime())?d:null}
function overdue(d:any,status:string){return Boolean(d)&&!["completed","resolved","cancelled"].includes(status)&&new Date(d).getTime()<Date.now()}

export class AdminCustomerOperationsService{
 async agents(){const db=getDb(),roles=await db.select().from(userRoles).where(and(eq(userRoles.role,"admin"),eq(userRoles.isActive,true))),ids=roles.map(x=>x.userId),rows=ids.length?await db.select({id:users.id,nickname:users.nickname,email:users.email,phone:users.phone}).from(users).where(inArray(users.id,ids)):[];return rows.map(x=>({id:x.id,name:x.nickname||x.email||x.phone||x.id}))}

 async queue(input:{status?:string;assignee?:string;priority?:string}={}){const db=getDb(),[tasks,recoveries,agents,segments]=await Promise.all([db.select().from(customerOperationTasks).orderBy(asc(customerOperationTasks.dueAt),desc(customerOperationTasks.createdAt)),db.select().from(customerServiceRecoveryCases).orderBy(asc(customerServiceRecoveryCases.dueAt),desc(customerServiceRecoveryCases.createdAt)),this.agents(),db.select().from(customerSegments).where(eq(customerSegments.isActive,true))]);const customerIds=[...new Set([...tasks.map(x=>x.customerId),...recoveries.map(x=>x.customerId)])],customers=customerIds.length?await db.select({id:users.id,nickname:users.nickname,email:users.email,phone:users.phone}).from(users).where(inArray(users.id,customerIds)):[],cmap=new Map(customers.map(x=>[x.id,x] as const)),amap=new Map(agents.map(x=>[x.id,x] as const));const taskRows=tasks.map(x=>({...x,customer:cmap.get(x.customerId)||null,assignedAgent:x.assignedAdminUserId?amap.get(x.assignedAdminUserId)||null:null,overdue:overdue(x.dueAt,x.status)})).filter(x=>(!input.status||x.status===input.status)&&(!input.assignee||x.assignedAdminUserId===input.assignee)&&(!input.priority||x.priority===input.priority));const recoveryRows=recoveries.map(x=>({...x,customer:cmap.get(x.customerId)||null,assignedAgent:x.assignedAdminUserId?amap.get(x.assignedAdminUserId)||null:null,overdue:overdue(x.dueAt,x.status)})).filter(x=>(!input.status||x.status===input.status)&&(!input.assignee||x.assignedAdminUserId===input.assignee));const openTasks=tasks.filter(x=>!["completed","cancelled"].includes(x.status)),openRecovery=recoveries.filter(x=>!["resolved","cancelled"].includes(x.status));return{tasks:taskRows,recoveries:recoveryRows,agents,segments,summary:{openTasks:openTasks.length,overdueTasks:openTasks.filter(x=>overdue(x.dueAt,x.status)).length,followUpsDueToday:openTasks.filter(x=>x.taskType==="follow_up"&&x.dueAt&&new Date(x.dueAt).toDateString()===new Date().toDateString()).length,openRecovery:openRecovery.length,criticalRecovery:openRecovery.filter(x=>x.severity==="critical").length,unassigned:openTasks.filter(x=>!x.assignedAdminUserId).length+openRecovery.filter(x=>!x.assignedAdminUserId).length}}}

 async customerWorkspace(customerId:string){const db=getDb(),customer=(await db.select({id:users.id,nickname:users.nickname,email:users.email,phone:users.phone,status:users.status}).from(users).where(eq(users.id,customerId)).limit(1))[0];if(!customer)throw new Error("CUSTOMER_NOT_FOUND");const[tasks,recoveries,memberships,profile,events]=await Promise.all([db.select().from(customerOperationTasks).where(eq(customerOperationTasks.customerId,customerId)).orderBy(desc(customerOperationTasks.createdAt)),db.select().from(customerServiceRecoveryCases).where(eq(customerServiceRecoveryCases.customerId,customerId)).orderBy(desc(customerServiceRecoveryCases.createdAt)),db.select({segmentId:customerSegments.id,code:customerSegments.code,name:customerSegments.name,description:customerSegments.description}).from(customerSegmentMembers).innerJoin(customerSegments,eq(customerSegmentMembers.segmentId,customerSegments.id)).where(eq(customerSegmentMembers.customerId,customerId)),db.select().from(customerRelationshipProfiles).where(eq(customerRelationshipProfiles.customerId,customerId)).limit(1),db.select().from(customerOperationEvents).where(eq(customerOperationEvents.customerId,customerId)).orderBy(desc(customerOperationEvents.createdAt)).limit(150)]);return{customer,relationship:profile[0]||null,tasks:tasks.map(x=>({...x,overdue:overdue(x.dueAt,x.status)})),recoveries:recoveries.map(x=>({...x,overdue:overdue(x.dueAt,x.status)})),segments:memberships,events,policy:{operationalOnly:true,automaticCustomerContact:false,automaticCompensation:false,automaticFinancialActions:false,partnerFundsAuthority:false}}}

 async createTask(actorId:string,customerId:string,input:any){const title=clean(input.title,220);if(!title)throw new Error("TASK_TITLE_REQUIRED");const db=getDb(),priority=priorities.includes(String(input.priority) as any)?String(input.priority):"normal",row=(await db.insert(customerOperationTasks).values({customerId,title,description:clean(input.description,3000),taskType:clean(input.taskType,40)||"follow_up",priority,status:"open",assignedAdminUserId:clean(input.assignedAdminUserId,80)||null,dueAt:date(input.dueAt),sourceType:clean(input.sourceType,48)||null,sourceId:clean(input.sourceId,120)||null,createdByAdminUserId:actorId}).returning())[0];await this.event(actorId,customerId,"task",row.id,"task_created",{priority,taskType:row.taskType});return row}

 async updateTask(actorId:string,taskId:string,input:any){const db=getDb(),row=(await db.select().from(customerOperationTasks).where(eq(customerOperationTasks.id,taskId)).limit(1))[0];if(!row)throw new Error("TASK_NOT_FOUND");const status=taskStatuses.includes(String(input.status) as TaskStatus)?String(input.status):row.status,priority=priorities.includes(String(input.priority) as any)?String(input.priority):row.priority,completedAt=status==="completed"?(row.completedAt||new Date()):status!=="completed"?null:row.completedAt,[saved]=await db.update(customerOperationTasks).set({title:input.title!==undefined?clean(input.title,220):row.title,description:input.description!==undefined?clean(input.description,3000):row.description,taskType:input.taskType!==undefined?(clean(input.taskType,40)||row.taskType):row.taskType,priority,status,assignedAdminUserId:input.assignedAdminUserId!==undefined?(clean(input.assignedAdminUserId,80)||null):row.assignedAdminUserId,dueAt:input.dueAt!==undefined?date(input.dueAt):row.dueAt,completedAt,updatedAt:new Date()}).where(eq(customerOperationTasks.id,taskId)).returning();await this.event(actorId,row.customerId,"task",taskId,"task_updated",{status,priority,assignedAdminUserId:saved.assignedAdminUserId});return saved}

 async createSegment(actorId:string,input:any){const name=clean(input.name,120),code=(clean(input.code||name,60).toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_+|_+$/g,""));if(!name||!code)throw new Error("SEGMENT_FIELDS_REQUIRED");return(await getDb().insert(customerSegments).values({name,code,description:clean(input.description,1500),createdByAdminUserId:actorId}).returning())[0]}

 async setSegment(actorId:string,customerId:string,segmentId:string,enabled:boolean){const db=getDb();if(enabled)await db.insert(customerSegmentMembers).values({segmentId,customerId,addedByAdminUserId:actorId}).onConflictDoNothing();else await db.delete(customerSegmentMembers).where(and(eq(customerSegmentMembers.segmentId,segmentId),eq(customerSegmentMembers.customerId,customerId)));await this.event(actorId,customerId,"segment",segmentId,enabled?"segment_added":"segment_removed",{segmentId});return this.customerWorkspace(customerId)}

 async createRecovery(actorId:string,customerId:string,input:any){const reason=clean(input.reason,120),summary=clean(input.summary,4000);if(!reason||!summary)throw new Error("RECOVERY_FIELDS_REQUIRED");const severity=severities.includes(String(input.severity) as any)?String(input.severity):"normal",db=getDb(),row=(await db.insert(customerServiceRecoveryCases).values({customerId,reason,summary,severity,status:"open",assignedAdminUserId:clean(input.assignedAdminUserId,80)||null,dueAt:date(input.dueAt),sourceType:clean(input.sourceType,48)||null,sourceId:clean(input.sourceId,120)||null,createdByAdminUserId:actorId}).returning())[0];await this.event(actorId,customerId,"recovery",row.id,"recovery_created",{severity,reason});return row}

 async updateRecovery(actorId:string,recoveryId:string,input:any){const db=getDb(),row=(await db.select().from(customerServiceRecoveryCases).where(eq(customerServiceRecoveryCases.id,recoveryId)).limit(1))[0];if(!row)throw new Error("RECOVERY_NOT_FOUND");const status=recoveryStatuses.includes(String(input.status) as RecoveryStatus)?String(input.status):row.status,severity=severities.includes(String(input.severity) as any)?String(input.severity):row.severity,resolvedAt=status==="resolved"?(row.resolvedAt||new Date()):status!=="resolved"?null:row.resolvedAt,[saved]=await db.update(customerServiceRecoveryCases).set({reason:input.reason!==undefined?clean(input.reason,120):row.reason,summary:input.summary!==undefined?clean(input.summary,4000):row.summary,severity,status,assignedAdminUserId:input.assignedAdminUserId!==undefined?(clean(input.assignedAdminUserId,80)||null):row.assignedAdminUserId,dueAt:input.dueAt!==undefined?date(input.dueAt):row.dueAt,resolutionNote:input.resolutionNote!==undefined?clean(input.resolutionNote,4000):row.resolutionNote,resolvedAt,updatedAt:new Date()}).where(eq(customerServiceRecoveryCases.id,recoveryId)).returning();await this.event(actorId,row.customerId,"recovery",recoveryId,"recovery_updated",{status,severity,assignedAdminUserId:saved.assignedAdminUserId});return saved}

 private async event(actorId:string,customerId:string,entityType:string,entityId:string,action:string,metadata:Record<string,unknown>){const db=getDb();await db.insert(customerOperationEvents).values({customerId,actorAdminUserId:actorId,entityType,entityId,action,metadata});await db.insert(operationsAuditLogs).values({actorUserId:actorId,area:"customer_operations",action,targetType:entityType,targetId:entityId,metadata:{...metadata,operationalOnly:true,automaticFinancialActions:false}})}
}
export const adminCustomerOperationsService=new AdminCustomerOperationsService();
