import{and,desc,eq,inArray}from"drizzle-orm";import{getDb}from"@/db";import{customerSupportMessages,customerSupportThreads,operationsAuditLogs,supportSatisfaction,supportSlaPolicies,supportThreadEvents,userRoles,users}from"@/db/schema";
function clean(v:any,n=2000){return String(v||"").trim().slice(0,n)}
const statuses=["open","pending","resolved"]as const,priorities=["normal","urgent","critical"]as const;
function mins(a:any,b:any){if(!a||!b)return null;return Math.max(0,Math.round((new Date(b).getTime()-new Date(a).getTime())/60000))}
function averageMinutes(values:Array<number|null>){const xs=values.filter((x):x is number=>x!==null);return xs.length?Math.round(xs.reduce((sum,value)=>sum+value,0)/xs.length):0}
export class AdminSupportDeskService{
 async agents(){const db=getDb(),roles=await db.select().from(userRoles).where(and(eq(userRoles.role,"admin"),eq(userRoles.isActive,true))),ids=roles.map(x=>x.userId),rows=ids.length?await db.select().from(users).where(inArray(users.id,ids)):[];return rows.map(x=>({id:x.id,nickname:x.nickname||x.email||x.phone||x.id,email:x.email||"",phone:x.phone||""}))}
 async policies(){const rows=await getDb().select().from(supportSlaPolicies),rank:Record<string,number>={critical:0,urgent:1,normal:2};return rows.sort((a,b)=>(rank[a.priority]??9)-(rank[b.priority]??9))}
 async queue(adminUserId:string){const db=getDb(),threads=await db.select().from(customerSupportThreads).orderBy(desc(customerSupportThreads.lastMessageAt)),ids=threads.map(x=>x.id),msgs=ids.length?await db.select().from(customerSupportMessages).where(inArray(customerSupportMessages.threadId,ids)):[],customers=threads.length?await db.select().from(users).where(inArray(users.id,[...new Set(threads.map(x=>x.customerId))])):[],agents=await this.agents(),policies=await this.policies(),now=Date.now(),sats=ids.length?await db.select().from(supportSatisfaction).where(inArray(supportSatisfaction.threadId,ids)):[];const enriched=threads.map(t=>{const m=msgs.filter(x=>x.threadId===t.id),last=m.slice().sort((a,b)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime())[0],unread=m.filter(x=>x.senderRole==="customer"&&!x.adminReadAt).length,customer=customers.find(x=>x.id===t.customerId),agent=agents.find(x=>x.id===t.assignedAdminUserId),supervisor=agents.find(x=>x.id===t.supervisorAdminUserId),firstOverdue=!t.firstRespondedAt&&Boolean(t.firstResponseDueAt)&&new Date(t.firstResponseDueAt!).getTime()<now,resolutionOverdue=t.status!=="resolved"&&Boolean(t.resolutionDueAt)&&new Date(t.resolutionDueAt!).getTime()<now;return{...t,lastMessage:last?.body||"",unreadCount:unread,customer:{id:t.customerId,name:customer?.nickname||customer?.phone||customer?.email||t.customerId},assignedAgent:agent||null,supervisor:supervisor||null,slaOverdue:firstOverdue||resolutionOverdue,firstResponseOverdue:firstOverdue,resolutionOverdue,satisfaction:sats.find(x=>x.threadId===t.id)||null}});const open=enriched.filter(x=>x.status!=="resolved"),resolved=enriched.filter(x=>x.status==="resolved"),loads=new Map<string,number>(agents.map(a=>[a.id,open.filter(x=>x.assignedAdminUserId===a.id).length] as [string,number])),recommended=agents.slice().sort((a,b)=>(loads.get(a.id)||0)-(loads.get(b.id)||0))[0]||null,threadsWithRouting=enriched.map(x=>({...x,recommendedAgent:!x.assignedAdminUserId?recommended:null}));return{threads:threadsWithRouting,agents,policies,routing:{strategy:"least_active_agent",automaticAssignment:false,recommendedAgent:recommended},summary:{total:enriched.length,open:open.length,pending:enriched.filter(x=>x.status==="pending").length,resolved:resolved.length,unassigned:open.filter(x=>!x.assignedAdminUserId).length,overdue:open.filter(x=>x.slaOverdue).length,escalated:open.filter(x=>x.escalationLevel>0).length,critical:open.filter(x=>x.priority==="critical").length,unread:enriched.reduce((n,x)=>n+x.unreadCount,0),avgFirstResponseMinutes:Math.round(resolved.map(x=>mins(x.createdAt,x.firstRespondedAt)).filter((x):x is number=>x!=null).reduce((a,c,_,arr)=>a+c/Math.max(1,arr.length),0)),avgResolutionMinutes:Math.round(resolved.map(x=>mins(x.createdAt,x.resolvedAt)).filter((x):x is number=>x!=null).reduce((a,c,_,arr)=>a+c/Math.max(1,arr.length),0)),avgSatisfaction:sats.length?Number((sats.reduce((a,x)=>a+x.rating,0)/sats.length).toFixed(2)):null}}}
 async thread(id:string){const db=getDb(),t=(await db.select().from(customerSupportThreads).where(eq(customerSupportThreads.id,id)).limit(1))[0];if(!t)throw new Error("SUPPORT_THREAD_NOT_FOUND");const[messages,events,sat]=await Promise.all([db.select().from(customerSupportMessages).where(eq(customerSupportMessages.threadId,id)),db.select().from(supportThreadEvents).where(eq(supportThreadEvents.threadId,id)).orderBy(desc(supportThreadEvents.createdAt)),db.select().from(supportSatisfaction).where(eq(supportSatisfaction.threadId,id)).limit(1)]);return{thread:t,messages,events,satisfaction:sat[0]||null}}
 async assign(adminUserId:string,id:string,agentUserId:string|null){const db=getDb(),t=await this.mustThread(id);if(agentUserId)await this.mustAgent(agentUserId);const now=new Date(),[u]=await db.update(customerSupportThreads).set({assignedAdminUserId:agentUserId,updatedAt:now}).where(eq(customerSupportThreads.id,id)).returning();await this.event(adminUserId,id,"assignment_changed",t.assignedAdminUserId,agentUserId,{previous:t.assignedAdminUserId,next:agentUserId});return u}
 async status(adminUserId:string,id:string,status:string){if(!statuses.includes(status as any))throw new Error("SUPPORT_STATUS_INVALID");const db=getDb(),t=await this.mustThread(id),now=new Date(),resolvedAt=status==="resolved"?now:null,[u]=await db.update(customerSupportThreads).set({status,resolvedAt,updatedAt:now}).where(eq(customerSupportThreads.id,id)).returning();await this.event(adminUserId,id,"status_changed",null,null,{from:t.status,to:status});return u}
 async priority(adminUserId:string,id:string,priority:string){if(!priorities.includes(priority as any))throw new Error("SUPPORT_PRIORITY_INVALID");const db=getDb(),t=await this.mustThread(id),policy=(await db.select().from(supportSlaPolicies).where(eq(supportSlaPolicies.priority,priority)).limit(1))[0];if(!policy)throw new Error("SUPPORT_SLA_POLICY_MISSING");const now=new Date(),[u]=await db.update(customerSupportThreads).set({priority,firstResponseDueAt:t.firstRespondedAt?t.firstResponseDueAt:new Date(t.createdAt.getTime()+policy.firstResponseMinutes*60000),resolutionDueAt:new Date(t.createdAt.getTime()+policy.resolutionMinutes*60000),updatedAt:now}).where(eq(customerSupportThreads.id,id)).returning();await this.event(adminUserId,id,"priority_changed",null,null,{from:t.priority,to:priority});return u}
 async escalate(adminUserId:string,id:string,input:any){const db=getDb(),t=await this.mustThread(id),reason=clean(input.reason,1200);if(!reason)throw new Error("ESCALATION_REASON_REQUIRED");const supervisor=input.supervisorAdminUserId?String(input.supervisorAdminUserId):null;if(supervisor)await this.mustAgent(supervisor);const now=new Date(),level=Math.max(1,Math.min(3,Number(input.level||t.escalationLevel+1))),[u]=await db.update(customerSupportThreads).set({escalationLevel:level,escalatedAt:now,escalationReason:reason,supervisorAdminUserId:supervisor||t.supervisorAdminUserId,priority:level>=2?"critical":t.priority==="normal"?"urgent":t.priority,updatedAt:now}).where(eq(customerSupportThreads.id,id)).returning();await this.event(adminUserId,id,"escalated",null,supervisor,{level,reason});return u}
 async clearEscalation(adminUserId:string,id:string){const db=getDb(),t=await this.mustThread(id),[u]=await db.update(customerSupportThreads).set({escalationLevel:0,escalatedAt:null,escalationReason:null,supervisorAdminUserId:null,updatedAt:new Date()}).where(eq(customerSupportThreads.id,id)).returning();await this.event(adminUserId,id,"escalation_cleared",null,null,{previousLevel:t.escalationLevel});return u}
 async updatePolicy(adminUserId:string,priority:string,input:any){if(!priorities.includes(priority as any))throw new Error("SUPPORT_PRIORITY_INVALID");const first=Math.max(5,Math.min(10080,Math.round(Number(input.firstResponseMinutes)))),resolution=Math.max(first,Math.min(43200,Math.round(Number(input.resolutionMinutes))));if(!first||!resolution)throw new Error("SUPPORT_SLA_POLICY_INVALID");const db=getDb(),existing=(await db.select().from(supportSlaPolicies).where(eq(supportSlaPolicies.priority,priority)).limit(1))[0],now=new Date();if(existing){const[u]=await db.update(supportSlaPolicies).set({firstResponseMinutes:first,resolutionMinutes:resolution,isActive:input.isActive!==false,updatedBy:adminUserId,updatedAt:now}).where(eq(supportSlaPolicies.priority,priority)).returning();await this.audit(adminUserId,"sla:"+priority,"sla_policy_updated",u);return u}const[u]=await db.insert(supportSlaPolicies).values({priority,firstResponseMinutes:first,resolutionMinutes:resolution,isActive:input.isActive!==false,updatedBy:adminUserId}).returning();return u}
 async reply(adminUserId:string,id:string,bodyInput:any){const body=clean(bodyInput);if(!body)throw new Error("SUPPORT_MESSAGE_REQUIRED");const db=getDb(),t=await this.mustThread(id),now=new Date(),m=(await db.insert(customerSupportMessages).values({threadId:id,senderRole:"admin",senderUserId:adminUserId,body,adminReadAt:now}).returning())[0];const first=t.firstRespondedAt||now;await db.update(customerSupportThreads).set({assignedAdminUserId:t.assignedAdminUserId||adminUserId,firstRespondedAt:first,lastMessageAt:now,updatedAt:now,status:t.status==="resolved"?"open":t.status,resolvedAt:t.status==="resolved"?null:t.resolvedAt}).where(eq(customerSupportThreads.id,id));await this.event(adminUserId,id,"admin_reply",t.assignedAdminUserId,t.assignedAdminUserId||adminUserId,{messageId:m.id});return m}
 async markRead(adminUserId:string,id:string){const db=getDb();await this.mustThread(id);const rows=await db.select().from(customerSupportMessages).where(eq(customerSupportMessages.threadId,id)),now=new Date();for(const m of rows.filter(x=>x.senderRole==="customer"&&!x.adminReadAt))await db.update(customerSupportMessages).set({adminReadAt:now}).where(eq(customerSupportMessages.id,m.id));return{read:true}}
 async performance(){const q=await this.queue("system"),agents=q.agents;return agents.map((a:any)=>{const owned=q.threads.filter((x:any)=>x.assignedAdminUserId===a.id),resolved=owned.filter((x:any)=>x.status==="resolved"),sat=resolved.map((x:any)=>x.satisfaction?.rating).filter((x:any):x is number=>typeof x==="number");return{agent:a,active:owned.filter((x:any)=>x.status!=="resolved").length,resolved:resolved.length,overdue:owned.filter((x:any)=>x.slaOverdue).length,avgFirstResponseMinutes:averageMinutes(resolved.map((x:any)=>mins(x.createdAt,x.firstRespondedAt))),avgResolutionMinutes:averageMinutes(resolved.map((x:any)=>mins(x.createdAt,x.resolvedAt))),satisfaction:sat.length?Number((sat.reduce((sum:number,value:number)=>sum+value,0)/sat.length).toFixed(2)):null}})}
 private async mustThread(id:string){const t=(await getDb().select().from(customerSupportThreads).where(eq(customerSupportThreads.id,id)).limit(1))[0];if(!t)throw new Error("SUPPORT_THREAD_NOT_FOUND");return t}
 private async mustAgent(id:string){const r=(await getDb().select().from(userRoles).where(and(eq(userRoles.userId,id),eq(userRoles.role,"admin"),eq(userRoles.isActive,true))).limit(1))[0];if(!r)throw new Error("SUPPORT_AGENT_INVALID")}
 private async event(actor:string,id:string,action:string,from:string|null,to:string|null,metadata:any){const db=getDb();await db.insert(supportThreadEvents).values({threadId:id,actorUserId:actor,action,fromAgentUserId:from,toAgentUserId:to,metadata});await this.audit(actor,id,action,metadata)}
 private async audit(userId:string,id:string,action:string,state:any){await getDb().insert(operationsAuditLogs).values({actorUserId:userId==="system"?null:userId,area:"customer_support_desk",action,targetType:"customer_support_thread",targetId:id,afterState:state,metadata:{supportOperationsOnly:true,noFinancialAuthority:true,noPartnerWorkflowChange:true}})}
}
export const adminSupportDeskService=new AdminSupportDeskService();
