import{and,eq,inArray}from"drizzle-orm";import{getDb}from"@/db";import{customerOperationTasks,customerServiceRecoveryCases,customerSupportThreads,modules,operationsAgentCapacity,operationsAuditLogs,serviceRequests,userRoles,users}from"@/db/schema";

const terminal=new Set(["resolved","completed","cancelled","rejected","closed"]);
const ms=(v:any)=>v?new Date(v).getTime():0;
const details=(x:any)=>(x?.details||{})as Record<string,any>;
function risk(due:any,status:string){if(!due||terminal.has(status))return"none";const left=ms(due)-Date.now();return left<=0?"overdue":left<=2*3600000?"critical":left<=24*3600000?"warning":"healthy"}
function dueOfRequest(x:any,kind:string){const d=details(x);if(kind==="housing")return d.housingAppointment?.scheduledAt||d.requestedViewingAt||null;if(kind==="travel"){if(d.travelAppointment?.scheduledAt)return d.travelAppointment.scheduledAt;return d.requestedDate?`${d.requestedDate}${d.requestedTime?`T${d.requestedTime}`:"T23:59:00"}`:null;}return null}
function kindOfRequest(x:any,moduleCode:string){const d=details(x),i=String(d.inquiryType||"");if(d.housingLead===true||i.includes("housing")||i==="rental_inquiry"||moduleCode.includes("housing"))return"housing";if(i.includes("travel")||moduleCode.includes("travel"))return"travel";return null}

export class AdminOperationsCommandCenterService{
 async agents(){const db=getDb(),roles=await db.select().from(userRoles).where(and(eq(userRoles.role,"admin"),eq(userRoles.isActive,true))),ids=[...new Set(roles.map(x=>x.userId))],people=ids.length?await db.select({id:users.id,nickname:users.nickname,email:users.email,phone:users.phone}).from(users).where(inArray(users.id,ids)):[],caps=ids.length?await db.select().from(operationsAgentCapacity).where(inArray(operationsAgentCapacity.adminUserId,ids)):[];return people.map(x=>{const c=caps.find(z=>z.adminUserId===x.id);return{id:x.id,name:x.nickname||x.email||x.phone||x.id,dailyCapacity:c?.dailyCapacity||20,warningLoadPercent:c?.warningLoadPercent||80,criticalLoadPercent:c?.criticalLoadPercent||100,isAvailable:c?.isAvailable??true,note:c?.note||null}})}

 async dashboard(){const db=getDb(),[support,tasks,recoveries,requests,moduleRows,agents]=await Promise.all([db.select().from(customerSupportThreads),db.select().from(customerOperationTasks),db.select().from(customerServiceRecoveryCases),db.select().from(serviceRequests),db.select().from(modules),this.agents()]);const mmap=new Map(moduleRows.map(x=>[x.id,x.code] as const)),items:any[]=[];
 for(const x of support){if(x.status==="resolved")continue;const due=!x.firstRespondedAt?x.firstResponseDueAt:x.resolutionDueAt;items.push({id:x.id,kind:"support",title:x.subject,status:x.status,priority:x.priority,assigneeId:x.assignedAdminUserId,dueAt:due,risk:risk(due,x.status),customerId:x.customerId,href:"support",createdAt:x.createdAt})}
 for(const x of tasks){if(terminal.has(x.status))continue;items.push({id:x.id,kind:"customer_task",title:x.title,status:x.status,priority:x.priority,assigneeId:x.assignedAdminUserId,dueAt:x.dueAt,risk:risk(x.dueAt,x.status),customerId:x.customerId,href:"customerOps",createdAt:x.createdAt})}
 for(const x of recoveries){if(terminal.has(x.status))continue;items.push({id:x.id,kind:"service_recovery",title:x.reason,status:x.status,priority:x.severity,assigneeId:x.assignedAdminUserId,dueAt:x.dueAt,risk:risk(x.dueAt,x.status),customerId:x.customerId,href:"customerOps",createdAt:x.createdAt})}
 for(const x of requests){const kind=kindOfRequest(x,String(mmap.get(x.moduleId)||""));if(!kind||terminal.has(String(x.status)))continue;const d=details(x),stage=kind==="housing"?String(d.housingLeadStage||x.status):String(d.travelBookingStage||x.status),due=dueOfRequest(x,kind);items.push({id:x.id,kind,title:x.title,status:stage,priority:x.priority>=2?"high":x.priority>=1?"normal":"low",assigneeId:null,dueAt:due,risk:risk(due,stage),customerId:x.customerId,href:kind,createdAt:x.createdAt,partnerAssignedUserId:x.assignedUserId})}
 const amap=new Map(agents.map(a=>[a.id,a] as const)),now=Date.now(),todayEnd=new Date();todayEnd.setHours(23,59,59,999);
 const enriched=items.map(x=>({...x,assignee:x.assigneeId?amap.get(x.assigneeId)||null:null})).sort((a,z)=>{const rank=(r:string)=>r==="overdue"?0:r==="critical"?1:r==="warning"?2:3;return rank(a.risk)-rank(z.risk)||(ms(a.dueAt)||Infinity)-(ms(z.dueAt)||Infinity)});
 const workload=agents.map(a=>{const mine=enriched.filter(x=>x.assigneeId===a.id),loadPercent=Math.round(mine.length/Math.max(1,a.dailyCapacity)*100);return{...a,active:mine.length,overdue:mine.filter(x=>x.risk==="overdue").length,due24h:mine.filter(x=>x.dueAt&&ms(x.dueAt)>now&&ms(x.dueAt)<=now+86400000).length,critical:mine.filter(x=>x.risk==="critical"||x.priority==="critical").length,loadPercent,loadState:loadPercent>=a.criticalLoadPercent?"critical":loadPercent>=a.warningLoadPercent?"warning":"healthy"}}).sort((a,z)=>z.loadPercent-a.loadPercent);
 const byKind=Object.fromEntries(["support","customer_task","service_recovery","housing","travel"].map(k=>[k,enriched.filter(x=>x.kind===k).length]));
 const summary={totalBacklog:enriched.length,overdue:enriched.filter(x=>x.risk==="overdue").length,due2h:enriched.filter(x=>x.risk==="critical").length,due24h:enriched.filter(x=>x.risk==="warning"||x.risk==="critical").length,unassigned:enriched.filter(x=>!x.assigneeId).length,criticalRecovery:enriched.filter(x=>x.kind==="service_recovery"&&x.priority==="critical").length,dueToday:enriched.filter(x=>x.dueAt&&ms(x.dueAt)>=now&&ms(x.dueAt)<=todayEnd.getTime()).length,overloadedAgents:workload.filter(x=>x.loadState==="critical").length};
 const forecast={next2Hours:enriched.filter(x=>x.risk==="critical").length,next24Hours:enriched.filter(x=>x.dueAt&&ms(x.dueAt)>now&&ms(x.dueAt)<=now+86400000).length,next72Hours:enriched.filter(x=>x.dueAt&&ms(x.dueAt)>now&&ms(x.dueAt)<=now+72*3600000).length,alreadyOverdue:summary.overdue,forecastRisk:summary.overdue>0||summary.overloadedAgents>0?"critical":summary.due2h>0?"high":summary.due24h>0?"watch":"healthy"};
 const bottlenecks=[...(summary.overdue?[{code:"OVERDUE_BACKLOG",severity:"critical",count:summary.overdue}]:[]),...(summary.unassigned?[{code:"UNASSIGNED_WORK",severity:"warning",count:summary.unassigned}]:[]),...(summary.overloadedAgents?[{code:"AGENT_CAPACITY",severity:"critical",count:summary.overloadedAgents}]:[]),...(summary.criticalRecovery?[{code:"CRITICAL_RECOVERY",severity:"critical",count:summary.criticalRecovery}]:[])];
 return{summary,forecast,byKind,workload,bottlenecks,items:enriched.slice(0,500),policy:{managementVisibilityOnly:true,automaticAssignment:false,automaticWorkflowMutation:false,automaticFinancialActions:false,partnerFundsAuthority:false}}}

 async setCapacity(actorId:string,adminUserId:string,input:any){const db=getDb(),dailyCapacity=Math.max(1,Math.min(500,Math.round(Number(input.dailyCapacity||20)))),warningLoadPercent=Math.max(1,Math.min(200,Math.round(Number(input.warningLoadPercent||80)))),criticalLoadPercent=Math.max(warningLoadPercent,Math.min(300,Math.round(Number(input.criticalLoadPercent||100)))),values={adminUserId,dailyCapacity,warningLoadPercent,criticalLoadPercent,isAvailable:input.isAvailable!==false,note:String(input.note||"").slice(0,1000)||null,updatedByAdminUserId:actorId,updatedAt:new Date()};const [row]=await db.insert(operationsAgentCapacity).values(values).onConflictDoUpdate({target:operationsAgentCapacity.adminUserId,set:values}).returning();await db.insert(operationsAuditLogs).values({actorUserId:actorId,area:"operations_command_center",action:"agent_capacity_updated",targetType:"admin_user",targetId:adminUserId,afterState:row,metadata:{planningOnly:true,automaticAssignment:false,automaticFinancialActions:false}});return row}
}
export const adminOperationsCommandCenterService=new AdminOperationsCommandCenterService();
