import {and,asc,desc,eq,gte,inArray} from "drizzle-orm";
import {getDb} from "@/db";
import {modules,operationsAuditLogs,organizations,serviceRequests,services,serviceTranslations} from "@/db/schema";

type PackageRow={id:string;name:string;pricingMode:string;adultPrice:number;childPrice:number;groupPrice:number;surchargePerBooking:number;minGuests:number;maxGuests:number;isEnabled:boolean;adminHidden?:boolean;adminVerified?:boolean;adminReviewNote?:string;adminReviewedAt?:string;adminReviewedBy?:string};
type ModerationAction="review"|"verify"|"unverify"|"hide"|"restore";
function m(row:any){return(row.metadata||{}) as Record<string,unknown>}
function d(row:any){return(row.details||{}) as Record<string,unknown>}
function clean(v:unknown,max=1000){return String(v||"").trim().slice(0,max)}
function num(v:unknown){const n=Number(v);return Number.isFinite(n)?n:0}
function rate(a:number,b:number){return a>0?Math.round(b/a*1000)/10:0}
function packageRows(meta:Record<string,unknown>):PackageRow[]{return Array.isArray(meta.travelPackages)?meta.travelPackages.filter(x=>x&&typeof x==="object").map((x:any)=>({id:String(x.id||""),name:String(x.name||"Package"),pricingMode:String(x.pricingMode||"per_person"),adultPrice:num(x.adultPrice),childPrice:num(x.childPrice),groupPrice:num(x.groupPrice),surchargePerBooking:num(x.surchargePerBooking),minGuests:Math.max(1,num(x.minGuests)||1),maxGuests:Math.max(1,num(x.maxGuests)||20),isEnabled:x.isEnabled!==false,adminHidden:x.adminHidden===true,adminVerified:x.adminVerified===true,adminReviewNote:String(x.adminReviewNote||""),adminReviewedAt:x.adminReviewedAt?String(x.adminReviewedAt):undefined,adminReviewedBy:x.adminReviewedBy?String(x.adminReviewedBy):undefined})):[]}
function quality(row:any){const x=m(row),issues:string[]=[];let score=100;const pkgs=packageRows(x),gallery=Array.isArray(x.galleryUrls)?x.galleryUrls.filter(Boolean):[];const bad=(c:string,n:number)=>{issues.push(c);score-=n};if(!row.name)bad("missing_name",20);if(!row.summary&&!row.description)bad("missing_description",10);if(!String(x.imageUrl||""))bad("missing_cover_image",15);if(gallery.length<3)bad("insufficient_gallery",8);if(!String(x.destination||""))bad("missing_destination",12);if(!String(x.experienceType||""))bad("missing_experience_type",8);if(!String(x.duration||""))bad("missing_duration",6);if(!String(x.departurePoint||""))bad("missing_departure_point",8);if(!Array.isArray(x.startTimes)&&!String(x.startTime||""))bad("missing_start_time",8);if(!pkgs.length)bad("missing_package",20);if(pkgs.some(p=>p.maxGuests<p.minGuests))bad("invalid_package_capacity",10);if(pkgs.some(p=>p.pricingMode==="group"?p.groupPrice<=0:p.adultPrice<=0))bad("invalid_package_price",15);return{score:Math.max(0,score),issues}}
function stage(row:any){const s=String(d(row).travelBookingStage||"requested");return["requested","confirmed","completed","cancelled","rejected"].includes(s)?s:"requested"}

export class AdminTravelOversightService{
 async overview(period:7|30|90=30,locale="zh-CN"){
  const db=getDb(),start=new Date(Date.now()-(period-1)*86400000);start.setUTCHours(0,0,0,0);
  const serviceRows=await db.select({id:services.id,code:services.code,organizationId:services.organizationId,isEnabled:services.isEnabled,priceFrom:services.priceFrom,currency:services.currency,metadata:services.metadata,createdAt:services.createdAt,updatedAt:services.updatedAt,organizationName:organizations.name,organizationCode:organizations.code,name:serviceTranslations.name,summary:serviceTranslations.summary,description:serviceTranslations.description}).from(services).innerJoin(modules,eq(services.moduleId,modules.id)).leftJoin(organizations,eq(services.organizationId,organizations.id)).leftJoin(serviceTranslations,and(eq(serviceTranslations.serviceId,services.id),eq(serviceTranslations.locale,locale))).where(eq(modules.code,"travel")).orderBy(asc(services.createdAt));
  const ids=serviceRows.map(x=>x.id);const requests=ids.length?await db.select().from(serviceRequests).where(and(inArray(serviceRequests.serviceId,ids),gte(serviceRequests.createdAt,start))).orderBy(desc(serviceRequests.createdAt)).limit(10000):[];
  const travel=requests.filter(x=>d(x).inquiryType==="travel_experience_inquiry"),summaryStage=Object.fromEntries(["requested","confirmed","completed","cancelled","rejected"].map(s=>[s,travel.filter(x=>stage(x)===s).length])) as Record<string,number>;
  const quoted=travel.reduce((a,x)=>a+num(d(x).quotedAmount),0),confirmedValue=travel.filter(x=>["confirmed","completed"].includes(stage(x))).reduce((a,x)=>a+num(d(x).quotedAmount),0),completedValue=travel.filter(x=>stage(x)==="completed").reduce((a,x)=>a+num(d(x).quotedAmount),0);
  const experiences=serviceRows.map(row=>{const q=quality(row),meta=m(row),pkgs=packageRows(meta),rs=travel.filter(x=>x.serviceId===row.id),f=Object.fromEntries(["requested","confirmed","completed","cancelled","rejected"].map(s=>[s,rs.filter(x=>stage(x)===s).length]));return{...row,qualityScore:q.score,qualityIssues:q.issues,moderationStatus:String(meta.travelModerationStatus||"unreviewed"),adminVerified:meta.travelAdminVerified===true,adminHidden:meta.travelAdminHidden===true,packages:pkgs,bookingCount:rs.length,funnel:f,quotedValue:rs.reduce((a,x)=>a+num(d(x).quotedAmount),0),completedValue:rs.filter(x=>stage(x)==="completed").reduce((a,x)=>a+num(d(x).quotedAmount),0)}});
  const orgIds=[...new Set(serviceRows.map(x=>x.organizationId).filter(Boolean))] as string[];
  const partners=orgIds.map(id=>{const es=experiences.filter(x=>x.organizationId===id),rs=travel.filter(x=>es.some(e=>e.id===x.serviceId)),q=rs.reduce((a,x)=>a+num(d(x).quotedAmount),0),cv=rs.filter(x=>["confirmed","completed"].includes(stage(x))).reduce((a,x)=>a+num(d(x).quotedAmount),0);return{organizationId:id,organizationName:es[0]?.organizationName||"",organizationCode:es[0]?.organizationCode||"",experiences:es.length,published:es.filter(x=>x.isEnabled).length,verified:es.filter(x=>x.adminVerified).length,packages:es.reduce((a,x)=>a+x.packages.length,0),bookings:rs.length,confirmed:rs.filter(x=>["confirmed","completed"].includes(stage(x))).length,completed:rs.filter(x=>stage(x)==="completed").length,quotedValue:q,confirmedValue:cv,conversionRate:rate(rs.length,rs.filter(x=>["confirmed","completed"].includes(stage(x))).length),completionRate:rate(rs.length,rs.filter(x=>stage(x)==="completed").length),averageQuality:es.length?Math.round(es.reduce((a,x)=>a+x.qualityScore,0)/es.length):0}});
  return{periodDays:period,summary:{experiences:experiences.length,published:experiences.filter(x=>x.isEnabled).length,verified:experiences.filter(x=>x.adminVerified).length,hidden:experiences.filter(x=>x.adminHidden).length,packages:experiences.reduce((a,x)=>a+x.packages.length,0),bookings:travel.length,...summaryStage,bookingConversionRate:rate(travel.length,summaryStage.confirmed+summaryStage.completed),completionRate:rate(travel.length,summaryStage.completed),quotedValue:quoted,confirmedValue,completedValue},partners,experiences:experiences.sort((a,b)=>b.bookingCount-a.bookingCount)};
 }
 async moderateExperience(adminUserId:string,id:string,input:{action?:unknown;note?:unknown}){
  const action=String(input.action||"review") as ModerationAction;if(!["review","verify","unverify","hide","restore"].includes(action))throw new Error("TRAVEL_MODERATION_ACTION_INVALID");const db=getDb(),row=(await db.select().from(services).where(eq(services.id,id)).limit(1))[0];if(!row)throw new Error("TRAVEL_EXPERIENCE_NOT_FOUND");const module=(await db.select().from(modules).where(eq(modules.id,row.moduleId)).limit(1))[0];if(module?.code!=="travel")throw new Error("TRAVEL_EXPERIENCE_NOT_FOUND");const before=m(row),now=new Date().toISOString(),note=clean(input.note),snapshot=(await this.overview(30,"zh-CN")).experiences.find(x=>x.id===id);let isEnabled=row.isEnabled;let next:Record<string,unknown>={...before,travelAdminReviewedAt:now,travelAdminReviewedBy:adminUserId,travelAdminReviewNote:note};
  if(action==="review")next={...next,travelModerationStatus:"reviewed"};if(action==="verify"){if(!snapshot||snapshot.qualityScore<80)throw new Error("TRAVEL_QUALITY_TOO_LOW_TO_VERIFY");if(before.travelAdminHidden===true)throw new Error("TRAVEL_EXPERIENCE_ADMIN_HIDDEN");next={...next,travelModerationStatus:"verified",travelAdminVerified:true,travelAdminVerifiedAt:now}}if(action==="unverify")next={...next,travelModerationStatus:"reviewed",travelAdminVerified:false,travelAdminVerifiedAt:null};if(action==="hide"){isEnabled=false;next={...next,travelModerationStatus:"hidden",travelAdminHidden:true,travelAdminHiddenAt:now,travelAdminVerified:false}}if(action==="restore"){isEnabled=true;next={...next,travelModerationStatus:"reviewed",travelAdminHidden:false,travelAdminHiddenAt:null,syncStatus:"published",syncedAt:now}}
  const[u]=await db.update(services).set({isEnabled,metadata:next,updatedAt:new Date()}).where(eq(services.id,id)).returning();await db.insert(operationsAuditLogs).values({actorUserId:adminUserId,area:"travel_moderation",action,targetType:"service",targetId:id,beforeState:{isEnabled:row.isEnabled,metadata:row.metadata},afterState:{isEnabled:u.isEnabled,metadata:u.metadata},metadata:{note}});return u;
 }
 async moderatePackage(adminUserId:string,id:string,packageId:string,input:{action?:unknown;note?:unknown}){
  const action=String(input.action||"review") as ModerationAction;if(!["review","verify","unverify","hide","restore"].includes(action))throw new Error("TRAVEL_PACKAGE_MODERATION_ACTION_INVALID");const db=getDb(),row=(await db.select().from(services).where(eq(services.id,id)).limit(1))[0];if(!row)throw new Error("TRAVEL_EXPERIENCE_NOT_FOUND");const module=(await db.select().from(modules).where(eq(modules.id,row.moduleId)).limit(1))[0];if(module?.code!=="travel")throw new Error("TRAVEL_EXPERIENCE_NOT_FOUND");const meta=m(row),pkgs=packageRows(meta),idx=pkgs.findIndex(x=>x.id===packageId);if(idx<0)throw new Error("TRAVEL_PACKAGE_NOT_FOUND");const now=new Date().toISOString(),note=clean(input.note),p={...pkgs[idx],adminReviewedAt:now,adminReviewedBy:adminUserId,adminReviewNote:note};
  if(action==="review")Object.assign(p,{adminVerified:false});if(action==="verify"){if((p.pricingMode==="group"?p.groupPrice:p.adultPrice)<=0||p.maxGuests<p.minGuests)throw new Error("TRAVEL_PACKAGE_QUALITY_INVALID");if(p.adminHidden)throw new Error("TRAVEL_PACKAGE_ADMIN_HIDDEN");Object.assign(p,{adminVerified:true})}if(action==="unverify")Object.assign(p,{adminVerified:false});if(action==="hide")Object.assign(p,{adminHidden:true,adminVerified:false,isEnabled:false});if(action==="restore")Object.assign(p,{adminHidden:false,isEnabled:true});pkgs[idx]=p;
  const[u]=await db.update(services).set({metadata:{...meta,travelPackages:pkgs,travelInventoryUpdatedAt:now},updatedAt:new Date()}).where(eq(services.id,id)).returning();await db.insert(operationsAuditLogs).values({actorUserId:adminUserId,area:"travel_package_moderation",action,targetType:"travel_package",targetId:packageId,beforeState:packageRows(meta)[idx],afterState:p,metadata:{serviceId:id,note}});return u;
 }
}
export const adminTravelOversightService=new AdminTravelOversightService();
