import{and,desc,eq,inArray}from"drizzle-orm";import{getDb}from"@/db";import{customerNotificationPreferences,customerNotificationReceipts,customerSavedSearchAlertEvents,customerSavedSearches,moduleTranslations,modules,serviceRequests,serviceRequestStatusHistory,services,serviceTranslations}from"@/db/schema";
type Category="order"|"housing"|"travel"|"payment"|"saved_search";
function category(note:string,moduleCode:string):Category{if(note.startsWith("PAYMENT_")||note.startsWith("TRAVEL_PARTNER_PAYMENT_"))return"payment";if(note.startsWith("HOUSING_")||moduleCode==="housing")return"housing";if(note.startsWith("TRAVEL_")||moduleCode==="travel")return"travel";return"order"}
function href(c:Category,requestId?:string,searchHref?:string){return c==="housing"?"/housing/requests":c==="travel"||c==="payment"?"/travel/requests":c==="saved_search"?(searchHref||"/search"):`/order/${requestId}`}
function enabled(p:any,c:Category){return c==="order"?p.orderEnabled:c==="housing"?p.housingEnabled:c==="travel"?p.travelEnabled:c==="payment"?p.paymentEnabled:p.savedSearchEnabled}
export class CustomerNotificationCenterService{
 async preferences(userId:string){const db=getDb(),row=(await db.select().from(customerNotificationPreferences).where(eq(customerNotificationPreferences.userId,userId)).limit(1))[0];if(row)return row;return(await db.insert(customerNotificationPreferences).values({userId}).returning())[0]}
 async updatePreferences(userId:string,input:any){const db=getDb(),p=await this.preferences(userId),next={orderEnabled:input.orderEnabled===undefined?p.orderEnabled:input.orderEnabled===true,housingEnabled:input.housingEnabled===undefined?p.housingEnabled:input.housingEnabled===true,travelEnabled:input.travelEnabled===undefined?p.travelEnabled:input.travelEnabled===true,paymentEnabled:input.paymentEnabled===undefined?p.paymentEnabled:input.paymentEnabled===true,savedSearchEnabled:input.savedSearchEnabled===undefined?p.savedSearchEnabled:input.savedSearchEnabled===true,updatedAt:new Date()};return(await db.update(customerNotificationPreferences).set(next).where(eq(customerNotificationPreferences.userId,userId)).returning())[0]}
 async inbox(userId:string,locale="vi-VN",filter="all"){const db=getDb(),prefs=await this.preferences(userId),requests=await db.select().from(serviceRequests).where(eq(serviceRequests.customerId,userId));const requestIds=requests.map(x=>x.id),hist=requestIds.length?await db.select().from(serviceRequestStatusHistory).where(inArray(serviceRequestStatusHistory.requestId,requestIds)).orderBy(desc(serviceRequestStatusHistory.createdAt)).limit(150):[],mods=await db.select().from(modules),mtr=await db.select().from(moduleTranslations),sv=await db.select().from(services),str=await db.select().from(serviceTranslations),saved=await db.select().from(customerSavedSearches).where(eq(customerSavedSearches.userId,userId)),searchEvents=await db.select().from(customerSavedSearchAlertEvents).where(and(eq(customerSavedSearchAlertEvents.userId,userId),eq(customerSavedSearchAlertEvents.isBaseline,false))).orderBy(desc(customerSavedSearchAlertEvents.createdAt)).limit(80),receipts=await db.select().from(customerNotificationReceipts).where(eq(customerNotificationReceipts.userId,userId)),receiptMap=new Map<string,any>(receipts.map(x=>[`${x.sourceType}:${x.sourceId}`,x] as [string,any]));
 const items:any[]=[];
 for(const h of hist){const r=requests.find(x=>x.id===h.requestId);if(!r)continue;const mod=mods.find(x=>x.id===r.moduleId),c=category(String(h.note||""),String(mod?.code||"")),sourceType="request_history",sourceId=h.id,receipt=receiptMap.get(`${sourceType}:${sourceId}`),service=sv.find(x=>x.id===r.serviceId),name=str.find(x=>x.serviceId===r.serviceId&&x.locale===locale)||str.find(x=>x.serviceId===r.serviceId),mn=mtr.find(x=>x.moduleId===r.moduleId&&x.locale===locale)||mtr.find(x=>x.moduleId===r.moduleId);items.push({id:`${sourceType}:${sourceId}`,sourceType,sourceId,category:c,eventCode:String(h.note||"")||`STATUS:${h.toStatus}`,status:h.toStatus,title:name?.name||r.title||mn?.name||r.requestCode,subtitle:r.requestCode,href:href(c,r.id),readAt:receipt?.readAt||null,dismissedAt:receipt?.dismissedAt||null,createdAt:h.createdAt})}
 for(const e of searchEvents){const s=saved.find(x=>x.id===e.savedSearchId);if(!s||!s.watchEnabled)continue;const sourceType="saved_search",sourceId=e.id,receipt=receiptMap.get(`${sourceType}:${sourceId}`),service=sv.find(x=>x.id===e.serviceId),name=str.find(x=>x.serviceId===e.serviceId&&x.locale===locale)||str.find(x=>x.serviceId===e.serviceId),u=new URLSearchParams();if(s.query)u.set("q",s.query);if(s.moduleCode)u.set("module",s.moduleCode);items.push({id:`${sourceType}:${sourceId}`,sourceType,sourceId,category:"saved_search"as Category,eventCode:e.eventType,title:s.label,subtitle:name?.name||service?.code||"",href:`/search?${u.toString()}`,readAt:receipt?.readAt||e.readAt||null,dismissedAt:receipt?.dismissedAt||null,createdAt:e.createdAt})}
 const visible=items.filter(x=>!x.dismissedAt&&enabled(prefs,x.category)&&(filter==="all"||x.category===filter)).sort((a,b)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime()).slice(0,200);return{items:visible,preferences:prefs,summary:{unread:visible.filter(x=>!x.readAt).length,total:visible.length,byCategory:{order:visible.filter(x=>x.category==="order").length,housing:visible.filter(x=>x.category==="housing").length,travel:visible.filter(x=>x.category==="travel").length,payment:visible.filter(x=>x.category==="payment").length,saved_search:visible.filter(x=>x.category==="saved_search").length}},policy:{customerControlled:true,preferencesOnlyAffectCustomerAlerts:true,noPartnerWorkflowChange:true}}}
 async receipt(userId:string,sourceType:string,sourceId:string,input:any){const db=getDb(),existing=(await db.select().from(customerNotificationReceipts).where(and(eq(customerNotificationReceipts.userId,userId),eq(customerNotificationReceipts.sourceType,sourceType),eq(customerNotificationReceipts.sourceId,sourceId))).limit(1))[0],now=new Date(),values={readAt:input.read===true?now:existing?.readAt||null,dismissedAt:input.dismissed===true?now:existing?.dismissedAt||null,updatedAt:now};if(existing)return(await db.update(customerNotificationReceipts).set(values).where(eq(customerNotificationReceipts.id,existing.id)).returning())[0];return(await db.insert(customerNotificationReceipts).values({userId,sourceType,sourceId,...values}).returning())[0]}
 async markAllRead(userId:string,locale="vi-VN"){const box=await this.inbox(userId,locale,"all");for(const x of box.items.filter((i:any)=>!i.readAt))await this.receipt(userId,x.sourceType,x.sourceId,{read:true});return{updated:box.items.filter((i:any)=>!i.readAt).length}}
}
export const customerNotificationCenterService=new CustomerNotificationCenterService();
