import {and,desc,eq,isNull,or,gte,lte} from "drizzle-orm";import {getDb} from "@/db";import {customerFavorites,customerBrowsingHistory,customerCoupons,customerCouponClaims,services,serviceTranslations} from "@/db/schema";
export class CustomerPersonalizationService{
 async favorites(userId:string,locale:string){const db=getDb();return db.select({id:services.id,code:services.code,moduleId:services.moduleId,priceFrom:services.priceFrom,currency:services.currency,metadata:services.metadata,name:serviceTranslations.name,summary:serviceTranslations.summary,createdAt:customerFavorites.createdAt}).from(customerFavorites).innerJoin(services,eq(customerFavorites.serviceId,services.id)).leftJoin(serviceTranslations,and(eq(serviceTranslations.serviceId,services.id),eq(serviceTranslations.locale,locale))).where(eq(customerFavorites.userId,userId)).orderBy(desc(customerFavorites.createdAt))}
 async isFavorite(userId:string,serviceId:string){return Boolean((await getDb().select().from(customerFavorites).where(and(eq(customerFavorites.userId,userId),eq(customerFavorites.serviceId,serviceId))).limit(1))[0])}
 async setFavorite(userId:string,serviceId:string,on:boolean){const db=getDb();if(on)await db.insert(customerFavorites).values({userId,serviceId}).onConflictDoNothing();else await db.delete(customerFavorites).where(and(eq(customerFavorites.userId,userId),eq(customerFavorites.serviceId,serviceId)));return{serviceId,favorite:on}}
 async recordView(userId:string,serviceId:string){await getDb().insert(customerBrowsingHistory).values({userId,serviceId});return{serviceId}}
 async history(userId:string,locale:string){const db=getDb();return db.select({id:services.id,code:services.code,moduleId:services.moduleId,priceFrom:services.priceFrom,currency:services.currency,metadata:services.metadata,name:serviceTranslations.name,summary:serviceTranslations.summary,viewedAt:customerBrowsingHistory.viewedAt}).from(customerBrowsingHistory).innerJoin(services,eq(customerBrowsingHistory.serviceId,services.id)).leftJoin(serviceTranslations,and(eq(serviceTranslations.serviceId,services.id),eq(serviceTranslations.locale,locale))).where(eq(customerBrowsingHistory.userId,userId)).orderBy(desc(customerBrowsingHistory.viewedAt)).limit(50)}
 async coupons(userId:string,locale:string){const now=new Date(),db=getDb();const rows=await db.select({id:customerCoupons.id,code:customerCoupons.code,title:customerCoupons.title,description:customerCoupons.description,discountType:customerCoupons.discountType,discountValue:customerCoupons.discountValue,minSpend:customerCoupons.minSpend,currency:customerCoupons.currency,expiresAt:customerCoupons.expiresAt,claimedAt:customerCouponClaims.claimedAt,usedAt:customerCouponClaims.usedAt}).from(customerCoupons).leftJoin(customerCouponClaims,and(eq(customerCouponClaims.couponId,customerCoupons.id),eq(customerCouponClaims.userId,userId))).where(and(eq(customerCoupons.isActive,true),or(isNull(customerCoupons.startsAt),lte(customerCoupons.startsAt,now)),or(isNull(customerCoupons.expiresAt),gte(customerCoupons.expiresAt,now))));return rows.map(x=>({...x,title:(x.title as any)?.[locale]||(x.title as any)?.["zh-CN"]||x.code,description:(x.description as any)?.[locale]||(x.description as any)?.["zh-CN"]||""}))}
 async claim(userId:string,couponId:string){await getDb().insert(customerCouponClaims).values({userId,couponId}).onConflictDoNothing();return{couponId,claimed:true}}
}export const customerPersonalizationService=new CustomerPersonalizationService();
