import{and,desc,eq}from"drizzle-orm";import{getDb}from"@/db";import{customerBrowsingHistory,customerFavorites,services}from"@/db/schema";import{unifiedServiceDiscoveryService}from"@/lib/services/unified-service-discovery-service";
function uniq<T>(xs:T[],key:(x:T)=>string){const seen=new Set<string>();return xs.filter(x=>{const k=key(x);if(seen.has(k))return false;seen.add(k);return true})}
export class CustomerPersonalizedDiscoveryService{
 async favoriteIds(userId:string){const rows=await getDb().select().from(customerFavorites).where(eq(customerFavorites.userId,userId));return rows.map(x=>x.serviceId)}
 async isFavorite(userId:string,serviceId:string){const row=(await getDb().select().from(customerFavorites).where(and(eq(customerFavorites.userId,userId),eq(customerFavorites.serviceId,serviceId))).limit(1))[0];return{serviceId,favorite:Boolean(row)}}
 async toggleFavorite(userId:string,serviceId:string,favorite?:boolean){const db=getDb(),service=(await db.select().from(services).where(eq(services.id,serviceId)).limit(1))[0];if(!service||!service.isEnabled)throw new Error("SERVICE_NOT_FOUND");const row=(await db.select().from(customerFavorites).where(and(eq(customerFavorites.userId,userId),eq(customerFavorites.serviceId,serviceId))).limit(1))[0],target=favorite===undefined?!row:favorite;if(target&&!row)await db.insert(customerFavorites).values({userId,serviceId});if(!target&&row)await db.delete(customerFavorites).where(and(eq(customerFavorites.userId,userId),eq(customerFavorites.serviceId,serviceId)));return{serviceId,favorite:target}}
 async recordView(userId:string,serviceId:string){const db=getDb(),service=(await db.select().from(services).where(eq(services.id,serviceId)).limit(1))[0];if(!service||!service.isEnabled)return{recorded:false};await db.insert(customerBrowsingHistory).values({userId,serviceId});return{recorded:true,serviceId}}
 async clearHistory(userId:string){await getDb().delete(customerBrowsingHistory).where(eq(customerBrowsingHistory.userId,userId));return{cleared:true}}
 async hub(userId:string,locale="vi-VN"){const db=getDb(),[fav,hist,all]=await Promise.all([db.select().from(customerFavorites).where(eq(customerFavorites.userId,userId)),db.select().from(customerBrowsingHistory).where(eq(customerBrowsingHistory.userId,userId)).orderBy(desc(customerBrowsingHistory.viewedAt)).limit(120),unifiedServiceDiscoveryService.search({locale,limit:100})]);const byId=new Map<string,any>((all.services as any[]).map((x:any)=>[x.id,x] as [string,any])),favorites=fav.map(x=>byId.get(x.serviceId)).filter(Boolean),mappedViews:any[]=hist.map(x=>({item:byId.get(x.serviceId),viewedAt:x.viewedAt})).filter((x:any)=>Boolean(x.item)),recentlyViewed=uniq<any>(mappedViews,(x:any)=>String(x.item.id)).slice(0,24);const affinity=new Map<string,number>();for(const x of favorites as any[])affinity.set(x.moduleCode,(affinity.get(x.moduleCode)||0)+4);for(const x of recentlyViewed as any[])affinity.set((x.item as any).moduleCode,(affinity.get((x.item as any).moduleCode)||0)+1);const excluded=new Set([...fav.map(x=>x.serviceId),...(recentlyViewed as any[]).map((x:any)=>x.item.id)]),forYou=(all.services as any[]).filter(x=>!excluded.has(x.id)).map(x=>({...x,personalScore:affinity.get(x.moduleCode)||0})).sort((a,b)=>b.personalScore-a.personalScore||b.verifiedBadgeCount-a.verifiedBadgeCount||a.name.localeCompare(b.name)).slice(0,24);const continueViewing=(recentlyViewed as any[]).slice(0,8);return{favorites,recentlyViewed,continueViewing,forYou,preferenceSummary:[...affinity.entries()].sort((a,b)=>b[1]-a[1]).map(([moduleCode,weight])=>({moduleCode,weight})),privacy:{firstPartyActivityOnly:true,noSensitiveProfiling:true,noExternalTracking:true,noCrossAccountSharing:true,customerCanClearHistory:true},ranking:{favoriteWeight:4,recentViewWeight:1,paidPlacement:false,trustScoreBoost:false}}}
}
export const customerPersonalizedDiscoveryService=new CustomerPersonalizedDiscoveryService();
