import{and,desc,eq}from"drizzle-orm";import{getDb}from"@/db";import{customerSavedSearches}from"@/db/schema";
function clean(v:any,n:number){return String(v||"").trim().slice(0,n)}
function filters(v:any){if(!v||typeof v!=="object"||Array.isArray(v))return{};const out:Record<string,unknown>={};for(const[k,val]of Object.entries(v).slice(0,30)){if(["string","number","boolean"].includes(typeof val)||val===null)out[String(k).slice(0,80)]=val}return out}
function href(x:any){const u=new URLSearchParams();if(x.query)u.set("q",x.query);if(x.moduleCode)u.set("module",x.moduleCode);for(const[k,v]of Object.entries(x.filters||{})){if(v!==undefined&&v!==null&&String(v)!=="")u.set(k,String(v))}return`/search?${u.toString()}`}
export class CustomerIntentMemoryService{
 async list(userId:string){const rows=await getDb().select().from(customerSavedSearches).where(eq(customerSavedSearches.userId,userId)).orderBy(desc(customerSavedSearches.isPinned),desc(customerSavedSearches.lastUsedAt),desc(customerSavedSearches.updatedAt));return rows.map(x=>({...x,shortcutHref:href(x)}))}
 async create(userId:string,input:any){const db=getDb(),label=clean(input.label,120),query=clean(input.query,500),moduleCode=clean(input.moduleCode,40)||null,fs=filters(input.filters);if(!label)throw new Error("SAVED_SEARCH_LABEL_REQUIRED");const row=(await db.insert(customerSavedSearches).values({userId,label,query,moduleCode,filters:fs,isPinned:input.isPinned===true}).returning())[0];return{...row,shortcutHref:href(row)}}
 async update(userId:string,id:string,input:any){const db=getDb(),row=(await db.select().from(customerSavedSearches).where(and(eq(customerSavedSearches.id,id),eq(customerSavedSearches.userId,userId))).limit(1))[0];if(!row)throw new Error("SAVED_SEARCH_NOT_FOUND");const next={label:input.label!==undefined?clean(input.label,120):row.label,query:input.query!==undefined?clean(input.query,500):row.query,moduleCode:input.moduleCode!==undefined?(clean(input.moduleCode,40)||null):row.moduleCode,filters:input.filters!==undefined?filters(input.filters):row.filters,isPinned:input.isPinned!==undefined?input.isPinned===true:row.isPinned,updatedAt:new Date()};if(!next.label)throw new Error("SAVED_SEARCH_LABEL_REQUIRED");const saved=(await db.update(customerSavedSearches).set(next).where(and(eq(customerSavedSearches.id,id),eq(customerSavedSearches.userId,userId))).returning())[0];return{...saved,shortcutHref:href(saved)}}
 async remove(userId:string,id:string){await getDb().delete(customerSavedSearches).where(and(eq(customerSavedSearches.id,id),eq(customerSavedSearches.userId,userId)));return{deleted:true,id}}
 async use(userId:string,id:string){const db=getDb(),row=(await db.update(customerSavedSearches).set({lastUsedAt:new Date(),updatedAt:new Date()}).where(and(eq(customerSavedSearches.id,id),eq(customerSavedSearches.userId,userId))).returning())[0];if(!row)throw new Error("SAVED_SEARCH_NOT_FOUND");return{...row,shortcutHref:href(row)}}
 async shortcuts(userId:string){const rows=await this.list(userId),pinned=rows.filter(x=>x.isPinned),recent=rows.filter(x=>!x.isPinned).slice(0,6);return{pinned:pinned.slice(0,8),recent,all:rows.slice(0,20),policy:{customerManaged:true,noAutomaticIntentCreation:true,noSensitiveProfiling:true,noExternalTracking:true}}}
}
export const customerIntentMemoryService=new CustomerIntentMemoryService();
