import{and,desc,eq,inArray}from"drizzle-orm";import{getDb}from"@/db";import{customerSupportMessages,customerSupportThreads,modules,organizations,serviceRequests,serviceTranslations,services,supportSlaPolicies}from"@/db/schema";import{housingMessagingService}from"@/lib/services/housing-messaging-service";import{travelMessagingService}from"@/lib/services/travel-messaging-service";import{paymentSupportService}from"@/lib/services/payment-support-service";
function d(x:any){return(x?.details||{})as Record<string,any>}function clean(v:any,n=2000){return String(v||"").trim().slice(0,n)}function msgTime(m:any){return new Date(m.createdAt||0).getTime()}
function route(kind:string,id:string){return kind==="housing"?`/housing/requests`:kind==="travel"||kind==="payment"?`/travel/requests`:`/messages?thread=support:${id}`}
export class CustomerMessageCenterService{
 async inbox(userId:string,locale="vi-VN"){const db=getDb(),requests=await db.select().from(serviceRequests).where(eq(serviceRequests.customerId,userId)),serviceIds=requests.map(x=>x.serviceId).filter(Boolean)as string[],sv=serviceIds.length?await db.select().from(services).where(inArray(services.id,serviceIds)):[],tr=serviceIds.length?await db.select().from(serviceTranslations).where(inArray(serviceTranslations.serviceId,serviceIds)):[],mods=await db.select().from(modules),orgs=await db.select().from(organizations),support=await db.select().from(customerSupportThreads).where(eq(customerSupportThreads.customerId,userId)).orderBy(desc(customerSupportThreads.lastMessageAt));
 const threads:any[]=[];
 for(const r of requests){const x=d(r),service=sv.find(s=>s.id===r.serviceId),name=tr.find(t=>t.serviceId===r.serviceId&&t.locale===locale)||tr.find(t=>t.serviceId===r.serviceId),org=orgs.find(o=>o.id===r.assignedOrganizationId),mod=mods.find(m=>m.id===r.moduleId);
  const housing=Array.isArray(x.housingMessages)?x.housingMessages:[],travel=Array.isArray(x.travelMessages)?x.travelMessages:[],payment=Array.isArray(x.paymentSupportTicket?.messages)?x.paymentSupportTicket.messages:[];
  for(const[kind,messages]of [["housing",housing],["travel",travel],["payment",payment]]as const){if(!messages.length)continue;const last=messages.slice().sort((a:any,b:any)=>msgTime(b)-msgTime(a))[0],unread=messages.filter((m:any)=>kind==="payment"?m.sender==="partner"&&!m.customerReadAt:m.senderRole==="partner"&&!m.customerReadAt).length;threads.push({id:`${kind}:${r.id}`,kind,requestId:r.id,title:name?.name||r.title||r.requestCode,subtitle:org?.name||mod?.code||"",lastMessage:last.body||"",lastMessageAt:last.createdAt,unreadCount:unread,href:route(kind,r.id),status:r.status})}}
 const supportIds=support.map(x=>x.id),sm=supportIds.length?await db.select().from(customerSupportMessages).where(inArray(customerSupportMessages.threadId,supportIds)):[];for(const s of support){const messages=sm.filter(m=>m.threadId===s.id),last=messages.slice().sort((a,b)=>msgTime(b)-msgTime(a))[0];threads.push({id:`support:${s.id}`,kind:"support",supportThreadId:s.id,title:s.subject,subtitle:"ZhaoXi Support",lastMessage:last?.body||"",lastMessageAt:last?.createdAt||s.lastMessageAt,unreadCount:messages.filter(m=>m.senderRole!=="customer"&&!m.customerReadAt).length,href:`/messages?thread=support:${s.id}`,status:s.status})}
 return{threads:threads.sort((a,b)=>msgTime(b)-msgTime(a)),summary:{total:threads.length,unread:threads.reduce((n,x)=>n+x.unreadCount,0),housing:threads.filter(x=>x.kind==="housing").length,travel:threads.filter(x=>x.kind==="travel").length,payment:threads.filter(x=>x.kind==="payment").length,support:threads.filter(x=>x.kind==="support").length}}}
 async thread(userId:string,threadId:string){const[kind,id]=threadId.split(":");const db=getDb();if(kind==="support"){const t=(await db.select().from(customerSupportThreads).where(and(eq(customerSupportThreads.id,id),eq(customerSupportThreads.customerId,userId))).limit(1))[0];if(!t)throw new Error("MESSAGE_THREAD_NOT_FOUND");const messages=await db.select().from(customerSupportMessages).where(eq(customerSupportMessages.threadId,id));return{thread:{id:threadId,kind,title:t.subject,status:t.status},messages:messages.map(m=>({id:m.id,senderRole:m.senderRole,body:m.body,createdAt:m.createdAt,customerReadAt:m.customerReadAt}))}}
 const r=(await db.select().from(serviceRequests).where(and(eq(serviceRequests.id,id),eq(serviceRequests.customerId,userId))).limit(1))[0];if(!r)throw new Error("MESSAGE_THREAD_NOT_FOUND");const x=d(r);if(kind==="housing")return{thread:{id:threadId,kind,title:r.title,status:r.status},messages:(Array.isArray(x.housingMessages)?x.housingMessages:[])};if(kind==="travel")return{thread:{id:threadId,kind,title:r.title,status:r.status},messages:(Array.isArray(x.travelMessages)?x.travelMessages:[])};if(kind==="payment")return{thread:{id:threadId,kind,title:"Payment Support",status:x.paymentSupportTicket?.stage||"open"},messages:(Array.isArray(x.paymentSupportTicket?.messages)?x.paymentSupportTicket.messages:[]).map((m:any)=>({...m,senderRole:m.sender}))};throw new Error("MESSAGE_THREAD_NOT_FOUND")}
 async send(userId:string,threadId:string,bodyInput:any){const body=clean(bodyInput);if(!body)throw new Error("MESSAGE_REQUIRED");const[kind,id]=threadId.split(":");if(kind==="housing")return housingMessagingService.customerSend(userId,id,body);if(kind==="travel")return travelMessagingService.customerSend(userId,id,body);if(kind==="payment")return paymentSupportService.customerMessage(userId,id,body);if(kind==="support"){const db=getDb(),t=(await db.select().from(customerSupportThreads).where(and(eq(customerSupportThreads.id,id),eq(customerSupportThreads.customerId,userId))).limit(1))[0];if(!t)throw new Error("MESSAGE_THREAD_NOT_FOUND");const now=new Date(),m=(await db.insert(customerSupportMessages).values({threadId:id,senderRole:"customer",senderUserId:userId,body,customerReadAt:now}).returning())[0];await db.update(customerSupportThreads).set({lastMessageAt:now,updatedAt:now,status:t.status==="closed"?"open":t.status}).where(eq(customerSupportThreads.id,id));return m}throw new Error("MESSAGE_THREAD_NOT_FOUND")}
 async markRead(userId:string,threadId:string){const[kind,id]=threadId.split(":");if(kind==="housing")return housingMessagingService.customerRead(userId,id);if(kind==="travel")return travelMessagingService.customerRead(userId,id);if(kind==="payment")return paymentSupportService.markRead(userId,"customer",undefined,id);if(kind==="support"){const db=getDb(),t=(await db.select().from(customerSupportThreads).where(and(eq(customerSupportThreads.id,id),eq(customerSupportThreads.customerId,userId))).limit(1))[0];if(!t)throw new Error("MESSAGE_THREAD_NOT_FOUND");const now=new Date(),messages=await db.select().from(customerSupportMessages).where(eq(customerSupportMessages.threadId,id));for(const m of messages.filter(m=>m.senderRole!=="customer"&&!m.customerReadAt))await db.update(customerSupportMessages).set({customerReadAt:now}).where(eq(customerSupportMessages.id,m.id));return{read:true}}throw new Error("MESSAGE_THREAD_NOT_FOUND")}
 async createSupport(userId:string,input:any){const subject=clean(input.subject,180),body=clean(input.message);if(!subject||!body)throw new Error("SUPPORT_THREAD_FIELDS_REQUIRED");const db=getDb(),now=new Date(),policy=(await db.select().from(supportSlaPolicies).where(eq(supportSlaPolicies.priority,"normal")).limit(1))[0],firstMinutes=policy?.firstResponseMinutes||240,resolutionMinutes=policy?.resolutionMinutes||1440,t=(await db.insert(customerSupportThreads).values({customerId:userId,subject,priority:"normal",lastMessageAt:now,firstResponseDueAt:new Date(now.getTime()+firstMinutes*60000),resolutionDueAt:new Date(now.getTime()+resolutionMinutes*60000)}).returning())[0];await db.insert(customerSupportMessages).values({threadId:t.id,senderRole:"customer",senderUserId:userId,body,customerReadAt:now});return{id:`support:${t.id}`,thread:t}}
}
export const customerMessageCenterService=new CustomerMessageCenterService();
