import {and,asc,desc,eq,inArray} from "drizzle-orm";
import {getDb} from "@/db";
import {deliveryJobEvents,deliveryJobs,driverLocationHistory,driverLocations,driverProfiles,organizations,serviceRequests,serviceRequestStatusHistory,users} from "@/db/schema";

export type DriverAvailability="offline"|"available"|"busy"|"suspended";
export type DeliveryJobStatus="searching_driver"|"assigned"|"picked_up"|"delivering"|"delivered"|"cancelled";
const transitions:Record<DeliveryJobStatus,DeliveryJobStatus[]>={searching_driver:["assigned","cancelled"],assigned:["picked_up","cancelled"],picked_up:["delivering","cancelled"],delivering:["delivered","cancelled"],delivered:[],cancelled:[]};

function n(value:unknown){const x=Number(value);return Number.isFinite(x)?x:undefined}
function radians(value:number){return value*Math.PI/180}
function distanceKm(a:{latitude:number;longitude:number},b:{latitude:number;longitude:number}){const earth=6371;const dLat=radians(b.latitude-a.latitude),dLon=radians(b.longitude-a.longitude);const x=Math.sin(dLat/2)**2+Math.cos(radians(a.latitude))*Math.cos(radians(b.latitude))*Math.sin(dLon/2)**2;return earth*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function estimateEtaMinutes(distance:number,speedMps?:number){if(distance<=0.03)return 1;const effective=speedMps&&speedMps>1.5?Math.min(speedMps,18):6.94;return Math.max(1,Math.ceil((distance*1000/effective)/60))}
function point(lat:unknown,lng:unknown){const latitude=n(lat),longitude=n(lng);return latitude!==undefined&&longitude!==undefined?{latitude,longitude}:null}

export class DriverService{
 async profileForUser(userId:string){const db=getDb();return(await db.select().from(driverProfiles).where(eq(driverProfiles.userId,userId)).limit(1))[0]||null}
 async ensureProfile(userId:string){const db=getDb();const current=await this.profileForUser(userId);if(current)return current;const user=(await db.select().from(users).where(eq(users.id,userId)).limit(1))[0];const[row]=await db.insert(driverProfiles).values({userId,phone:user?.phone||undefined,status:"offline"}).returning();return row}
 async updateProfile(userId:string,input:{status?:DriverAvailability;phone?:string;vehicleType?:string;plateNumber?:string}){const db=getDb();const current=await this.ensureProfile(userId);if(input.status==="available"){const active=(await db.select().from(deliveryJobs).where(and(eq(deliveryJobs.driverId,current.id),inArray(deliveryJobs.status,["assigned","picked_up","delivering"]))).limit(1))[0];if(active)throw new Error("DRIVER_HAS_ACTIVE_JOB")}const[row]=await db.update(driverProfiles).set({status:input.status??current.status,phone:input.phone??current.phone,vehicleType:input.vehicleType??current.vehicleType,plateNumber:input.plateNumber??current.plateNumber,updatedAt:new Date()}).where(eq(driverProfiles.id,current.id)).returning();return row}
 async event(jobId:string,eventType:string,input:{driverId?:string|null;fromStatus?:string|null;toStatus?:string|null;metadata?:Record<string,unknown>}={}){const[row]=await getDb().insert(deliveryJobEvents).values({jobId,driverId:input.driverId||undefined,eventType,fromStatus:input.fromStatus||undefined,toStatus:input.toStatus||undefined,metadata:input.metadata||{}}).returning();return row}
 async ensureReadyJobs(){const db=getDb();const rows=await db.select().from(serviceRequests).where(eq(serviceRequests.status,"completed"));for(const row of rows){const details=(row.details||{}) as Record<string,unknown>;if(details.deliveryFulfillmentMode==="external_manual"||details.driverDispatchRequired===false)continue;if(details.deliveryStage!=="finding_courier")continue;const existing=(await db.select().from(deliveryJobs).where(eq(deliveryJobs.requestId,row.id)).limit(1))[0];if(existing)continue;const org=row.assignedOrganizationId?(await db.select().from(organizations).where(eq(organizations.id,row.assignedOrganizationId)).limit(1))[0]:undefined;const om=(org?.metadata||{}) as Record<string,unknown>;const[created]=await db.insert(deliveryJobs).values({requestId:row.id,status:"searching_driver",pickupAddress:org?.addressText||undefined,pickupLatitude:n(om.latitude)?.toString(),pickupLongitude:n(om.longitude)?.toString(),dropoffAddress:row.addressText||undefined,dropoffLatitude:row.latitude||undefined,dropoffLongitude:row.longitude||undefined,metadata:{requestCode:row.requestCode,organizationId:row.assignedOrganizationId,deliveryDistanceKm:details.deliveryDistanceKm,deliveryFee:details.deliveryFee,deliveryEtaMinutes:details.deliveryEtaMinutes,deliveryZoneKm:details.deliveryZoneKm}}).returning();if(created){await this.event(created.id,"job_created",{fromStatus:null,toStatus:"searching_driver",metadata:{requestId:row.id}});await db.update(serviceRequests).set({details:{...details,deliveryStage:"searching_driver",deliveryJobId:created.id},updatedAt:new Date()}).where(eq(serviceRequests.id,row.id))}}}
 async listJobs(userId:string,scope:"available"|"mine"="available"){
  await this.ensureReadyJobs();const db=getDb(),driver=await this.ensureProfile(userId);
  const driverLocation=(await db.select().from(driverLocations).where(eq(driverLocations.driverId,driver.id)).limit(1))[0]||null;
  if(scope==="available"&&driver.status!=="available")return[];
  const rows=scope==="mine"?await db.select().from(deliveryJobs).where(eq(deliveryJobs.driverId,driver.id)).orderBy(desc(deliveryJobs.updatedAt)):await db.select().from(deliveryJobs).where(eq(deliveryJobs.status,"searching_driver")).orderBy(asc(deliveryJobs.createdAt));
  const currentPoint=point(driverLocation?.latitude,driverLocation?.longitude),result:any[]=[];
  for(const job of rows){const request=(await db.select().from(serviceRequests).where(eq(serviceRequests.id,job.requestId)).limit(1))[0];const pickup=point(job.pickupLatitude,job.pickupLongitude);const dispatchDistanceKm=currentPoint&&pickup?Number(distanceKm(currentPoint,pickup).toFixed(2)):null;const dispatchEtaMinutes=dispatchDistanceKm===null?null:estimateEtaMinutes(dispatchDistanceKm,n(driverLocation?.speedMps));const orderDetails=(request?.details||{}) as Record<string,unknown>;result.push({...job,requestCode:request?.requestCode,customerName:request?.customerName,customerPhone:request?.customerPhone,title:request?.title,orderDetails,dispatchDistanceKm,dispatchEtaMinutes,deliveryFee:Number(orderDetails.deliveryFee||0),dispatchScore:dispatchDistanceKm===null?0:Math.max(0,100-Math.min(100,dispatchDistanceKm*8))})}
  if(scope==="available")result.sort((a,b)=>(b.dispatchScore-a.dispatchScore)||((a.dispatchDistanceKm??9999)-(b.dispatchDistanceKm??9999))||new Date(a.createdAt).getTime()-new Date(b.createdAt).getTime());
  return result
 }
 async acceptJob(userId:string,jobId:string){const db=getDb(),driver=await this.ensureProfile(userId);if(driver.status!=="available")throw new Error(driver.status==="suspended"?"DRIVER_SUSPENDED":"DRIVER_NOT_AVAILABLE");const active=(await db.select().from(deliveryJobs).where(and(eq(deliveryJobs.driverId,driver.id),inArray(deliveryJobs.status,["assigned","picked_up","delivering"]))).limit(1))[0];if(active)throw new Error("DRIVER_HAS_ACTIVE_JOB");const current=(await db.select().from(deliveryJobs).where(eq(deliveryJobs.id,jobId)).limit(1))[0];if(!current)throw new Error("JOB_NOT_FOUND");if(current.status!=="searching_driver"||current.driverId)throw new Error("JOB_UNAVAILABLE");const now=new Date();const[job]=await db.update(deliveryJobs).set({driverId:driver.id,status:"assigned",assignedAt:now,updatedAt:now}).where(and(eq(deliveryJobs.id,jobId),eq(deliveryJobs.status,"searching_driver"))).returning();if(!job||job.driverId!==driver.id)throw new Error("JOB_UNAVAILABLE");await db.update(driverProfiles).set({status:"busy",updatedAt:now}).where(eq(driverProfiles.id,driver.id));await this.event(job.id,"driver_assigned",{driverId:driver.id,fromStatus:"searching_driver",toStatus:"assigned"});const request=(await db.select().from(serviceRequests).where(eq(serviceRequests.id,job.requestId)).limit(1))[0];if(request){const details={...((request.details||{}) as Record<string,unknown>),deliveryStage:"assigned",deliveryJobId:job.id,driverId:driver.id,driverAssignedAt:now.toISOString()};await db.update(serviceRequests).set({details,updatedAt:now}).where(eq(serviceRequests.id,request.id));await db.insert(serviceRequestStatusHistory).values({requestId:request.id,fromStatus:request.status,toStatus:request.status,note:"DRIVER_ASSIGNED"})}return job}
 async updateJobStatus(userId:string,jobId:string,status:DeliveryJobStatus){const db=getDb(),driver=await this.ensureProfile(userId);const current=(await db.select().from(deliveryJobs).where(eq(deliveryJobs.id,jobId)).limit(1))[0];if(!current)throw new Error("JOB_NOT_FOUND");if(current.driverId!==driver.id)throw new Error("JOB_FORBIDDEN");if(!transitions[current.status as DeliveryJobStatus]?.includes(status))throw new Error("INVALID_DELIVERY_TRANSITION");const now=new Date(),patch:any={status,updatedAt:now};if(status==="picked_up")patch.pickedUpAt=now;if(status==="delivered")patch.deliveredAt=now;const[job]=await db.update(deliveryJobs).set(patch).where(and(eq(deliveryJobs.id,jobId),eq(deliveryJobs.driverId,driver.id),eq(deliveryJobs.status,current.status))).returning();if(!job)throw new Error("DELIVERY_TRANSITION_CONFLICT");await this.event(job.id,`status_${status}`,{driverId:driver.id,fromStatus:current.status,toStatus:status});const request=(await db.select().from(serviceRequests).where(eq(serviceRequests.id,current.requestId)).limit(1))[0];if(request){const details={...((request.details||{}) as Record<string,unknown>),deliveryStage:status,deliveryJobId:job.id,driverId:driver.id,deliveryUpdatedAt:now.toISOString()};await db.update(serviceRequests).set({details,updatedAt:now}).where(eq(serviceRequests.id,request.id));await db.insert(serviceRequestStatusHistory).values({requestId:request.id,fromStatus:request.status,toStatus:request.status,note:`DELIVERY_${status.toUpperCase()}`})}if(status==="delivered"||status==="cancelled")await db.update(driverProfiles).set({status:"available",updatedAt:now}).where(eq(driverProfiles.id,driver.id));return job}
 async updateLocation(userId:string,input:{latitude:number;longitude:number;accuracyMeters?:number;heading?:number;speedMps?:number}){const db=getDb(),driver=await this.ensureProfile(userId),now=new Date();const values={driverId:driver.id,latitude:String(input.latitude),longitude:String(input.longitude),accuracyMeters:input.accuracyMeters==null?undefined:String(input.accuracyMeters),heading:input.heading==null?undefined:String(input.heading),speedMps:input.speedMps==null?undefined:String(input.speedMps),updatedAt:now};const[row]=await db.insert(driverLocations).values(values).onConflictDoUpdate({target:driverLocations.driverId,set:values}).returning();const active=(await db.select().from(deliveryJobs).where(and(eq(deliveryJobs.driverId,driver.id),inArray(deliveryJobs.status,["assigned","picked_up","delivering"]))).orderBy(desc(deliveryJobs.updatedAt)).limit(1))[0];if(active){const latest=(await db.select().from(driverLocationHistory).where(eq(driverLocationHistory.driverId,driver.id)).orderBy(desc(driverLocationHistory.recordedAt)).limit(1))[0];const elapsed=latest?now.getTime()-new Date(latest.recordedAt).getTime():Infinity;const moved=latest?distanceKm({latitude:Number(latest.latitude),longitude:Number(latest.longitude)},{latitude:input.latitude,longitude:input.longitude}):Infinity;if(elapsed>=4000||moved>=0.008)await db.insert(driverLocationHistory).values({driverId:driver.id,jobId:active.id,latitude:String(input.latitude),longitude:String(input.longitude),accuracyMeters:input.accuracyMeters==null?undefined:String(input.accuracyMeters),heading:input.heading==null?undefined:String(input.heading),speedMps:input.speedMps==null?undefined:String(input.speedMps),recordedAt:now})}return row}
 async trackingForRequest(requestId:string){await this.ensureReadyJobs();const db=getDb(),job=(await db.select().from(deliveryJobs).where(eq(deliveryJobs.requestId,requestId)).limit(1))[0];if(!job)return null;let driver:any=null,location:any=null,path:any[]=[];if(job.driverId){const profile=(await db.select().from(driverProfiles).where(eq(driverProfiles.id,job.driverId)).limit(1))[0];if(profile){const user=(await db.select().from(users).where(eq(users.id,profile.userId)).limit(1))[0];driver={id:profile.id,displayName:user?.nickname||"ZhaoXi Driver",avatarUrl:user?.avatarUrl||undefined,vehicleType:profile.vehicleType,plateNumber:profile.plateNumber||undefined};location=(await db.select().from(driverLocations).where(eq(driverLocations.driverId,profile.id)).limit(1))[0]||null;path=await db.select().from(driverLocationHistory).where(and(eq(driverLocationHistory.driverId,profile.id),eq(driverLocationHistory.jobId,job.id))).orderBy(desc(driverLocationHistory.recordedAt)).limit(60);path=path.reverse().map(x=>({latitude:String(x.latitude),longitude:String(x.longitude),accuracyMeters:x.accuracyMeters?String(x.accuracyMeters):undefined,heading:x.heading?String(x.heading):undefined,speedMps:x.speedMps?String(x.speedMps):undefined,recordedAt:x.recordedAt}))}}
  const timeline=await db.select().from(deliveryJobEvents).where(eq(deliveryJobEvents.jobId,job.id)).orderBy(asc(deliveryJobEvents.createdAt));const locationAgeSeconds=location?Math.max(0,Math.round((Date.now()-new Date(location.updatedAt).getTime())/1000)):undefined;let distanceRemainingKm:number|undefined,etaMinutes:number|undefined;const current=point(location?.latitude,location?.longitude),pickup=point(job.pickupLatitude,job.pickupLongitude),dropoff=point(job.dropoffLatitude,job.dropoffLongitude);const target=(job.status==="assigned"||job.status==="searching_driver")?pickup:dropoff;const targetType=(job.status==="assigned"||job.status==="searching_driver")?"pickup":"dropoff";if(current&&target){distanceRemainingKm=Number(distanceKm(current,target).toFixed(2));etaMinutes=estimateEtaMinutes(distanceRemainingKm,n(location?.speedMps))}return{job,driver,location,path,timeline,telemetry:{isLive:locationAgeSeconds!==undefined&&locationAgeSeconds<=20,isStale:locationAgeSeconds!==undefined&&locationAgeSeconds>30,locationAgeSeconds,distanceRemainingKm,etaMinutes,targetType,lastUpdatedAt:location?.updatedAt||null}}}
}
export const driverService=new DriverService();
