import {and,desc,eq,gte} from "drizzle-orm";
import {getDb} from "@/db";
import {betaFeedback} from "@/db/schema";
const APPS=new Set(["customer","partner","admin","driver"]);
const CATS=new Set(["general","bug","suggestion","payment","delivery","partner","account"]);
const STATES=new Set(["new","reviewing","planned","resolved","closed"]);
function clean(v:unknown,max=3000){return String(v??"").replace(/[\u0000-\u001f]/g," ").trim().slice(0,max)}
function safeMeta(input:unknown){if(!input||typeof input!=="object"||Array.isArray(input))return{};const out:Record<string,unknown>={};for(const[k,v]of Object.entries(input as Record<string,unknown>).slice(0,20)){if(/token|secret|password|authorization|cookie/i.test(k))continue;out[k.slice(0,80)]=typeof v==="string"?v.slice(0,500):v}return out}
export class FeedbackService{
 async create(input:Record<string,unknown>,session?:{userId?:string|null;organizationId?:string|null}|null){const app=clean(input.app,24);const category=clean(input.category,32);const message=clean(input.message,4000);if(!message)throw new Error("FEEDBACK_MESSAGE_REQUIRED");const ratingRaw=Number(input.rating||0);const rating=ratingRaw>=1&&ratingRaw<=5?Math.round(ratingRaw):null;const[row]=await getDb().insert(betaFeedback).values({userId:session?.userId||undefined,organizationId:session?.organizationId||undefined,app:APPS.has(app)?app:"customer",category:CATS.has(category)?category:"general",rating,message,route:clean(input.route,700)||null,release:clean(input.release||"15.2.0",40),channel:clean(input.channel||process.env.ZHAOXI_RELEASE_CHANNEL||"beta",16),metadata:safeMeta(input.metadata)}).returning();return row}
 async list(input:{days?:number;app?:string;status?:string;limit?:number}={}){const days=Math.max(1,Math.min(180,Number(input.days||30)));const cond=[gte(betaFeedback.createdAt,new Date(Date.now()-days*86400000))];if(input.app&&APPS.has(input.app))cond.push(eq(betaFeedback.app,input.app));if(input.status&&STATES.has(input.status))cond.push(eq(betaFeedback.status,input.status));return getDb().select().from(betaFeedback).where(and(...cond)).orderBy(desc(betaFeedback.createdAt)).limit(Math.max(1,Math.min(200,Number(input.limit||100))))}
 async update(id:string,status:string){if(!STATES.has(status))throw new Error("FEEDBACK_STATUS_INVALID");const[row]=await getDb().update(betaFeedback).set({status,updatedAt:new Date()}).where(eq(betaFeedback.id,id)).returning();if(!row)throw new Error("FEEDBACK_NOT_FOUND");return row}
 async summary(days=30){const rows=await this.list({days,limit:200});const byApp=new Map<string,number>(),byCategory=new Map<string,number>(),byStatus=new Map<string,number>();for(const r of rows){byApp.set(r.app,(byApp.get(r.app)||0)+1);byCategory.set(r.category,(byCategory.get(r.category)||0)+1);byStatus.set(r.status,(byStatus.get(r.status)||0)+1)}const ratings=rows.map(r=>r.rating).filter((x):x is number=>typeof x==="number");return{generatedAt:new Date().toISOString(),days,total:rows.length,newCount:rows.filter(r=>r.status==="new").length,avgRating:ratings.length?Math.round((ratings.reduce((a,b)=>a+b,0)/ratings.length)*10)/10:null,byApp:[...byApp].map(([app,count])=>({app,count})),byCategory:[...byCategory].map(([category,count])=>({category,count})),byStatus:[...byStatus].map(([status,count])=>({status,count})),recent:rows.slice(0,30)}}
}
export const feedbackService=new FeedbackService();
