import crypto from "node:crypto";import {and,desc,eq} from "drizzle-orm";import {getDb} from "@/db";import {onboardingApplications,organizationMembers,organizations,userRoles,users} from "@/db/schema";import {addressGeocodingService} from "@/lib/services/address-geocoding-service";
const ROLES=new Set(["customer","partner","driver"]);
function clean(v:unknown,n=500){return String(v||"").trim().slice(0,n)||null}
export class OnboardingService{
async status(userId:string){const db=getDb();const rows=await db.select().from(onboardingApplications).where(eq(onboardingApplications.userId,userId)).orderBy(desc(onboardingApplications.updatedAt));const roles=await db.select().from(userRoles).where(and(eq(userRoles.userId,userId),eq(userRoles.isActive,true)));return {applications:rows,provisionedRoles:roles.map(r=>r.role)}}
async submit(userId:string,input:any){const role=String(input.role||"customer");if(!ROLES.has(role))throw new Error("INVALID_ONBOARDING_ROLE");const status=role==="customer"?"approved":"submitted";const values={userId,role,status,displayName:clean(input.displayName,120),phone:clean(input.phone,30),city:clean(input.city,120),businessName:clean(input.businessName,180),businessType:clean(input.businessType,40),addressText:clean(input.addressText,1000),vehicleType:clean(input.vehicleType,40),plateNumber:clean(input.plateNumber,32),notes:clean(input.notes,1000),submittedAt:new Date(),updatedAt:new Date()};const [row]=await getDb().insert(onboardingApplications).values(values).onConflictDoUpdate({target:[onboardingApplications.userId,onboardingApplications.role],set:values}).returning();if(role==="customer"){await this.provision(row.id,userId,"customer");}return row}
async list(){return getDb().select({id:onboardingApplications.id,userId:onboardingApplications.userId,role:onboardingApplications.role,status:onboardingApplications.status,displayName:onboardingApplications.displayName,phone:onboardingApplications.phone,city:onboardingApplications.city,businessName:onboardingApplications.businessName,businessType:onboardingApplications.businessType,addressText:onboardingApplications.addressText,vehicleType:onboardingApplications.vehicleType,plateNumber:onboardingApplications.plateNumber,notes:onboardingApplications.notes,reviewNote:onboardingApplications.reviewNote,submittedAt:onboardingApplications.submittedAt,reviewedAt:onboardingApplications.reviewedAt,nickname:users.nickname,wechatOpenId:users.wechatOpenId}).from(onboardingApplications).leftJoin(users,eq(onboardingApplications.userId,users.id)).orderBy(desc(onboardingApplications.updatedAt)).limit(300)}
async review(id:string,input:any,adminId:string){const status=String(input.status||"");if(!["approved","rejected"].includes(status))throw new Error("INVALID_REVIEW_STATUS");const db=getDb();const row=(await db.select().from(onboardingApplications).where(eq(onboardingApplications.id,id)).limit(1))[0];if(!row)throw new Error("ONBOARDING_NOT_FOUND");if(status==="approved")await this.provision(row.id,row.userId,row.role);const [updated]=await db.update(onboardingApplications).set({status,reviewNote:clean(input.reviewNote,1000),reviewedBy:adminId,reviewedAt:new Date(),updatedAt:new Date()}).where(eq(onboardingApplications.id,id)).returning();return updated}
private async provision(applicationId:string,userId:string,role:string){const db=getDb();await db.insert(userRoles).values({userId,role,isActive:true}).onConflictDoUpdate({target:[userRoles.userId,userRoles.role],set:{isActive:true}});if(role==="partner"){const existing=(await db.select().from(organizationMembers).where(and(eq(organizationMembers.userId,userId),eq(organizationMembers.isActive,true))).limit(1))[0];if(!existing){const app=(await db.select().from(onboardingApplications).where(eq(onboardingApplications.id,applicationId)).limit(1))[0];if(!app?.businessName)throw new Error("PARTNER_BUSINESS_NAME_REQUIRED");const code=`ZX-P-${Date.now().toString(36).toUpperCase()}-${crypto.randomBytes(2).toString("hex").toUpperCase()}`,address=app.addressText||"",geocoded=address?await addressGeocodingService.lookup(address):null;const [org]=await db.insert(organizations).values({code,type:app.businessType||"service",name:app.businessName,addressText:address||undefined,phone:app.phone||undefined,status:"active",metadata:{source:"onboarding-15.4",city:app.city||undefined,...(geocoded?{latitude:geocoded.latitude,longitude:geocoded.longitude,geocodedAddress:geocoded.formattedAddress,geocodedAt:new Date().toISOString(),geocodingStatus:"resolved"}:{geocodingStatus:address?"unresolved":undefined})}}).returning();await db.insert(organizationMembers).values({organizationId:org.id,userId,role:"owner",isActive:true});}}}
}
export const onboardingService=new OnboardingService();
