import{and,eq}from"drizzle-orm";import{getDb}from"@/db";import{operationsAuditLogs,organizationMembers,organizations}from"@/db/schema";import{partnerQualityPolicyService}from"@/lib/services/partner-quality-policy-service";
function md(x:any){return(x?.metadata||{})as Record<string,any>}function iso(){return new Date().toISOString()}function cases(x:any){return Array.isArray(md(x).partnerComplianceCases)?md(x).partnerComplianceCases:[]}
const active=(s:string)=>!["recovered","closed"].includes(s);
export class PartnerComplianceCaseService{
 async admin(){const db=getDb(),orgs=await db.select().from(organizations),quality=await partnerQualityPolicyService.admin();return orgs.flatMap(org=>cases(org).map((c:any)=>({organization:{id:org.id,code:org.code,name:org.name},case:c,currentQuality:quality.partners.find((x:any)=>x.organization.id===org.id)?.summary||null,currentRisk:quality.partners.find((x:any)=>x.organization.id===org.id)?.risk||null}))).sort((a:any,b:any)=>String(b.case.updatedAt).localeCompare(String(a.case.updatedAt)))}
 async partner(userId:string,organizationId:string){const db=getDb(),m=(await db.select().from(organizationMembers).where(and(eq(organizationMembers.userId,userId),eq(organizationMembers.organizationId,organizationId),eq(organizationMembers.isActive,true))).limit(1))[0];if(!m)throw new Error("PARTNER_FORBIDDEN");const org=(await db.select().from(organizations).where(eq(organizations.id,organizationId)).limit(1))[0];if(!org)throw new Error("ORGANIZATION_NOT_FOUND");return cases(org)}
 async open(adminUserId:string,organizationId:string,input:any){const db=getDb(),org=(await db.select().from(organizations).where(eq(organizations.id,organizationId)).limit(1))[0];if(!org)throw new Error("ORGANIZATION_NOT_FOUND");const list=cases(org);if(list.some((x:any)=>active(String(x.status))))throw new Error("ACTIVE_COMPLIANCE_CASE_EXISTS");const q=await partnerQualityPolicyService.admin(),snapshot=q.partners.find((x:any)=>x.organization.id===organizationId),days=Math.max(1,Math.min(90,Math.round(Number(input.deadlineDays||14)))),created=iso(),item={id:crypto.randomUUID(),caseCode:`QC-${Date.now().toString(36).toUpperCase()}`,status:"action_required",reason:String(input.reason||snapshot?.risk?.recommendedAction||"QUALITY_REVIEW").slice(0,500),openedAt:created,updatedAt:created,deadlineAt:new Date(Date.now()+days*86400000).toISOString(),openedBy:adminUserId,riskAtOpen:snapshot?.risk||null,qualityAtOpen:snapshot?.summary||null,correctivePlan:null,evidence:[],timeline:[{at:created,actor:"admin",action:"case_opened"}],recovery:null,advisoryOnly:true,noAutomaticFeeChange:true,noFundControl:true};await this.save(db,org,[...list,item]);await this.audit(db,adminUserId,organizationId,"case_opened",item);return item}
 async partnerPlan(userId:string,organizationId:string,caseId:string,input:any){const db=getDb();await this.member(db,userId,organizationId);const org=(await db.select().from(organizations).where(eq(organizations.id,organizationId)).limit(1))[0],list=cases(org),i=list.findIndex((x:any)=>x.id===caseId);if(i<0)throw new Error("CASE_NOT_FOUND");const c=list[i];if(!active(c.status))throw new Error("CASE_CLOSED");const at=iso(),plan={summary:String(input.summary||"").trim().slice(0,3000),rootCause:String(input.rootCause||"").trim().slice(0,3000),actions:Array.isArray(input.actions)?input.actions.map((x:any)=>String(x).slice(0,1000)).slice(0,20):[],submittedAt:at,submittedBy:userId};if(!plan.summary||!plan.actions.length)throw new Error("CORRECTIVE_PLAN_REQUIRED");list[i]={...c,status:"plan_submitted",correctivePlan:plan,updatedAt:at,timeline:[...(c.timeline||[]),{at,actor:"partner",action:"corrective_plan_submitted"}]};await this.save(db,org,list);return list[i]}
 async evidence(userId:string,organizationId:string,caseId:string,input:any){const db=getDb();await this.member(db,userId,organizationId);const org=(await db.select().from(organizations).where(eq(organizations.id,organizationId)).limit(1))[0],list=cases(org),i=list.findIndex((x:any)=>x.id===caseId);if(i<0)throw new Error("CASE_NOT_FOUND");const c=list[i],at=iso(),e={id:crypto.randomUUID(),label:String(input.label||"Evidence").slice(0,300),reference:String(input.reference||"").slice(0,2000),note:String(input.note||"").slice(0,2000),submittedAt:at,submittedBy:userId};list[i]={...c,evidence:[...(c.evidence||[]),e].slice(-50),updatedAt:at,timeline:[...(c.timeline||[]),{at,actor:"partner",action:"evidence_submitted",evidenceId:e.id}]};await this.save(db,org,list);return list[i]}
 async review(adminUserId:string,organizationId:string,caseId:string,input:any){const db=getDb(),org=(await db.select().from(organizations).where(eq(organizations.id,organizationId)).limit(1))[0];if(!org)throw new Error("ORGANIZATION_NOT_FOUND");const list=cases(org),i=list.findIndex((x:any)=>x.id===caseId);if(i<0)throw new Error("CASE_NOT_FOUND");const c=list[i],decision=String(input.decision||"approve"),allowed=["approve","changes_required","monitor","recover","close"];if(!allowed.includes(decision))throw new Error("CASE_REVIEW_INVALID");const at=iso(),q=await partnerQualityPolicyService.admin(),snap=q.partners.find((x:any)=>x.organization.id===organizationId),status=decision==="approve"?"plan_approved":decision==="changes_required"?"action_required":decision==="monitor"?"monitoring":decision==="recover"?"recovered":"closed",recovery=decision==="recover"?{at,quality:snap?.summary||null,risk:snap?.risk||null,approvedBy:adminUserId}:c.recovery;list[i]={...c,status,recovery,updatedAt:at,adminNote:String(input.note||"").slice(0,2000),timeline:[...(c.timeline||[]),{at,actor:"admin",action:`review_${decision}`,note:String(input.note||"").slice(0,500)}]};await this.save(db,org,list);await this.audit(db,adminUserId,organizationId,`case_${decision}`,list[i]);return list[i]}
 private async member(db:any,userId:string,organizationId:string){const m=(await db.select().from(organizationMembers).where(and(eq(organizationMembers.userId,userId),eq(organizationMembers.organizationId,organizationId),eq(organizationMembers.isActive,true))).limit(1))[0];if(!m)throw new Error("PARTNER_FORBIDDEN")}
 private async save(db:any,org:any,list:any[]){await db.update(organizations).set({metadata:{...md(org),partnerComplianceCases:list.slice(-100)},updatedAt:new Date()}).where(eq(organizations.id,org.id))}
 private async audit(db:any,userId:string,orgId:string,action:string,state:any){await db.insert(operationsAuditLogs).values({actorUserId:userId,area:"partner_compliance_case",action,targetType:"organization",targetId:orgId,afterState:state,metadata:{advisoryOnly:true,noAutomaticFeeChange:true,noFundControl:true}})}
}
export const partnerComplianceCaseService=new PartnerComplianceCaseService();
