import{and,eq}from"drizzle-orm";import{getDb}from"@/db";import{operationsAuditLogs,organizationMembers,organizations}from"@/db/schema";import{partnerTrustCenterService}from"@/lib/services/partner-trust-center-service";
const TYPES=["verified_partner","high_service_quality","reliable_support","quality_recovered"]as const;type BadgeType=typeof TYPES[number];
function md(x:any){return(x?.metadata||{})as Record<string,any>}function badges(x:any){return Array.isArray(md(x).partnerTrustBadges)?md(x).partnerTrustBadges:[]}function now(){return new Date().toISOString()}
function active(b:any){return b.status==="active"&&(!b.expiresAt||new Date(b.expiresAt).getTime()>Date.now())}
export class PartnerTrustGovernanceService{
 async admin(){const db=getDb(),orgs=await db.select().from(organizations),trust=await partnerTrustCenterService.admin();return{partners:orgs.map(org=>({organization:{id:org.id,code:org.code,name:org.name},trust:trust.partners.find((x:any)=>x.organization.id===org.id)||null,badges:badges(org),activeBadges:badges(org).filter(active)})).filter(x=>x.trust||x.badges.length),badgeTypes:TYPES,governance:{manualCertificationOnly:true,trustScoreDoesNotAutoGrant:true,noAutomaticFeeChange:true,noFundControl:true,noRankingChange:true}}}
 async partner(userId:string,organizationId:string){const db=getDb();await this.member(db,userId,organizationId);const org=(await db.select().from(organizations).where(eq(organizations.id,organizationId)).limit(1))[0];if(!org)throw new Error("ORGANIZATION_NOT_FOUND");return{badges:badges(org),activeBadges:badges(org).filter(active),governance:{manualCertificationOnly:true,trustScoreDoesNotAutoGrant:true}}}
 async issue(adminUserId:string,organizationId:string,input:any){const db=getDb(),org=(await db.select().from(organizations).where(eq(organizations.id,organizationId)).limit(1))[0];if(!org)throw new Error("ORGANIZATION_NOT_FOUND");const type=String(input.type||"")as BadgeType;if(!TYPES.includes(type))throw new Error("BADGE_TYPE_INVALID");const reason=String(input.reason||"").trim().slice(0,2000);if(!reason)throw new Error("CERTIFICATION_REASON_REQUIRED");const list=badges(org),at=now(),expiresAt=input.expiresAt?new Date(String(input.expiresAt)).toISOString():null;if(expiresAt&&new Date(expiresAt).getTime()<=Date.now())throw new Error("BADGE_EXPIRY_INVALID");const badge={id:crypto.randomUUID(),type,status:"active",reason,evidenceReference:String(input.evidenceReference||"").slice(0,2000),issuedAt:at,issuedBy:adminUserId,expiresAt,revokedAt:null,revokedBy:null,revokeReason:null,manualCertification:true};const next=[...list.map((x:any)=>x.type===type&&active(x)?{...x,status:"superseded",updatedAt:at}:x),badge].slice(-100);await this.save(db,org,next);await this.audit(db,adminUserId,organizationId,"badge_issued",badge);return badge}
 async revoke(adminUserId:string,organizationId:string,badgeId:string,input:any){const db=getDb(),org=(await db.select().from(organizations).where(eq(organizations.id,organizationId)).limit(1))[0];if(!org)throw new Error("ORGANIZATION_NOT_FOUND");const list=badges(org),i=list.findIndex((x:any)=>x.id===badgeId);if(i<0)throw new Error("BADGE_NOT_FOUND");const reason=String(input.reason||"").trim().slice(0,2000);if(!reason)throw new Error("REVOCATION_REASON_REQUIRED");const at=now();list[i]={...list[i],status:"revoked",revokedAt:at,revokedBy:adminUserId,revokeReason:reason,updatedAt:at};await this.save(db,org,list);await this.audit(db,adminUserId,organizationId,"badge_revoked",list[i]);return list[i]}
 private async member(db:any,userId:string,organizationId:string){const m=(await db.select().from(organizationMembers).where(and(eq(organizationMembers.userId,userId),eq(organizationMembers.organizationId,organizationId),eq(organizationMembers.isActive,true))).limit(1))[0];if(!m)throw new Error("PARTNER_FORBIDDEN")}
 private async save(db:any,org:any,list:any[]){await db.update(organizations).set({metadata:{...md(org),partnerTrustBadges:list},updatedAt:new Date()}).where(eq(organizations.id,org.id))}
 private async audit(db:any,userId:string,orgId:string,action:string,state:any){await db.insert(operationsAuditLogs).values({actorUserId:userId,area:"partner_trust_governance",action,targetType:"organization",targetId:orgId,afterState:state,metadata:{manualCertificationOnly:true,trustScoreDoesNotAutoGrant:true,noAutomaticFeeChange:true,noFundControl:true,noRankingChange:true}})}
}
export const partnerTrustGovernanceService=new PartnerTrustGovernanceService();
