import {and,desc,eq,inArray} from"drizzle-orm";
import {getDb} from"@/db";
import {operationsAuditLogs,organizationMembers,partnerPaymentTransactions,serviceRequests} from"@/db/schema";
function d(v:any){return(v?.details||{}) as Record<string,unknown>}
function n(v:unknown){const x=Number(v);return Number.isFinite(x)?Math.max(0,Math.round(x)):0}
export class PartnerPaymentTransactionService{
 async append(input:{requestId:string;organizationId:string;intentId:string;provider:string;merchantId:string;providerReference?:string|null;eventType:string;status:string;amount:number;currency:string;source:string;idempotencyKey:string;payload?:Record<string,unknown>}){
  const db=getDb();const rows=await db.insert(partnerPaymentTransactions).values({...input,providerReference:input.providerReference||null,payload:input.payload||{}}).onConflictDoNothing({target:partnerPaymentTransactions.idempotencyKey}).returning();return rows[0]||null
 }
 async listForRequest(requestId:string){return getDb().select().from(partnerPaymentTransactions).where(eq(partnerPaymentTransactions.requestId,requestId)).orderBy(desc(partnerPaymentTransactions.createdAt))}
 async partnerList(userId:string,organizationId:string){const member=(await getDb().select().from(organizationMembers).where(and(eq(organizationMembers.userId,userId),eq(organizationMembers.organizationId,organizationId),eq(organizationMembers.isActive,true))).limit(1))[0];if(!member)throw new Error("PARTNER_FORBIDDEN");return getDb().select().from(partnerPaymentTransactions).where(eq(partnerPaymentTransactions.organizationId,organizationId)).orderBy(desc(partnerPaymentTransactions.createdAt)).limit(1000)}
 async reconcile(requestId:string,actorUserId:string,actorRole:"admin"|"partner"){
  const db=getDb(),row=(await db.select().from(serviceRequests).where(eq(serviceRequests.id,requestId)).limit(1))[0];if(!row)throw new Error("TRAVEL_BOOKING_NOT_FOUND");if(actorRole==="partner"){if(!row.assignedOrganizationId)throw new Error("PARTNER_FORBIDDEN");const member=(await db.select().from(organizationMembers).where(and(eq(organizationMembers.userId,actorUserId),eq(organizationMembers.organizationId,row.assignedOrganizationId),eq(organizationMembers.isActive,true))).limit(1))[0];if(!member)throw new Error("PARTNER_FORBIDDEN")}
  const txs=await this.listForRequest(requestId),latest=txs.find(x=>["paid","failed","cancelled","closed","refunded","pending"].includes(x.status));const details=d(row),current=String(details.travelPaymentStatus||"not_started");if(!latest)return{requestId,currentStatus:current,providerStatus:null,matched:true,repaired:false};
  const mapped=latest.status==="closed"?"cancelled":latest.status;const matched=current===mapped;if(matched)return{requestId,currentStatus:current,providerStatus:mapped,matched:true,repaired:false,transactionId:latest.id};
  const now=new Date().toISOString(),intent={...((details.partnerPaymentIntent||{}) as Record<string,unknown>),status:latest.status,providerReference:latest.providerReference||null,updatedAt:now};const next={...details,partnerPaymentIntent:intent,travelPaymentStatus:mapped,travelPaymentPaidAt:mapped==="paid"?details.travelPaymentPaidAt||now:details.travelPaymentPaidAt||null,travelPaymentReconciledAt:now,travelPaymentReconciledBy:actorUserId};
  await db.update(serviceRequests).set({details:next,updatedAt:new Date()}).where(eq(serviceRequests.id,requestId));await db.insert(operationsAuditLogs).values({actorUserId,area:"partner_payment_reconciliation",action:"repair",targetType:"service_request",targetId:requestId,beforeState:{travelPaymentStatus:current},afterState:{travelPaymentStatus:mapped},metadata:{transactionId:latest.id,actorRole,directToPartner:true}});
  await this.append({requestId,organizationId:row.assignedOrganizationId!,intentId:String(latest.intentId),provider:latest.provider,merchantId:latest.merchantId,providerReference:latest.providerReference,eventType:"reconciled",status:mapped,amount:n(latest.amount),currency:latest.currency,source:"reconciliation",idempotencyKey:`reconcile:${requestId}:${latest.id}:${mapped}`,payload:{previousStatus:current,actorRole}});
  return{requestId,currentStatus:mapped,providerStatus:mapped,matched:false,repaired:true,transactionId:latest.id}
 }
 async adminSummary(){const db=getDb(),rows=await db.select().from(partnerPaymentTransactions).orderBy(desc(partnerPaymentTransactions.createdAt)).limit(5000),intents=[...new Set(rows.map(x=>x.intentId))],latest=intents.map(id=>rows.find(x=>x.intentId===id)!).filter(Boolean),requestIds=[...new Set(latest.map(x=>x.requestId))],requests=requestIds.length?await db.select().from(serviceRequests).where(inArray(serviceRequests.id,requestIds)):[];const reconciliation=latest.map(tx=>{const r=requests.find(x=>x.id===tx.requestId),current=String(d(r).travelPaymentStatus||"not_started"),provider=tx.status==="closed"?"cancelled":tx.status;return{requestId:tx.requestId,requestCode:r?.requestCode||"",organizationId:tx.organizationId,intentId:tx.intentId,currentStatus:current,providerStatus:provider,matched:current===provider,amount:tx.amount,currency:tx.currency,provider:tx.provider,merchantId:tx.merchantId,lastEventAt:tx.createdAt}});return{transactions:rows.slice(0,1000),reconciliation,summary:{transactionEvents:rows.length,intents:intents.length,mismatches:reconciliation.filter(x=>!x.matched).length,paid:latest.filter(x=>x.status==="paid").length,pending:latest.filter(x=>x.status==="pending").length,failed:latest.filter(x=>x.status==="failed").length,cancelled:latest.filter(x=>["cancelled","closed"].includes(x.status)).length,refunded:latest.filter(x=>x.status==="refunded").length,paidAmount:latest.filter(x=>x.status==="paid").reduce((a,x)=>a+n(x.amount),0)}}}
}
export const partnerPaymentTransactionService=new PartnerPaymentTransactionService();
