import{and,eq}from"drizzle-orm";import{getDb}from"@/db";import{organizationMembers,organizations,serviceRequests}from"@/db/schema";
function d(v:any){return(v?.details||{})as Record<string,any>}function ts(v:any){const x=v?new Date(v).getTime():0;return Number.isFinite(x)?x:0}function pct(n:number,d:number){return d?Math.round(n*1000/d)/10:100}function avg(a:number[]){return a.length?Math.round(a.reduce((x,y)=>x+y,0)/a.length):0}function clamp(n:number){return Math.max(0,Math.min(100,Math.round(n)))}
type Metric={key:string;score:number;weight:number;sample:number};
export class PaymentSupportAnalyticsService{
 private derive(rows:any[]){const now=Date.now(),tickets=rows.map(r=>({r,x:d(r),t:d(r).paymentSupportTicket})).filter(v=>v.t),exceptions=rows.filter(r=>d(r).paymentException),ticketCount=tickets.length,resolved=tickets.filter(v=>["resolved","closed"].includes(String(v.t.stage))).length,active=ticketCount-resolved,escalated=tickets.filter(v=>String(v.t.stage)==="escalated"||v.t.adminEscalatedAt).length,overdue=tickets.filter(v=>!["resolved","closed"].includes(String(v.t.stage))&&ts(v.t.slaDueAt)&&ts(v.t.slaDueAt)<now).length;
 const responseMinutes:number[]=[],slaSamples:{met:boolean}[]=[],refundSamples:{met:boolean}[]=[];
 for(const v of tickets){const opened=ts(v.t.createdAt),timeline=Array.isArray(v.t.timeline)?v.t.timeline:[],msgs=Array.isArray(v.t.messages)?v.t.messages:[];const partnerTimes=[...timeline.filter((x:any)=>x.actor==="partner").map((x:any)=>ts(x.at)),...msgs.filter((x:any)=>x.sender==="partner").map((x:any)=>ts(x.createdAt))].filter(Boolean).sort((a,b)=>a-b);if(opened&&partnerTimes[0]>=opened)responseMinutes.push(Math.round((partnerTimes[0]-opened)/60000));
   if(opened&&ts(v.t.slaDueAt)&&partnerTimes[0])slaSamples.push({met:partnerTimes[0]<=ts(v.t.slaDueAt)});
   const refundCompleted=ts(v.t.refundCompletedAt);if(refundCompleted){const awaitEvents=timeline.filter((x:any)=>x.action==="await_refund"&&x.refundEtaAt).sort((a:any,b:any)=>ts(b.at)-ts(a.at));const target=awaitEvents.length?ts(awaitEvents[0].refundEtaAt):0;if(target)refundSamples.push({met:refundCompleted<=target})}}
 const firstResponseAvgMinutes=avg(responseMinutes),slaMetCount=slaSamples.filter(x=>x.met).length,refundEtaMetCount=refundSamples.filter(x=>x.met).length,slaMetRate=pct(slaMetCount,slaSamples.length),refundEtaMetRate=pct(refundEtaMetCount,refundSamples.length),escalationRate=pct(escalated,ticketCount),exceptionRate=pct(exceptions.length,Math.max(1,ticketCount));
 const responseScore=firstResponseAvgMinutes===0?(responseMinutes.length?100:100):clamp(100-firstResponseAvgMinutes/14.4),metrics:Metric[]=[
   {key:"sla",score:slaMetRate,weight:30,sample:slaSamples.length},
   {key:"response",score:responseScore,weight:20,sample:responseMinutes.length},
   {key:"refundEta",score:refundEtaMetRate,weight:25,sample:refundSamples.length},
   {key:"escalation",score:clamp(100-escalationRate),weight:15,sample:ticketCount},
   {key:"exception",score:clamp(100-exceptionRate),weight:10,sample:ticketCount}
 ];const usable=metrics.filter(x=>x.sample>0),den=usable.reduce((a,x)=>a+x.weight,0),qualityScore=den?clamp(usable.reduce((a,x)=>a+x.score*x.weight,0)/den):100;
 return{summary:{ticketCount,active,resolved,escalated,overdue,exceptions:exceptions.length,firstResponseAvgMinutes,slaSampleSize:slaSamples.length,slaMetRate,refundEtaSampleSize:refundSamples.length,refundEtaMetRate,escalationRate,exceptionRate,qualityScore},quality:{score:qualityScore,metrics},tickets:tickets.slice(0,200).map(v=>({requestId:v.r.id,requestCode:v.r.requestCode,stage:v.t.stage,createdAt:v.t.createdAt,slaDueAt:v.t.slaDueAt,refundEtaAt:v.t.refundEtaAt||null,refundCompletedAt:v.t.refundCompletedAt||null,escalated:Boolean(v.t.adminEscalatedAt)||v.t.stage==="escalated"}))}}
 async partner(userId:string,organizationId:string){const db=getDb(),m=(await db.select().from(organizationMembers).where(and(eq(organizationMembers.userId,userId),eq(organizationMembers.organizationId,organizationId),eq(organizationMembers.isActive,true))).limit(1))[0];if(!m)throw new Error("PARTNER_FORBIDDEN");const org=(await db.select().from(organizations).where(eq(organizations.id,organizationId)).limit(1))[0],rows=await db.select().from(serviceRequests).where(eq(serviceRequests.assignedOrganizationId,organizationId));return{organization:{id:org?.id,code:org?.code,name:org?.name},...this.derive(rows)}}
 async admin(){const db=getDb(),orgs=await db.select().from(organizations),all=await db.select().from(serviceRequests),partners=orgs.map(org=>({organization:{id:org.id,code:org.code,name:org.name},...this.derive(all.filter(r=>r.assignedOrganizationId===org.id))})).filter(x=>x.summary.ticketCount||x.summary.exceptions).sort((a,b)=>b.summary.qualityScore-a.summary.qualityScore);const totalTickets=partners.reduce((a,x)=>a+x.summary.ticketCount,0),weighted=(key:"slaMetRate"|"refundEtaMetRate")=>{const sampleKey=key==="slaMetRate"?"slaSampleSize":"refundEtaSampleSize";const den=partners.reduce((a,x)=>a+x.summary[sampleKey],0);return den?Math.round(partners.reduce((a,x)=>a+x.summary[key]*x.summary[sampleKey],0)/den*10)/10:100};return{partners,summary:{partnerCount:partners.length,totalTickets,active:partners.reduce((a,x)=>a+x.summary.active,0),overdue:partners.reduce((a,x)=>a+x.summary.overdue,0),escalated:partners.reduce((a,x)=>a+x.summary.escalated,0),exceptions:partners.reduce((a,x)=>a+x.summary.exceptions,0),slaMetRate:weighted("slaMetRate"),refundEtaMetRate:weighted("refundEtaMetRate"),averageQualityScore:partners.length?Math.round(partners.reduce((a,x)=>a+x.summary.qualityScore,0)/partners.length):100}}}
}
export const paymentSupportAnalyticsService=new PaymentSupportAnalyticsService();
