import {eq} from"drizzle-orm";
import {getDb} from"@/db";
import {operationsAuditLogs,organizations} from"@/db/schema";
import {paymentProviderRegistryService} from"@/lib/services/payment-provider-registry-service";

export type CircuitState="closed"|"open"|"half_open";
export type RuntimeHealth={providerId:string;state:CircuitState;consecutiveFailures:number;totalSuccess:number;totalFailures:number;lastSuccessAt?:string|null;lastFailureAt?:string|null;lastError?:string|null;openedAt?:string|null;openUntil?:string|null;updatedAt:string};
const FAILURE_THRESHOLD=3,OPEN_MS=5*60*1000;
function metadata(v:any){return(v?.metadata||{}) as Record<string,unknown>}
function now(){return new Date().toISOString()}
function defaultHealth(providerId:string):RuntimeHealth{return{providerId,state:"closed",consecutiveFailures:0,totalSuccess:0,totalFailures:0,lastSuccessAt:null,lastFailureAt:null,lastError:null,openedAt:null,openUntil:null,updatedAt:now()}}
export class PaymentProviderRuntimeService{
 private async organization(id:string){const row=(await getDb().select().from(organizations).where(eq(organizations.id,id)).limit(1))[0];if(!row)throw new Error("ORGANIZATION_NOT_FOUND");return row}
 private read(org:any,providerId:string){const root=(metadata(org).paymentProviderRuntime||{}) as Record<string,unknown>,raw=(root[providerId]||{}) as Partial<RuntimeHealth>;return{...defaultHealth(providerId),...raw,providerId} as RuntimeHealth}
 async get(organizationId:string,providerId:string){paymentProviderRegistryService.get(providerId);const org=await this.organization(organizationId),health=this.read(org,providerId);if(health.state==="open"&&health.openUntil&&new Date(health.openUntil).getTime()<=Date.now())return{...health,state:"half_open" as const};return health}
 async canExecute(organizationId:string,providerId:string){const registry=paymentProviderRegistryService.get(providerId),health=await this.get(organizationId,providerId);if(!registry.enabled)return{allowed:false,reason:"provider_disabled",health,registry};if(health.state==="open")return{allowed:false,reason:"circuit_open",health,registry};return{allowed:true,reason:health.state==="half_open"?"half_open_probe":"healthy",health,registry}}
 private async write(organizationId:string,providerId:string,next:RuntimeHealth,actorUserId?:string|null,event?:string){const db=getDb(),org=await this.organization(organizationId),m=metadata(org),runtime=(m.paymentProviderRuntime||{}) as Record<string,unknown>;await db.update(organizations).set({metadata:{...m,paymentProviderRuntime:{...runtime,[providerId]:next}},updatedAt:new Date()}).where(eq(organizations.id,organizationId));if(event)await db.insert(operationsAuditLogs).values({actorUserId:actorUserId||null,area:"payment_provider_runtime",action:event,targetType:"organization",targetId:organizationId,afterState:{providerId,health:next},metadata:{providerId,directToPartner:true}});return next}
 async success(organizationId:string,providerId:string){const prev=await this.get(organizationId,providerId),next:RuntimeHealth={...prev,state:"closed",consecutiveFailures:0,totalSuccess:prev.totalSuccess+1,lastSuccessAt:now(),lastError:null,openedAt:null,openUntil:null,updatedAt:now()};return this.write(organizationId,providerId,next,null,prev.state!=="closed"?"circuit_closed":"runtime_success")}
 async failure(organizationId:string,providerId:string,error:unknown){const prev=await this.get(organizationId,providerId),count=prev.consecutiveFailures+1,open=count>=FAILURE_THRESHOLD,stamp=now(),next:RuntimeHealth={...prev,state:open?"open":"closed",consecutiveFailures:count,totalFailures:prev.totalFailures+1,lastFailureAt:stamp,lastError:String(error instanceof Error?error.message:error||"PROVIDER_RUNTIME_FAILURE").slice(0,300),openedAt:open?stamp:prev.openedAt||null,openUntil:open?new Date(Date.now()+OPEN_MS).toISOString():prev.openUntil||null,updatedAt:stamp};return this.write(organizationId,providerId,next,null,open?"circuit_opened":"runtime_failure")}
 async probe(organizationId:string,providerId:string){const gate=await this.canExecute(organizationId,providerId);return{organizationId,providerId,...gate,checkedAt:now(),threshold:FAILURE_THRESHOLD,openMs:OPEN_MS}}
 async adminOverview(){const orgs=await getDb().select().from(organizations),providers=paymentProviderRegistryService.list(),rows=[] as any[];for(const org of orgs){const m=metadata(org),gateway=(m.partnerPaymentGateway||{}) as Record<string,unknown>,primary=String(gateway.provider||"partner_checkout_link"),fallback=(gateway.fallbackGateway||{}) as Record<string,unknown>,ids=[primary,...(fallback.enabled===true&&fallback.provider?[String(fallback.provider)]:[])];for(const providerId of [...new Set(ids)]){try{rows.push({organization:{id:org.id,code:org.code,name:org.name},provider:paymentProviderRegistryService.get(providerId),health:await this.get(org.id,providerId),role:providerId===primary?"primary":"fallback"})}catch{}}}return{providers,rows,threshold:FAILURE_THRESHOLD,openMs:OPEN_MS}}
}
export const paymentProviderRuntimeService=new PaymentProviderRuntimeService();
