import{eq}from"drizzle-orm";import{getDb}from"@/db";import{modules,moduleTranslations,organizations,services,serviceTranslations}from"@/db/schema";
function md(x:any){return(x?.metadata||{})as Record<string,any>}function active(x:any){return x.status==="active"&&(!x.expiresAt||new Date(x.expiresAt).getTime()>Date.now())}
const labels:Record<string,string>={verified_partner:"Verified Partner",high_service_quality:"High Service Quality",reliable_support:"Reliable Support",quality_recovered:"Quality Recovered"};
function publicBadges(org:any){const xs=Array.isArray(md(org).partnerTrustBadges)?md(org).partnerTrustBadges:[];return xs.filter(active).map((x:any)=>({type:x.type,label:labels[x.type]||x.type,issuedAt:x.issuedAt,expiresAt:x.expiresAt||null,verifiedManually:true}))}
function identity(org:any){const m=md(org),pub=(m.publicTrustProfile||{})as Record<string,any>;return{id:org.id,code:org.code,name:org.name,type:org.type,description:pub.description||org.description||"",addressText:org.addressText||"",logoUrl:String(pub.logoUrl||m.logoUrl||""),coverUrl:String(pub.coverUrl||m.coverUrl||""),publicPhone:pub.showPhone===true?org.phone||"": "",publicEmail:pub.showEmail===true?org.email||"": "",badges:publicBadges(org),verification:{manualReview:true,trustScoreAutoBadge:false},publicProfile:{headline:String(pub.headline||""),servicePromise:String(pub.servicePromise||""),since:String(pub.since||""),website:String(pub.website||"")}}}
export class PublicPartnerTrustService{
 async get(organizationId:string){const db=getDb(),org=(await db.select().from(organizations).where(eq(organizations.id,organizationId)).limit(1))[0];if(!org||org.status!=="active")throw new Error("PUBLIC_PARTNER_NOT_FOUND");const sv=await db.select().from(services).where(eq(services.organizationId,organizationId)),tr=await db.select().from(serviceTranslations),mods=await db.select().from(modules),modTr=await db.select().from(moduleTranslations);const items=sv.filter(x=>x.isEnabled).slice(0,100).map(x=>{const names=tr.filter(y=>y.serviceId===x.id),mod=mods.find(m=>m.id===x.moduleId),moduleCode=String(mod?.code||"other"),moduleRoute=String(mod?.route||"/services"),moduleNames=modTr.filter(z=>z.moduleId===x.moduleId),publicHref=moduleCode==="food"?`/restaurant/${organizationId}`:moduleCode==="housing"?`/housing/${x.id}`:moduleCode==="travel"?`/travel/${x.id}`:`${moduleRoute.replace(/\/$/,"")}/${x.id}`;return{id:x.id,code:x.code,moduleId:x.moduleId,moduleCode,moduleRoute,publicHref,priceFrom:Number(x.priceFrom||0),currency:x.currency,metadata:x.metadata,translations:names.map(y=>({locale:y.locale,name:y.name,summary:y.summary})),moduleTranslations:moduleNames.map(y=>({locale:y.locale,name:y.name,shortName:y.shortName}))}});const portfolio=Object.values(items.reduce((acc:any,item:any)=>{const k=item.moduleCode;if(!acc[k])acc[k]={moduleCode:k,moduleRoute:item.moduleRoute,moduleTranslations:item.moduleTranslations,services:[]};acc[k].services.push(item);return acc},{} as Record<string,any>));return{partner:identity(org),services:items,portfolio,storefront:{organizationId,title:org.name,serviceCount:items.length,moduleCount:portfolio.length},privacy:{publicBadgesOnly:true,internalTrustScore:false,internalRisk:false,complianceCases:false,adminInterventions:false}}}
 async batch(ids:string[]){const db=getDb(),uniq=[...new Set(ids.filter(Boolean))].slice(0,100),orgs=await db.select().from(organizations);return uniq.map(id=>orgs.find(o=>o.id===id)).filter((o:any)=>o&&o.status==="active").map((o:any)=>({organizationId:o.id,name:o.name,code:o.code,badges:publicBadges(o)}))}
}
export const publicPartnerTrustService=new PublicPartnerTrustService();
