import crypto from "node:crypto";
import { and, eq, isNull } from "drizzle-orm";
import { getDb } from "@/db";
import { organizationMembers, organizations, roleSwitchHandoffs, userRoles } from "@/db/schema";
import type { WeChatRole } from "@/lib/services/wechat-auth-service";
const VALID_ROLES = new Set<WeChatRole>(["customer", "partner", "driver", "admin"]); const TTL_MS = 60_000;
function digest(value:string){return crypto.createHash("sha256").update(value).digest("hex");}
async function resolveRoleContext(userId:string, role:WeChatRole){const db=getDb();if(role==="customer")return {organizationId:undefined as string|undefined};if(role==="partner"){const row=(await db.select({organizationId:organizations.id}).from(organizationMembers).innerJoin(organizations,eq(organizationMembers.organizationId,organizations.id)).where(and(eq(organizationMembers.userId,userId),eq(organizationMembers.isActive,true),eq(organizations.status,"active"))).limit(1))[0];if(!row)throw new Error("PARTNER_NOT_LINKED");return row;}const allowed=(await db.select().from(userRoles).where(and(eq(userRoles.userId,userId),eq(userRoles.role,role),eq(userRoles.isActive,true))).limit(1))[0];if(!allowed)throw new Error(role==="driver"?"DRIVER_NOT_AUTHORIZED":"ADMIN_NOT_AUTHORIZED");return {organizationId:undefined as string|undefined};}
export class RoleSwitchService{async create(userId:string,targetRoleValue:unknown){const targetRole=String(targetRoleValue||"") as WeChatRole;if(!VALID_ROLES.has(targetRole))throw new Error("INVALID_TARGET_ROLE");const context=await resolveRoleContext(userId,targetRole);const code=crypto.randomBytes(32).toString("base64url");const expiresAt=new Date(Date.now()+TTL_MS);await getDb().insert(roleSwitchHandoffs).values({codeHash:digest(code),userId,targetRole,organizationId:context.organizationId,expiresAt});return {code,targetRole,expiresAt:expiresAt.toISOString()};}async consume(codeValue:unknown){const code=String(codeValue||"").trim();if(!code)throw new Error("HANDOFF_CODE_REQUIRED");const db=getDb();const row=(await db.select().from(roleSwitchHandoffs).where(eq(roleSwitchHandoffs.codeHash,digest(code))).limit(1))[0];if(!row||row.consumedAt||row.expiresAt.getTime()<=Date.now())throw new Error("HANDOFF_INVALID_OR_EXPIRED");const targetRole=row.targetRole as WeChatRole;if(!VALID_ROLES.has(targetRole))throw new Error("INVALID_TARGET_ROLE");const context=await resolveRoleContext(row.userId,targetRole);const [claimed]=await db.update(roleSwitchHandoffs).set({consumedAt:new Date()}).where(and(eq(roleSwitchHandoffs.id,row.id),isNull(roleSwitchHandoffs.consumedAt))).returning();if(!claimed)throw new Error("HANDOFF_ALREADY_USED");return {userId:row.userId,role:targetRole,organizationId:context.organizationId||row.organizationId||undefined};}}
export const roleSwitchService=new RoleSwitchService();
