import{and,desc,eq}from"drizzle-orm";import{getDb}from"@/db";import{operationsAuditLogs,supportKnowledgeArticles,supportKnowledgeFeedback,supportKnowledgeViews}from"@/db/schema";
function clean(v:any,n:number){return String(v??"").trim().slice(0,n)}
function slugify(v:any){return clean(v,180).toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"")||`article-${Date.now()}`}
function words(v:any){return new Set(clean(v,8000).toLowerCase().split(/[^a-z0-9\u00c0-\u024f\u4e00-\u9fff]+/).filter(x=>x.length>2))}
function score(article:any,q:string){const qw=words(q);if(!qw.size)return 0;const hay=words(`${article.title} ${article.summary} ${(article.tags||[]).join(" ")} ${article.category}`);let n=0;for(const w of qw)if(hay.has(w))n++;return n}
export class SupportKnowledgeService{
 async adminList(locale?:string){const db=getDb(),rows=await db.select().from(supportKnowledgeArticles).orderBy(desc(supportKnowledgeArticles.updatedAt));return locale?rows.filter(x=>x.locale===locale):rows}
 async publicList(locale="vi-VN",q="",category=""){const rows=(await this.adminList(locale)).filter(x=>x.status==="published"&&(!category||x.category===category));return rows.map(x=>({...x,relevance:score(x,q)})).filter(x=>!q||x.relevance>0).sort((a,b)=>b.relevance-a.relevance||new Date(b.updatedAt).getTime()-new Date(a.updatedAt).getTime())}
 async getPublic(idOrSlug:string,locale="vi-VN",userId?:string|null,source="help_center"){const rows=await this.publicList(locale);const row=rows.find(x=>x.id===idOrSlug||x.slug===idOrSlug);if(!row)throw new Error("KNOWLEDGE_ARTICLE_NOT_FOUND");await getDb().insert(supportKnowledgeViews).values({articleId:row.id,userId:userId||null,source:clean(source,40)||"help_center"});return row}
 async save(actorId:string,input:any){const db=getDb(),id=clean(input.id,80),title=clean(input.title,220),body=clean(input.body,30000);if(!title||!body)throw new Error("KNOWLEDGE_FIELDS_REQUIRED");const values={slug:slugify(input.slug||title),locale:clean(input.locale,16)||"vi-VN",title,summary:clean(input.summary,1000),body,category:clean(input.category,80)||"general",tags:Array.isArray(input.tags)?input.tags.map((x:any)=>clean(x,50)).filter(Boolean).slice(0,20):[],status:["draft","published","archived"].includes(String(input.status))?String(input.status):"draft",publishedAt:String(input.status)==="published"?new Date():null,updatedByUserId:actorId,updatedAt:new Date()};let row:any;if(id){row=(await db.update(supportKnowledgeArticles).set(values).where(eq(supportKnowledgeArticles.id,id)).returning())[0]}else{row=(await db.insert(supportKnowledgeArticles).values({...values,createdByUserId:actorId}).returning())[0]}if(!row)throw new Error("KNOWLEDGE_SAVE_FAILED");await this.audit(actorId,row.id,id?"knowledge_updated":"knowledge_created",{status:row.status,locale:row.locale});return row}
 async feedback(userId:string|null,articleId:string,input:any){const helpful=input.helpful===true,comment=clean(input.comment,1500);const row=(await getDb().insert(supportKnowledgeFeedback).values({articleId,userId:userId||null,helpful,comment}).returning())[0];return row}
 async analytics(){const db=getDb(),[articles,views,feedback]=await Promise.all([db.select().from(supportKnowledgeArticles),db.select().from(supportKnowledgeViews),db.select().from(supportKnowledgeFeedback)]);return articles.map(a=>{const av=views.filter(x=>x.articleId===a.id),af=feedback.filter(x=>x.articleId===a.id),yes=af.filter(x=>x.helpful).length;return{articleId:a.id,title:a.title,locale:a.locale,status:a.status,views:av.length,feedback:af.length,helpful:yes,helpfulRate:af.length?Number((yes/af.length*100).toFixed(1)):null}}).sort((a,b)=>b.views-a.views)}
 async recommend(context:string,locale="vi-VN",limit=5){const rows=await this.publicList(locale,context);return rows.slice(0,Math.max(1,Math.min(10,limit))).map(x=>({id:x.id,slug:x.slug,title:x.title,summary:x.summary,category:x.category,relevance:x.relevance,href:`/help/${x.slug}`}))}
 private async audit(actorId:string,targetId:string,action:string,metadata:Record<string,unknown>){await getDb().insert(operationsAuditLogs).values({actorUserId:actorId,area:"support_knowledge",action,targetType:"support_knowledge_article",targetId,metadata})}
}
export const supportKnowledgeService=new SupportKnowledgeService();
