import {asc,desc,eq} from "drizzle-orm";
import {getDb} from "@/db";
import {serviceRequests,supportConversations,supportMessages} from "@/db/schema";

type Locale="zh-CN"|"zh-TW"|"vi-VN"|"en-US";
type Role="customer"|"partner"|"admin"|"driver";
function loc(value:string):Locale{return (["zh-CN","zh-TW","vi-VN","en-US"] as string[]).includes(value)?value as Locale:"vi-VN"}
function intentOf(text:string){const s=text.toLowerCase();if(/human|agent|nhân viên|人工|客服/.test(s))return"human";if(/payment|pay|thanh toán|wechat pay|付款|支付/.test(s))return"payment";if(/driver|delivery|ship|giao|tài xế|配送|司机/.test(s))return"delivery";if(/order|đơn|订单/.test(s))return"order";if(/login|account|wechat|đăng nhập|tài khoản|登录|账号/.test(s))return"account";if(/partner|restaurant|store|đối tác|nhà hàng|合作|商家/.test(s))return"partner";return"general"}
const answer:Record<Locale,Record<string,string>>={
 "vi-VN":{order:"Bạn có thể mở mục Đơn hàng để xem trạng thái mới nhất. Nếu gửi mã đơn (ví dụ ZX...), tôi sẽ kiểm tra ngữ cảnh đơn cho bạn.",delivery:"Khi tài xế nhận chuyến, trang chi tiết đơn sẽ hiển thị trạng thái giao hàng, vị trí gần realtime, quãng đường còn lại và ETA.",payment:"ZhaoXi hỗ trợ trạng thái thanh toán thống nhất. COD dùng được mặc định; WeChat Pay chỉ hoạt động khi merchant đã được cấu hình và giao dịch đáp ứng điều kiện tiền tệ.",account:"Đăng nhập WeChat QR là phương thức chính. Phiên đăng nhập và quyền Customer/Partner/Admin/Driver được Backend xác thực.",partner:"Đối tác quản lý gian hàng, dịch vụ, media và đơn hàng từ Partner Center. Nội dung được đồng bộ sang Customer sau khi xuất bản.",general:"Tôi có thể hỗ trợ về đơn hàng, giao hàng, thanh toán, tài khoản WeChat và hoạt động đối tác. Bạn hãy mô tả vấn đề cụ thể hơn.",human:"Tôi đã chuyển cuộc trò chuyện sang hàng chờ hỗ trợ của nhân viên."},
 "en-US":{order:"Open Orders to see the latest status. If you send a ZhaoXi order code, I can use its context to help.",delivery:"After a driver accepts the job, order details show delivery state, near-live location, remaining distance and ETA.",payment:"ZhaoXi uses one payment state model. COD is available by default; WeChat Pay requires configured merchant credentials and an eligible currency.",account:"WeChat QR is the primary sign-in method. The backend validates sessions and Customer/Partner/Admin/Driver roles.",partner:"Partners manage stores, services, media and orders in Partner Center, then publish content to Customer.",general:"I can help with orders, delivery, payments, WeChat accounts and partner operations. Tell me what you need.",human:"I have moved this conversation to the human-support queue."},
 "zh-CN":{order:"您可以在订单中心查看最新状态。发送赵喜订单编号（如 ZX...），我可以结合订单信息继续协助。",delivery:"配送员接单后，订单详情会显示配送状态、近实时位置、剩余距离和预计到达时间。",payment:"赵喜使用统一支付状态。货到付款默认可用；微信支付需要完成商户配置并满足交易币种条件。",account:"微信扫码是主要登录方式，Customer/Partner/Admin/Driver 的会话和权限由后端验证。",partner:"合作伙伴可在 Partner Center 管理店铺、服务、图片和订单，发布后同步到 Customer。",general:"我可以协助订单、配送、支付、微信账号和商家运营问题。请描述具体问题。",human:"已将此对话转入人工客服队列。"},
 "zh-TW":{order:"您可以在訂單中心查看最新狀態。傳送趙喜訂單編號（如 ZX...），我可以結合訂單資訊協助。",delivery:"配送員接單後，訂單詳情會顯示配送狀態、近即時位置、剩餘距離與預計到達時間。",payment:"趙喜使用統一付款狀態。貨到付款預設可用；微信支付需要完成商戶設定並符合交易幣別條件。",account:"微信掃碼是主要登入方式，Customer/Partner/Admin/Driver 的工作階段與權限由後端驗證。",partner:"合作夥伴可在 Partner Center 管理店鋪、服務、圖片與訂單，發佈後同步到 Customer。",general:"我可以協助訂單、配送、付款、微信帳號與商家營運問題。請描述具體問題。",human:"已將此對話轉入人工客服佇列。"}
};
async function externalAssist(payload:unknown){const url=process.env.ZHAOXI_AI_ASSIST_URL?.trim();if(!url)return"";try{const r=await fetch(url,{method:"POST",headers:{"content-type":"application/json",...(process.env.ZHAOXI_AI_ASSIST_KEY?{authorization:`Bearer ${process.env.ZHAOXI_AI_ASSIST_KEY}`}:{})},body:JSON.stringify(payload),signal:AbortSignal.timeout(12000)});if(!r.ok)return"";const j:any=await r.json();return String(j.answer||j.output||j.message||"").trim()}catch{return""}}
export class SupportService{
 async create(input:{userId?:string;organizationId?:string;role?:Role;locale?:string;subject?:string}){const [row]=await getDb().insert(supportConversations).values({userId:input.userId,organizationId:input.organizationId,role:input.role||"customer",locale:loc(input.locale||"vi-VN"),subject:input.subject||"ZhaoXi Support"}).returning();return row}
 async messages(id:string){return getDb().select().from(supportMessages).where(eq(supportMessages.conversationId,id)).orderBy(asc(supportMessages.createdAt))}
 async list(userId?:string,organizationId?:string){let rows;if(userId)rows=await getDb().select().from(supportConversations).where(eq(supportConversations.userId,userId)).orderBy(desc(supportConversations.lastMessageAt)).limit(50);else if(organizationId)rows=await getDb().select().from(supportConversations).where(eq(supportConversations.organizationId,organizationId)).orderBy(desc(supportConversations.lastMessageAt)).limit(50);else rows=await getDb().select().from(supportConversations).orderBy(desc(supportConversations.lastMessageAt)).limit(50);return rows}
 async respond(input:{conversationId:string;message:string;locale?:string;forceHuman?:boolean}){const db=getDb();const conv=(await db.select().from(supportConversations).where(eq(supportConversations.id,input.conversationId)).limit(1))[0];if(!conv)throw new Error("SUPPORT_CONVERSATION_NOT_FOUND");const locale=loc(input.locale||conv.locale);const intent=input.forceHuman?"human":intentOf(input.message);if(input.message.trim())await db.insert(supportMessages).values({conversationId:conv.id,senderRole:"user",body:input.message.trim(),intent});let text=answer[locale][intent]||answer[locale].general;const code=(input.message.match(/\bZX[-A-Z0-9]{2,}\b/i)||[])[0];let orderContext:any=null;if(code){orderContext=(await db.select({requestCode:serviceRequests.requestCode,status:serviceRequests.status,title:serviceRequests.title,addressText:serviceRequests.addressText,details:serviceRequests.details}).from(serviceRequests).where(eq(serviceRequests.requestCode,code.toUpperCase())).limit(1))[0];if(orderContext)text+=locale.startsWith("zh")?`\n\n订单 ${orderContext.requestCode}：${orderContext.status} · ${orderContext.title}`:locale==="en-US"?`\n\nOrder ${orderContext.requestCode}: ${orderContext.status} · ${orderContext.title}`:`\n\nĐơn ${orderContext.requestCode}: ${orderContext.status} · ${orderContext.title}`}
 if(intent!=="human"){const external=await externalAssist({message:input.message,locale,role:conv.role,intent,order:orderContext});if(external)text=external}
 await db.insert(supportMessages).values({conversationId:conv.id,senderRole:intent==="human"?"system":"assistant",body:text,intent,metadata:{provider:process.env.ZHAOXI_AI_ASSIST_URL?"external_or_fallback":"zhaoxi_fallback"}});await db.update(supportConversations).set({status:intent==="human"?"escalated":conv.status,lastMessageAt:new Date(),updatedAt:new Date()}).where(eq(supportConversations.id,conv.id));return {conversation: {...conv,status:intent==="human"?"escalated":conv.status},messages:await this.messages(conv.id)}}
}
export const supportService=new SupportService();
