import{and,desc,eq}from"drizzle-orm";import{getDb}from"@/db";import{customerSupportThreads,operationsAuditLogs,supportAutomationRules,supportInternalNotes,supportMacros,supportTags,supportThreadEvents,supportThreadTags,users}from"@/db/schema";
class SupportCrmService{
 async workspace(threadId:string){const db=getDb();const thread=(await db.select().from(customerSupportThreads).where(eq(customerSupportThreads.id,threadId)).limit(1))[0];if(!thread)throw new Error("SUPPORT_THREAD_NOT_FOUND");const[tagLinks,notes,macros,rules,tags]=await Promise.all([db.select({id:supportTags.id,name:supportTags.name,color:supportTags.color}).from(supportThreadTags).innerJoin(supportTags,eq(supportThreadTags.tagId,supportTags.id)).where(eq(supportThreadTags.threadId,threadId)),db.select({id:supportInternalNotes.id,body:supportInternalNotes.body,createdAt:supportInternalNotes.createdAt,authorId:supportInternalNotes.authorAdminUserId,authorName:users.nickname}).from(supportInternalNotes).leftJoin(users,eq(users.id,supportInternalNotes.authorAdminUserId)).where(eq(supportInternalNotes.threadId,threadId)).orderBy(desc(supportInternalNotes.createdAt)),db.select().from(supportMacros).where(eq(supportMacros.isActive,true)).orderBy(desc(supportMacros.updatedAt)),db.select().from(supportAutomationRules).where(eq(supportAutomationRules.isEnabled,true)),db.select().from(supportTags).where(eq(supportTags.isActive,true))]);return{thread,tags:tagLinks,availableTags:tags,notes,macros,rules,financialAuthority:false,partnerFundsAuthority:false}}
 async addNote(actorId:string,threadId:string,body:string){body=String(body||"").trim();if(!body)throw new Error("NOTE_REQUIRED");const db=getDb(),row=(await db.insert(supportInternalNotes).values({threadId,authorAdminUserId:actorId,body:body.slice(0,4000)}).returning())[0];await this.audit(actorId,"internal_note",threadId,{noteId:row.id});return row}
 async tag(actorId:string,threadId:string,tagId:string,enabled:boolean){const db=getDb();if(enabled)await db.insert(supportThreadTags).values({threadId,tagId,createdByUserId:actorId}).onConflictDoNothing();else await db.delete(supportThreadTags).where(and(eq(supportThreadTags.threadId,threadId),eq(supportThreadTags.tagId,tagId)));await this.audit(actorId,enabled?"tag_added":"tag_removed",threadId,{tagId});return this.workspace(threadId)}
 async createMacro(actorId:string,input:any){const title=String(input.title||"").trim(),body=String(input.body||"").trim();if(!title||!body)throw new Error("MACRO_FIELDS_REQUIRED");return(await getDb().insert(supportMacros).values({title:title.slice(0,120),body:body.slice(0,4000),locale:String(input.locale||"vi-VN"),category:String(input.category||"general"),createdByUserId:actorId}).returning())[0]}
 async upsertRule(actorId:string,input:any){const db=getDb(),values={name:String(input.name||"").trim().slice(0,120),trigger:String(input.trigger||"").trim().slice(0,60),conditions:(input.conditions||{}) as Record<string,unknown>,actions:(input.actions||{}) as Record<string,unknown>,isEnabled:input.isEnabled!==false,createdByUserId:actorId,updatedAt:new Date()};if(!values.name||!values.trigger)throw new Error("RULE_FIELDS_REQUIRED");const row=input.id?(await db.update(supportAutomationRules).set(values).where(eq(supportAutomationRules.id,String(input.id))).returning())[0]:(await db.insert(supportAutomationRules).values(values).returning())[0];await this.audit(actorId,"automation_rule_saved",row.id,{trigger:row.trigger});return row}
 async automationContext(threadId:string,trigger:string){const db=getDb(),rules=await db.select().from(supportAutomationRules).where(and(eq(supportAutomationRules.trigger,trigger),eq(supportAutomationRules.isEnabled,true)));return{threadId,trigger,rules:rules.map((r:typeof rules[number])=>({id:r.id,name:r.name,conditions:r.conditions,actions:r.actions})),executionMode:"recommendation_only",automaticFinancialActions:false}}
 private async audit(actorId:string,action:string,targetId:string,metadata:Record<string,unknown>){await getDb().insert(operationsAuditLogs).values({actorType:"admin",actorUserId:actorId,area:"support_crm",action,targetType:"support_thread",targetId,metadata})}
}export const supportCrmService=new SupportCrmService();