import {eq} from "drizzle-orm";
import {getDb} from "@/db";
import {operationsAuditLogs,organizationMembers,organizations,serviceRequests} from "@/db/schema";

export type TravelPlatformFeePolicy={enabled:boolean;mode:"percentage"|"fixed"|"hybrid";percentageBps:number;fixedPerBooking:number;minimumFee:number;maximumFee:number;note:string;updatedAt?:string;updatedByUserId?:string};
function n(v:unknown,min=0,max=1_000_000_000){const x=Number(v);return Number.isFinite(x)?Math.max(min,Math.min(max,Math.round(x))):0}
function details(r:any){return(r.details||{}) as Record<string,unknown>}
function meta(r:any){return(r.metadata||{}) as Record<string,unknown>}
export class TravelPlatformFeeService{
 async authorizePartner(userId:string,organizationId:string){const m=(await getDb().select().from(organizationMembers).where(eq(organizationMembers.organizationId,organizationId))).find(x=>x.userId===userId&&x.isActive);if(!m)throw new Error("PARTNER_FORBIDDEN")}
 normalize(v:unknown):TravelPlatformFeePolicy{const x=(v&&typeof v==="object"?v:{}) as Record<string,unknown>,mode=["percentage","fixed","hybrid"].includes(String(x.mode))?String(x.mode) as TravelPlatformFeePolicy["mode"]:"percentage";return{enabled:x.enabled===true,mode,percentageBps:n(x.percentageBps,0,10000),fixedPerBooking:n(x.fixedPerBooking),minimumFee:n(x.minimumFee),maximumFee:n(x.maximumFee),note:String(x.note||"").trim().slice(0,500),updatedAt:x.updatedAt?String(x.updatedAt):undefined,updatedByUserId:x.updatedByUserId?String(x.updatedByUserId):undefined}}
 async resolve(organizationId:string){const org=(await getDb().select().from(organizations).where(eq(organizations.id,organizationId)).limit(1))[0];if(!org)throw new Error("ORGANIZATION_NOT_FOUND");return this.normalize(meta(org).travelPlatformFeePolicy)}
 calculate(policy:TravelPlatformFeePolicy,quotedAmount:number){if(!policy.enabled)return 0;const base=Math.max(0,Math.round(Number(quotedAmount)||0)),percent=Math.round(base*policy.percentageBps/10000);let fee=policy.mode==="fixed"?policy.fixedPerBooking:policy.mode==="hybrid"?percent+policy.fixedPerBooking:percent;if(policy.minimumFee>0)fee=Math.max(fee,policy.minimumFee);if(policy.maximumFee>0)fee=Math.min(fee,policy.maximumFee);return Math.max(0,Math.round(fee))}
 async update(adminUserId:string,organizationId:string,input:unknown){const db=getDb(),org=(await db.select().from(organizations).where(eq(organizations.id,organizationId)).limit(1))[0];if(!org)throw new Error("ORGANIZATION_NOT_FOUND");const before=meta(org),raw=(input&&typeof input==="object"?input:{}) as Record<string,unknown>,now=new Date().toISOString(),policy=this.normalize({...raw,updatedAt:now,updatedByUserId:adminUserId});const[next]=await db.update(organizations).set({metadata:{...before,travelPlatformFeePolicy:policy},updatedAt:new Date()}).where(eq(organizations.id,organizationId)).returning();await db.insert(operationsAuditLogs).values({actorUserId:adminUserId,area:"travel_platform_fee_policy",action:"update",targetType:"organization",targetId:organizationId,beforeState:{travelPlatformFeePolicy:before.travelPlatformFeePolicy||null},afterState:{travelPlatformFeePolicy:policy},metadata:{directPaymentToPartner:true}});return{organizationId,policy,organization:next}}
 async ledger(organizationId?:string){const db=getDb(),rows=organizationId?await db.select().from(serviceRequests).where(eq(serviceRequests.assignedOrganizationId,organizationId)):await db.select().from(serviceRequests);const travel=rows.filter(r=>details(r).inquiryType==="travel_experience_inquiry"&&details(r).travelPlatformFeeSnapshot);const entries=travel.map(r=>{const d=details(r),snap=(d.travelPlatformFeeSnapshot||{}) as Record<string,unknown>;return{requestId:r.id,requestCode:r.requestCode,organizationId:r.assignedOrganizationId,stage:String(d.travelBookingStage||"requested"),quotedAmount:n(d.quotedAmount),platformFee:n(snap.platformFee),feeStatus:String(d.travelPlatformFeeStatus||"not_due"),policy:snap.policy||{},confirmedAt:d.confirmedAt||null,completedAt:d.travelCompletedAt||null,feePaidAt:d.travelPlatformFeePaidAt||null}}).sort((a,b)=>b.requestCode.localeCompare(a.requestCode));return{entries,summary:{bookingCount:entries.length,quotedAmount:entries.reduce((a,x)=>a+x.quotedAmount,0),platformFeeAccrued:entries.filter(x=>["accrued","due","paid"].includes(x.feeStatus)).reduce((a,x)=>a+x.platformFee,0),platformFeeDue:entries.filter(x=>x.feeStatus==="due").reduce((a,x)=>a+x.platformFee,0),platformFeePaid:entries.filter(x=>x.feeStatus==="paid").reduce((a,x)=>a+x.platformFee,0)}}}
 async adminOverview(){const orgs=await getDb().select().from(organizations);const rows=[];for(const org of orgs){const policy=this.normalize(meta(org).travelPlatformFeePolicy),ledger=await this.ledger(org.id);if(policy.enabled||ledger.entries.length)rows.push({organization:{id:org.id,code:org.code,name:org.name,status:org.status},policy,ledger})}return rows}
 async partnerOverview(userId:string,organizationId:string){await this.authorizePartner(userId,organizationId);const org=(await getDb().select().from(organizations).where(eq(organizations.id,organizationId)).limit(1))[0];if(!org)throw new Error("ORGANIZATION_NOT_FOUND");return{organization:{id:org.id,code:org.code,name:org.name},policy:this.normalize(meta(org).travelPlatformFeePolicy),ledger:await this.ledger(organizationId),paymentRouting:"direct_to_partner",platformDoesNotHoldCustomerFunds:true}}
 async markPaid(adminUserId:string,requestId:string){const db=getDb(),row=(await db.select().from(serviceRequests).where(eq(serviceRequests.id,requestId)).limit(1))[0];if(!row)throw new Error("TRAVEL_BOOKING_NOT_FOUND");const d=details(row);if(d.inquiryType!=="travel_experience_inquiry"||d.travelPlatformFeeStatus!=="due")throw new Error("TRAVEL_PLATFORM_FEE_NOT_DUE");const now=new Date().toISOString(),next={...d,travelPlatformFeeStatus:"paid",travelPlatformFeePaidAt:now,travelPlatformFeePaidBy:adminUserId};const[u]=await db.update(serviceRequests).set({details:next,updatedAt:new Date()}).where(eq(serviceRequests.id,requestId)).returning();await db.insert(operationsAuditLogs).values({actorUserId:adminUserId,area:"travel_platform_fee_ledger",action:"paid",targetType:"service_request",targetId:requestId,beforeState:{travelPlatformFeeStatus:d.travelPlatformFeeStatus},afterState:{travelPlatformFeeStatus:"paid",travelPlatformFeePaidAt:now},metadata:{organizationId:row.assignedOrganizationId,directPaymentToPartner:true}});return u}
}
export const travelPlatformFeeService=new TravelPlatformFeeService();
