import {and,asc,eq} from "drizzle-orm";
import {getDb} from "@/db";
import {modules,operationsAuditLogs,organizationMembers,services,serviceTranslations} from "@/db/schema";

type PackageInput={id?:string;name?:string;pricingMode?:string;adultPrice?:number|string;childPrice?:number|string;groupPrice?:number|string;surchargePerBooking?:number|string;minGuests?:number|string;maxGuests?:number|string;isEnabled?:boolean};
type Input={organizationId?:string;locale?:string;name?:string;summary?:string;description?:string;price?:number|string;currency?:string;isPublished?:boolean;experienceType?:string;destination?:string;duration?:string;departurePoint?:string;maxGuests?:number|string;serviceLanguage?:string;availableDays?:string|string[];startTimes?:string|string[];bookingNoticeHours?:number|string;travelAvailabilityStatus?:string;includes?:string|string[];excludes?:string|string[];blackoutDates?:string|string[];imageUrl?:string;galleryUrls?:string[];packages?:PackageInput[]};
const locales=["zh-CN","zh-TW","vi-VN","en-US"];
function clean(v:unknown,max=1000){return String(v||"").trim().slice(0,max)}
function num(v:unknown,min=0,max=1e9){const n=Number(v);return Number.isFinite(n)?Math.max(min,Math.min(max,n)):0}
function arr(v:unknown,max=100){return(Array.isArray(v)?v.map(String):String(v||"").split(/[,;\n]/)).map(x=>x.trim()).filter(Boolean).slice(0,max)}
function dates(v:unknown){return arr(v,180).filter(x=>/^\d{4}-\d{2}-\d{2}$/.test(x))}
function packages(v:unknown):any[]{if(!Array.isArray(v))return[];return v.slice(0,20).map((x:any)=>({id:clean(x.id,64)||crypto.randomUUID(),name:clean(x.name,120)||"Package",pricingMode:["per_person","group"].includes(String(x.pricingMode))?String(x.pricingMode):"per_person",adultPrice:num(x.adultPrice),childPrice:num(x.childPrice),groupPrice:num(x.groupPrice),surchargePerBooking:num(x.surchargePerBooking),minGuests:Math.max(1,Math.round(num(x.minGuests,1,100))),maxGuests:Math.max(1,Math.round(num(x.maxGuests,1,100))),isEnabled:x.isEnabled!==false})).map(x=>({...x,maxGuests:Math.max(x.minGuests,x.maxGuests)}))}
export class TravelInventoryService{
 async authorize(userId:string,org:string){const m=(await getDb().select().from(organizationMembers).where(and(eq(organizationMembers.userId,userId),eq(organizationMembers.organizationId,org),eq(organizationMembers.isActive,true))).limit(1))[0];if(!m)throw new Error("PARTNER_FORBIDDEN")}
 async list(userId:string,org:string,locale="zh-CN"){await this.authorize(userId,org);const loc=locales.includes(locale)?locale:"zh-CN";return getDb().select({id:services.id,code:services.code,priceFrom:services.priceFrom,currency:services.currency,isEnabled:services.isEnabled,metadata:services.metadata,name:serviceTranslations.name,summary:serviceTranslations.summary,description:serviceTranslations.description}).from(services).innerJoin(modules,eq(services.moduleId,modules.id)).leftJoin(serviceTranslations,and(eq(serviceTranslations.serviceId,services.id),eq(serviceTranslations.locale,loc))).where(and(eq(modules.code,"travel"),eq(services.organizationId,org))).orderBy(asc(services.createdAt))}
 private meta(input:Input,current:Record<string,unknown>={}){const has=(k:keyof Input)=>Object.prototype.hasOwnProperty.call(input,k);const currentPackages=Array.isArray(current.travelPackages)?current.travelPackages.filter(x=>x&&typeof x==="object") as any[]:[];let nextPackages:any[]=currentPackages;if(has("packages")){nextPackages=packages(input.packages).map(p=>{const old=currentPackages.find(x=>String(x.id||"")===String(p.id||""));if(old?.adminHidden===true&&p.isEnabled!==false)throw new Error("TRAVEL_PACKAGE_ADMIN_HIDDEN");return{...p,adminHidden:old?.adminHidden===true,adminVerified:old?.adminVerified===true,adminReviewNote:old?.adminReviewNote||"",adminReviewedAt:old?.adminReviewedAt||null,adminReviewedBy:old?.adminReviewedBy||null}})}return{...current,experienceType:has("experienceType")?clean(input.experienceType,80):current.experienceType||"",destination:has("destination")?clean(input.destination,120):current.destination||"",duration:has("duration")?clean(input.duration,80):current.duration||"",departurePoint:has("departurePoint")?clean(input.departurePoint,300):current.departurePoint||"",maxGuests:has("maxGuests")?Math.max(1,Math.round(num(input.maxGuests,1,500))):Number(current.maxGuests||20),serviceLanguage:has("serviceLanguage")?clean(input.serviceLanguage,200):current.serviceLanguage||"",availableDays:has("availableDays")?arr(input.availableDays,7):current.availableDays||[],startTimes:has("startTimes")?arr(input.startTimes,20):current.startTimes||[],bookingNoticeHours:has("bookingNoticeHours")?num(input.bookingNoticeHours,0,720):Number(current.bookingNoticeHours||0),travelAvailabilityStatus:has("travelAvailabilityStatus")&&String(input.travelAvailabilityStatus)==="unavailable"?"unavailable":"available",includes:has("includes")?arr(input.includes,100):current.includes||[],excludes:has("excludes")?arr(input.excludes,100):current.excludes||[],blackoutDates:has("blackoutDates")?dates(input.blackoutDates):current.blackoutDates||[],imageUrl:has("imageUrl")?clean(input.imageUrl,2000):current.imageUrl||"",galleryUrls:has("galleryUrls")&&Array.isArray(input.galleryUrls)?input.galleryUrls.map(x=>clean(x,2000)).filter(Boolean).slice(0,20):current.galleryUrls||[],travelPackages:nextPackages,travelInventoryUpdatedAt:new Date().toISOString()}}
 async create(userId:string,input:Input){const org=clean(input.organizationId,64);await this.authorize(userId,org);const db=getDb(),module=(await db.select().from(modules).where(eq(modules.code,"travel")).limit(1))[0];if(!module)throw new Error("TRAVEL_MODULE_UNAVAILABLE");const name=clean(input.name,160);if(!name)throw new Error("TRAVEL_NAME_REQUIRED");const meta=this.meta(input,{}),pkgs=meta.travelPackages as any[];const price=pkgs.filter(x=>x.isEnabled).map(x=>x.pricingMode==="group"?x.groupPrice:x.adultPrice).filter(x=>x>0);const priceFrom=price.length?Math.min(...price):num(input.price);const[row]=await db.insert(services).values({moduleId:module.id,organizationId:org,code:`ZX-TRAVEL-${Date.now()}-${crypto.randomUUID().slice(0,6).toUpperCase()}`,priceFrom:String(Math.round(priceFrom)),currency:clean(input.currency,3)||"VND",isEnabled:input.isPublished===true,metadata:{...meta,syncStatus:input.isPublished===true?"published":"draft"}}).returning();await db.insert(serviceTranslations).values({serviceId:row.id,locale:locales.includes(String(input.locale))?String(input.locale):"zh-CN",name,summary:clean(input.summary,1000)||null,description:clean(input.description,5000)||null});await db.insert(operationsAuditLogs).values({actorUserId:userId,area:"travel_inventory",action:"create",targetType:"service",targetId:row.id,afterState:{metadata:row.metadata,isEnabled:row.isEnabled},metadata:{organizationId:org}});return row}
 async update(userId:string,id:string,input:Input){const db=getDb(),row=(await db.select().from(services).where(eq(services.id,id)).limit(1))[0];if(!row||!row.organizationId)throw new Error("TRAVEL_EXPERIENCE_NOT_FOUND");await this.authorize(userId,row.organizationId);const module=(await db.select().from(modules).where(eq(modules.id,row.moduleId)).limit(1))[0];if(module?.code!=="travel")throw new Error("TRAVEL_EXPERIENCE_NOT_FOUND");const current=(row.metadata||{}) as Record<string,unknown>;if(input.isPublished===true&&current.travelAdminHidden===true)throw new Error("TRAVEL_EXPERIENCE_ADMIN_HIDDEN");const meta=this.meta(input,current),pkgs=meta.travelPackages as any[],prices=pkgs.filter(x=>x.isEnabled&&!x.adminHidden).map(x=>x.pricingMode==="group"?x.groupPrice:x.adultPrice).filter(x=>x>0),priceFrom=prices.length?Math.min(...prices):Number(row.priceFrom||0),isEnabled=input.isPublished!==undefined?input.isPublished:row.isEnabled;const[u]=await db.update(services).set({priceFrom:String(Math.round(priceFrom)),currency:clean(input.currency,3)||row.currency,isEnabled,metadata:{...meta,syncStatus:isEnabled?"published":"draft",syncedAt:isEnabled?new Date().toISOString():current.syncedAt||null},updatedAt:new Date()}).where(eq(services.id,id)).returning();const name=clean(input.name,160);if(name)await db.insert(serviceTranslations).values({serviceId:id,locale:locales.includes(String(input.locale))?String(input.locale):"zh-CN",name,summary:clean(input.summary,1000)||null,description:clean(input.description,5000)||null}).onConflictDoUpdate({target:[serviceTranslations.serviceId,serviceTranslations.locale],set:{name,summary:clean(input.summary,1000)||null,description:clean(input.description,5000)||null}});await db.insert(operationsAuditLogs).values({actorUserId:userId,area:"travel_inventory",action:"update",targetType:"service",targetId:id,beforeState:{metadata:row.metadata,isEnabled:row.isEnabled},afterState:{metadata:u.metadata,isEnabled:u.isEnabled},metadata:{organizationId:row.organizationId}});return u}
}
export const travelInventoryService=new TravelInventoryService();
