"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
type Policy={id:string;key:string;name:string;metric:string;comparator:string;threshold:string;severity:string;windowMinutes:number;enabled:boolean;cooldownMinutes:number};
type Incident={id:string;policyKey:string;metric:string;severity:string;status:string;observedValue:string;threshold:string;windowMinutes:number;message:string;releaseVersion?:string|null;createdAt:string};
const metrics=["runtimeErrors","criticalErrors","orderFailureRate","paymentFailureRate","openSupport"];
export default function ReleaseAlertsPage(){
 const[policies,setPolicies]=useState<Policy[]>([]),[incidents,setIncidents]=useState<Incident[]>([]),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState("");
 const[name,setName]=useState(""),[metric,setMetric]=useState("runtimeErrors"),[threshold,setThreshold]=useState("10"),[severity,setSeverity]=useState("warning");
 const load=async()=>{try{const[a,b]=await Promise.all([fetch("/api/platform-release-alerts/policies",{cache:"no-store"}),fetch("/api/platform-release-alerts/incidents",{cache:"no-store"})]);const x=await a.json(),y=await b.json();if(!a.ok||!x?.ok)throw new Error(x?.error?.code||"POLICY_LOAD_FAILED");if(!b.ok||!y?.ok)throw new Error(y?.error?.code||"INCIDENT_LOAD_FAILED");setPolicies(x.data||[]);setIncidents(y.data||[]);setError("")}catch(e){setError(e instanceof Error?e.message:"LOAD_FAILED")}};
 useEffect(()=>{void load()},[]);
 async function evaluate(){setBusy("evaluate");try{const r=await fetch("/api/platform-release-alerts/evaluate",{method:"POST"});const x=await r.json();if(!r.ok||!x?.ok)throw new Error(x?.error?.code||"EVALUATE_FAILED");await load()}catch(e){setError(e instanceof Error?e.message:"EVALUATE_FAILED")}finally{setBusy(null)}}
 async function patchPolicy(row:Policy,body:Partial<Policy>){setBusy(row.id);try{const r=await fetch(`/api/platform-release-alerts/policies/${row.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const x=await r.json();if(!r.ok||!x?.ok)throw new Error(x?.error?.code||"POLICY_UPDATE_FAILED");await load()}catch(e){setError(e instanceof Error?e.message:"POLICY_UPDATE_FAILED")}finally{setBusy(null)}}
 async function createPolicy(){setBusy("create");try{const key=`${metric}-${Date.now()}`;const r=await fetch("/api/platform-release-alerts/policies",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({key,name:name||metric,metric,threshold:Number(threshold),severity,windowMinutes:60,cooldownMinutes:30,enabled:true})});const x=await r.json();if(!r.ok||!x?.ok)throw new Error(x?.error?.code||"POLICY_CREATE_FAILED");setName("");await load()}catch(e){setError(e instanceof Error?e.message:"POLICY_CREATE_FAILED")}finally{setBusy(null)}}
 async function setIncident(id:string,status:string){setBusy(id);try{const r=await fetch(`/api/platform-release-alerts/incidents/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status})});const x=await r.json();if(!r.ok||!x?.ok)throw new Error(x?.error?.code||"INCIDENT_UPDATE_FAILED");await load()}catch(e){setError(e instanceof Error?e.message:"INCIDENT_UPDATE_FAILED")}finally{setBusy(null)}}
 return <main style={{width:"min(100%,600px)",margin:"0 auto",minHeight:"100dvh",padding:18,background:"#f5f7fa",fontFamily:"Inter,Arial,sans-serif"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><Link href="/release-center" style={{textDecoration:"none",color:"#64748b"}}>← Release Center</Link><button onClick={()=>void evaluate()} disabled={busy!==null} style={{border:0,borderRadius:12,padding:"9px 12px",background:"#111827",color:"white",fontWeight:800}}>Evaluate now</button></div><h1 style={{fontSize:24,marginBottom:4}}>SLO Alert Policies</h1><p style={{color:"#64748b",marginTop:0}}>Thresholds → incidents → acknowledge / resolve</p>{error&&<div style={{padding:12,borderRadius:12,background:"#fff1f2",color:"#be123c",marginBottom:12}}>{error}</div>}
 <section style={{padding:16,borderRadius:18,background:"#fff",border:"1px solid #e5e7eb",marginBottom:14}}><b>Create policy</b><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginTop:10}}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Policy name" style={{gridColumn:"1 / -1",padding:10,border:"1px solid #dbe3dd",borderRadius:10}}/><select value={metric} onChange={e=>setMetric(e.target.value)} style={{padding:10,border:"1px solid #dbe3dd",borderRadius:10}}>{metrics.map(m=><option key={m}>{m}</option>)}</select><input value={threshold} onChange={e=>setThreshold(e.target.value)} type="number" style={{padding:10,border:"1px solid #dbe3dd",borderRadius:10}}/><select value={severity} onChange={e=>setSeverity(e.target.value)} style={{padding:10,border:"1px solid #dbe3dd",borderRadius:10}}><option value="warning">warning</option><option value="critical">critical</option></select><button onClick={()=>void createPolicy()} disabled={busy!==null} style={{border:0,borderRadius:10,background:"#07c160",color:"#fff",fontWeight:800}}>Create</button></div></section>
 <section style={{display:"grid",gap:10,marginBottom:14}}>{policies.map(p=><article key={p.id} style={{padding:14,borderRadius:16,background:"#fff",border:"1px solid #e5e7eb"}}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><div><b>{p.name}</b><small style={{display:"block",color:"#64748b"}}>{p.metric} {p.comparator} {p.threshold} · {p.windowMinutes} min · {p.severity}</small></div><button disabled={busy!==null} onClick={()=>void patchPolicy(p,{enabled:!p.enabled})} style={{border:0,borderRadius:999,padding:"7px 10px",background:p.enabled?"#dcfce7":"#f1f5f9",fontWeight:800}}>{p.enabled?"ON":"OFF"}</button></div></article>)}</section>
 <section style={{padding:16,borderRadius:18,background:"#fff",border:"1px solid #e5e7eb"}}><b>Incidents</b><div style={{display:"grid",gap:9,marginTop:10}}>{incidents.length===0?<small style={{color:"#64748b"}}>No release incidents.</small>:incidents.map(i=><article key={i.id} style={{padding:12,borderRadius:12,border:"1px solid #edf0ee",background:i.severity==="critical"?"#fff1f2":"#fffaf0"}}><div style={{display:"flex",justifyContent:"space-between",gap:8}}><b>{i.policyKey}</b><span style={{fontSize:12,fontWeight:900}}>{i.severity.toUpperCase()} · {i.status}</span></div><p style={{fontSize:13,margin:"7px 0"}}>{i.message}</p><small style={{color:"#64748b"}}>{new Date(i.createdAt).toLocaleString()} {i.releaseVersion?`· ${i.releaseVersion}`:""}</small>{i.status==="open"&&<button onClick={()=>void setIncident(i.id,"acknowledged")} disabled={busy!==null} style={{marginTop:8,marginRight:6,border:0,borderRadius:9,padding:"7px 9px",fontWeight:800}}>Acknowledge</button>}{i.status!=="resolved"&&<button onClick={()=>void setIncident(i.id,"resolved")} disabled={busy!==null} style={{marginTop:8,border:0,borderRadius:9,padding:"7px 9px",background:"#dcfce7",color:"#166534",fontWeight:800}}>Resolve</button>}</article>)}</div></section></main>
}