"use client";
import { useEffect, useRef, useState } from "react";
export function useInterval(callback: () => void, delay: number | null) { const saved = useRef(callback); useEffect(() => { saved.current = callback; }, [callback]); useEffect(() => { if (delay === null) return; const id = window.setInterval(() => saved.current(), delay); return () => window.clearInterval(id); }, [delay]); }
/** Poll only while the app is visible. A timeout prevents overlapping slow requests. */
export function useVisiblePolling(callback: () => void | Promise<void>, options: { enabled?: boolean; intervalMs?: number; immediate?: boolean } = {}) {
 const saved=useRef(callback),running=useRef(false);useEffect(()=>{saved.current=callback},[callback]);
 useEffect(()=>{if(options.enabled===false||typeof document==="undefined")return;let disposed=false,timer:number|undefined;const delay=Math.max(1_000,options.intervalMs??30_000);const clear=()=>{if(timer!==undefined)window.clearTimeout(timer);timer=undefined};const schedule=()=>{clear();if(disposed||document.visibilityState!=="visible")return;timer=window.setTimeout(()=>void run(),delay)};const run=async()=>{if(disposed||running.current||document.visibilityState!=="visible")return;running.current=true;try{await saved.current()}finally{running.current=false;schedule()}};const onVisible=()=>{if(document.visibilityState==="visible")void run();else clear()};document.addEventListener("visibilitychange",onVisible);window.addEventListener("focus",onVisible);if(options.immediate!==false)void run();else schedule();return()=>{disposed=true;clear();document.removeEventListener("visibilitychange",onVisible);window.removeEventListener("focus",onVisible)}},[options.enabled,options.intervalMs,options.immediate]);
}
export function useLocalStorageState<T>(key: string, initial: T) { const [value,setValue] = useState<T>(initial); useEffect(() => { try { const raw=window.localStorage.getItem(key); if(raw!==null)setValue(JSON.parse(raw) as T); } catch {} },[key]); const save=(next:T)=>{setValue(next);try{window.localStorage.setItem(key,JSON.stringify(next));}catch{}}; return [value,save] as const; }
