import { and, eq } from "drizzle-orm";
import { getDb } from "@/db";
import { mediaAssets } from "@/db/schema";
import { errorResponse, json } from "@/lib/api";
import { services } from "@/db/schema";
import { mayManageOrganization, requireSession } from "@/lib/security/route-authorization";
export const dynamic="force-dynamic"; type Context={params:Promise<{id:string}>};
export async function PATCH(request:Request,context:Context){try{const gate=await requireSession(request,["admin","partner"]);if(!gate.ok)return gate.response;const {id}=await context.params;const body=await request.json() as {organizationId?:string;serviceId?:string|null;sortOrder?:number;isPublished?:boolean;metadata?:Record<string,unknown>};const [current]=await getDb().select().from(mediaAssets).where(eq(mediaAssets.id,id)).limit(1);if(!current||!(await mayManageOrganization(gate.session,current.organizationId)))return errorResponse("Media not found.",404);if(body.organizationId&&body.organizationId!==current.organizationId)return errorResponse("Media not found.",404);if(body.serviceId){const [service]=await getDb().select({organizationId:services.organizationId}).from(services).where(eq(services.id,body.serviceId)).limit(1);if(!service||service.organizationId!==current.organizationId)return errorResponse("Service does not belong to organization.",403)}const [updated]=await getDb().update(mediaAssets).set({serviceId:body.serviceId===undefined?current.serviceId:body.serviceId,sortOrder:body.sortOrder??current.sortOrder,isPublished:body.isPublished??current.isPublished,metadata:body.metadata?{...(current.metadata||{}),...body.metadata}:current.metadata,updatedAt:new Date()}).where(and(eq(mediaAssets.id,id),eq(mediaAssets.organizationId,current.organizationId))).returning();return json({ok:true,data:updated})}catch(error){console.error(error);return errorResponse("Unable to update media.",500)}}
export async function DELETE(request:Request,context:Context){try{const gate=await requireSession(request,["admin","partner"]);if(!gate.ok)return gate.response;const {id}=await context.params;const organizationId=new URL(request.url).searchParams.get("organizationId");const [current]=await getDb().select().from(mediaAssets).where(eq(mediaAssets.id,id)).limit(1);if(!current||!(await mayManageOrganization(gate.session,current.organizationId)))return errorResponse("Media not found.",404);if(organizationId&&organizationId!==current.organizationId)return errorResponse("Media not found.",404);const [deleted]=await getDb().delete(mediaAssets).where(and(eq(mediaAssets.id,id),eq(mediaAssets.organizationId,current.organizationId))).returning();if(!deleted)return errorResponse("Media not found.",404);return json({ok:true,data:deleted})}catch(error){console.error(error);return errorResponse("Unable to delete media.",500)}}
