import { StyleSheet } from "react-native";

export const C = { ink: "#202522", muted: "#68706b", green: "#07c160", dark: "#173f32", mint: "#eaf8f0", line: "#dbe9e1", white: "#ffffff", red: "#c93645", amber: "#b66b08", bg: "#f5f6f5" };

export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: C.bg }, flex: { flex: 1 }, page: { padding: 18, paddingBottom: 38 },
  hero: { backgroundColor: C.dark, padding: 20, borderRadius: 26, marginBottom: 16, overflow: "hidden" },
  webHeader: { backgroundColor: C.white, paddingHorizontal: 18, paddingVertical: 14, flexDirection: "row", alignItems: "center", justifyContent: "space-between", shadowColor: "#173c2c", shadowOpacity: 0.08, shadowRadius: 14, shadowOffset: { width: 0, height: 5 }, elevation: 3 }, brandMark: { width: 48, height: 48, borderRadius: 16 }, brandName: { color: C.ink, fontSize: 20, fontWeight: "900", letterSpacing: 1.2 }, brandSub: { color: C.muted, fontSize: 13, marginTop: 2 }, headerActions: { flexDirection: "row", gap: 8 }, headerAction: { width: 52, height: 52, borderRadius: 17, alignItems: "center", justifyContent: "center", backgroundColor: C.white, shadowColor: "#173c2c", shadowOpacity: 0.1, shadowRadius: 10, shadowOffset: { width: 0, height: 3 }, elevation: 2 }, webNav: { backgroundColor: C.white, borderRadius: 22, marginHorizontal: 18, marginTop: 10, padding: 5, shadowColor: "#173c2c", shadowOpacity: 0.06, shadowRadius: 12, shadowOffset: { width: 0, height: 3 }, elevation: 2 }, webNavItem: { paddingHorizontal: 17, paddingVertical: 13, borderRadius: 16 }, webNavActive: { backgroundColor: C.mint }, webNavText: { color: C.ink, fontSize: 14, fontWeight: "800" }, webSection: { color: C.ink, fontSize: 24, fontWeight: "900", marginBottom: 12 },
  eyebrow: { color: "#89ddb2", fontSize: 12, fontWeight: "800", letterSpacing: 1.2 },
  heroTitle: { color: C.white, fontSize: 25, fontWeight: "900", marginTop: 5 },
  heroSub: { color: "#c3ded0", fontSize: 13, marginTop: 5 },
  row: { flexDirection: "row", alignItems: "center" }, between: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  statusDot: { width: 9, height: 9, borderRadius: 8, backgroundColor: "#43db8e", marginRight: 7 },
  stats: { flexDirection: "row", gap: 9, marginBottom: 18 }, stat: { flex: 1, backgroundColor: C.white, borderRadius: 18, padding: 14, borderWidth: 2, borderColor: "transparent", shadowColor: "#173c2c", shadowOpacity: 0.07, shadowRadius: 14, shadowOffset: { width: 0, height: 5 }, elevation: 2 },
  statActive: { borderColor: C.green, backgroundColor: "#f0fdf4", shadowColor: C.green, shadowOpacity: 0.2, shadowRadius: 12 },
  statAlert: { borderColor: C.red, backgroundColor: "#fef2f2", shadowColor: C.red, shadowOpacity: 0.2, shadowRadius: 12 },
  segment: { flexDirection: "row", gap: 7, backgroundColor: "#eaf0ed", borderRadius: 16, padding: 4, marginBottom: 18 }, segmentButton: { flex: 1, minHeight: 43, borderRadius: 12, alignItems: "center", justifyContent: "center" }, segmentOn: { backgroundColor: C.white, shadowColor: "#173c2c", shadowOpacity: 0.08, shadowRadius: 8, shadowOffset: { width: 0, height: 2 }, elevation: 2 }, segmentText: { color: C.muted, fontWeight: "900" }, segmentTextOn: { color: C.green },
  historyFilter: { flexDirection: "row", gap: 8, marginTop: -7, marginBottom: 16 }, historyFilterButton: { flex: 1, minHeight: 36, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: "#edf3ef" }, historyFilterOn: { backgroundColor: C.mint }, historyFilterText: { color: C.muted, fontSize: 12, fontWeight: "900" }, historyFilterTextOn: { color: C.green },
  statNumber: { fontSize: 24, color: C.ink, fontWeight: "900" }, statNumberActive: { color: C.green }, statLabel: { color: C.muted, fontSize: 11, fontWeight: "700", marginTop: 3 }, statLabelActive: { color: C.green, fontWeight: "900" },
  sectionTitle: { color: C.ink, fontSize: 19, fontWeight: "900", marginBottom: 10 },
  card: { backgroundColor: C.white, borderRadius: 20, padding: 15, marginBottom: 10, shadowColor: "#173c2c", shadowOpacity: 0.075, shadowRadius: 16, shadowOffset: { width: 0, height: 6 }, elevation: 2 },
  storeRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10, paddingVertical: 12 }, storeName: { color: C.ink, fontSize: 15, fontWeight: "800", flex: 1 }, storeActive: { color: C.green, fontSize: 12, fontWeight: "900" },
  cardLate: { backgroundColor: "#fffafb", shadowColor: "#c93645", shadowOpacity: 0.13 }, code: { color: C.green, fontWeight: "900", fontSize: 16 },
  pill: { borderRadius: 999, paddingHorizontal: 9, paddingVertical: 5, backgroundColor: C.mint }, pillText: { color: C.green, fontSize: 11, fontWeight: "900" },
  providerBadge: { flexDirection: "row", alignItems: "center", alignSelf: "flex-start", gap: 7, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6, backgroundColor: "#ccfbf1", marginTop: 5 }, providerLogo: { width: 42, height: 18, resizeMode: "contain" }, providerText: { color: "#0f766e", fontSize: 12, fontWeight: "900" }, priorityRow: { flexDirection: "row", gap: 7, marginTop: 10 }, priorityButton: { flex: 1, paddingVertical: 9, alignItems: "center", borderRadius: 12, backgroundColor: "#f1f5f9" }, priorityOn: { backgroundColor: C.mint }, priorityUrgentOn: { backgroundColor: "#fee2e2" }, priorityText: { color: "#64748b", fontSize: 12, fontWeight: "900" }, priorityTextOn: { color: "#067647" }, priorityUrgentTextOn: { color: "#b91c1c" }, etaSelect: { marginTop: 9, backgroundColor: "#f5f8f6", borderRadius: 14, padding: 12 },
  externalBadge: { alignSelf: "flex-start", borderRadius: 999, paddingHorizontal: 12, paddingVertical: 7, backgroundColor: C.mint, marginTop: 8 }, externalBadgeText: { color: "#087f4e", fontSize: 13, fontWeight: "900" },
  phoneBadge: { flexDirection: "row", alignItems: "center", gap: 5, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6, backgroundColor: C.mint }, phoneText: { color: C.green, fontWeight: "900", fontSize: 12 },
  detailGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 12, paddingTop: 12, borderTopWidth: 1, borderTopColor: "#edf1ef" }, detailTile: { width: "47%", minHeight: 62, padding: 11, borderRadius: 16, backgroundColor: "#f5f8f6" }, detailLabel: { color: C.muted, fontSize: 12 }, detailValue: { color: C.ink, fontSize: 15, fontWeight: "900", marginTop: 4 }, detailValueGreen: { color: C.green },
  itemName: { color: C.ink, fontSize: 17, fontWeight: "900", marginTop: 10 }, meta: { color: C.muted, fontSize: 13, marginTop: 5, lineHeight: 19 },
  money: { color: C.green, fontWeight: "900", fontSize: 15, marginTop: 8 },
  button: { minHeight: 48, borderRadius: 15, alignItems: "center", justifyContent: "center", paddingHorizontal: 16 }, buttonGreen: { backgroundColor: C.green, shadowColor: C.green, shadowOpacity: 0.2, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 3 }, buttonRed: { backgroundColor: "#fff0f1" }, buttonGhost: { backgroundColor: "#eef3f0" },
  buttonText: { color: C.white, fontWeight: "900", fontSize: 15 }, buttonRedText: { color: C.red, fontWeight: "900" }, buttonGhostText: { color: C.ink, fontWeight: "900" },
  empty: { alignItems: "center", padding: 38, backgroundColor: C.white, borderRadius: 22, shadowColor: "#173c2c", shadowOpacity: 0.06, shadowRadius: 15, shadowOffset: { width: 0, height: 5 }, elevation: 2 }, emptyTitle: { color: C.ink, fontSize: 17, fontWeight: "900", marginTop: 10 }, emptyText: { color: C.muted, textAlign: "center", marginTop: 5 },
  login: { flex: 1, backgroundColor: C.dark }, loginScroll: { flexGrow: 1, justifyContent: "center", padding: 24, paddingVertical: 32 }, loginCard: { backgroundColor: C.white, borderRadius: 28, padding: 24, shadowColor: "#001d12", shadowOpacity: 0.2, shadowRadius: 28, shadowOffset: { width: 0, height: 12 }, elevation: 8 }, logo: { width: 64, height: 64, borderRadius: 18, marginBottom: 18 }, loginTitle: { color: C.ink, fontSize: 27, fontWeight: "900" }, loginSub: { color: C.muted, lineHeight: 20, marginTop: 5, marginBottom: 22 },
  label: { color: C.ink, fontWeight: "800", fontSize: 13, marginBottom: 7 }, input: { height: 52, borderWidth: 0, borderRadius: 15, paddingHorizontal: 15, color: C.ink, backgroundColor: "#f1f6f3", marginBottom: 15 }, error: { color: C.red, backgroundColor: "#fff0f1", padding: 11, borderRadius: 12, marginBottom: 13, lineHeight: 18 },
  loginTabs: { flexDirection: "row", padding: 4, borderRadius: 14, backgroundColor: "#edf3ef", marginBottom: 18 }, loginTab: { flex: 1, minHeight: 40, borderRadius: 11, alignItems: "center", justifyContent: "center" }, loginTabOn: { backgroundColor: C.white }, loginTabText: { color: C.muted, fontWeight: "800" }, loginTabTextOn: { color: C.green },
  phoneRow: { flexDirection: "row", gap: 8 }, dialCode: { height: 52, minWidth: 96, borderWidth: 0, borderRadius: 15, alignItems: "center", justifyContent: "center", backgroundColor: C.mint }, dialCodeText: { color: C.ink, fontWeight: "900" }, phoneInput: { flex: 1 }, loginHint: { color: C.muted, fontSize: 12, marginTop: -7, marginBottom: 15, lineHeight: 17 },
  modalBackdrop: { flex: 1, backgroundColor: "rgba(3,24,16,.52)", justifyContent: "flex-end" }, modal: { backgroundColor: C.white, borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: 22, maxHeight: "90%", shadowColor: "#001d12", shadowOpacity: 0.18, shadowRadius: 25, shadowOffset: { width: 0, height: -8 }, elevation: 8 }, centerModalBackdrop: { flex: 1, backgroundColor: "rgba(3,24,16,.56)", justifyContent: "center", alignItems: "center", padding: 18 }, centerModal: { width: "100%", maxHeight: "88%", backgroundColor: C.white, borderRadius: 28, padding: 22, shadowColor: "#001d12", shadowOpacity: 0.25, shadowRadius: 30, shadowOffset: { width: 0, height: 10 }, elevation: 10 }, modalHandle: { width: 44, height: 5, borderRadius: 5, backgroundColor: "#cbd8d1", alignSelf: "center", marginBottom: 18 }, modalTitle: { color: C.ink, fontSize: 24, fontWeight: "900" }, modalGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 15 }, eta: { width: "30%", minWidth: 82, paddingVertical: 12, alignItems: "center", borderRadius: 13, backgroundColor: "#f0f4f2" }, etaOn: { backgroundColor: C.green }, etaText: { color: C.ink, fontWeight: "900" }, etaTextOn: { color: C.white }, actions: { flexDirection: "row", gap: 10, marginTop: 18 },
  confirmBackdrop: { flex: 1, backgroundColor: "rgba(10, 29, 22, .48)", alignItems: "center", justifyContent: "center", padding: 28 }, confirmCard: { width: "100%", backgroundColor: C.white, borderRadius: 26, padding: 24, alignItems: "center", shadowColor: "#001d12", shadowOpacity: 0.25, shadowRadius: 28, shadowOffset: { width: 0, height: 12 }, elevation: 12 }, confirmIcon: { width: 54, height: 54, borderRadius: 27, backgroundColor: C.mint, alignItems: "center", justifyContent: "center", marginBottom: 12 }, confirmTitle: { color: C.ink, fontSize: 21, fontWeight: "900", textAlign: "center" }, confirmText: { color: C.muted, fontSize: 14, textAlign: "center", lineHeight: 20, marginTop: 8, marginBottom: 22 }, confirmActions: { flexDirection: "row", width: "100%", gap: 10 }, confirmCancel: { flex: 1, minHeight: 48, borderRadius: 14, backgroundColor: "#eef3f0", alignItems: "center", justifyContent: "center" }, confirmCancelText: { color: C.muted, fontSize: 15, fontWeight: "900" }, confirmOk: { flex: 1.15, minHeight: 48, borderRadius: 14, backgroundColor: C.green, alignItems: "center", justifyContent: "center" }, confirmDanger: { backgroundColor: C.red }, confirmOkText: { color: C.white, fontSize: 15, fontWeight: "900" },
  successBackdrop: { flex: 1, backgroundColor: "rgba(10, 29, 22, .24)", alignItems: "center", justifyContent: "center", padding: 28 }, successToast: { width: "100%", backgroundColor: C.white, borderRadius: 28, paddingHorizontal: 24, paddingVertical: 28, alignItems: "center", shadowColor: "#001d12", shadowOpacity: 0.24, shadowRadius: 26, shadowOffset: { width: 0, height: 10 }, elevation: 10 }, successBurst: { width: 86, height: 86, alignItems: "center", justifyContent: "center", marginBottom: 10 }, partyPopper: { fontSize: 64 }, successTitle: { color: C.ink, fontSize: 20, fontWeight: "900", textAlign: "center" }, successText: { color: C.green, fontSize: 15, fontWeight: "900", marginTop: 6 },
  tabs: { flexDirection: "row", backgroundColor: C.white, paddingHorizontal: 12, paddingBottom: 7, paddingTop: 6, shadowColor: "#173c2c", shadowOpacity: 0.08, shadowRadius: 12, shadowOffset: { width: 0, height: -4 }, elevation: 5 }, tab: { flex: 1, alignItems: "center", padding: 5 }, tabText: { color: C.muted, fontSize: 11, fontWeight: "800", marginTop: 2 }, tabOn: { color: C.green },
  languageGrid: { flexDirection: "row", gap: 9, marginTop: 12 },
  languageButton: { flex: 1, minHeight: 64, borderRadius: 16, padding: 10, alignItems: "center", justifyContent: "center", borderWidth: 2, borderColor: "#e5ece8", backgroundColor: "#f8faf9" },
  languageButtonActive: { borderColor: C.green, backgroundColor: "#f0fdf4", shadowColor: C.green, shadowOpacity: 0.16, shadowRadius: 8, elevation: 2 },
  languageBadge: { color: "#738078", fontSize: 13, fontWeight: "900", marginBottom: 3 },
  languageBadgeActive: { color: C.green },
  languageText: { color: C.ink, fontSize: 12, fontWeight: "800" },
  languageTextActive: { color: C.green, fontWeight: "900" },

  // Revenue & Analytics (Clean, borderless, soft shadow)
  shadowCard: { backgroundColor: C.white, borderRadius: 20, padding: 18, marginBottom: 14, borderWidth: 0, shadowColor: "#0f172a", shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.06, shadowRadius: 16, elevation: 3 },
  cardHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 12 },
  cardTitle: { color: C.ink, fontSize: 16, fontWeight: "900" },
  cardSub: { color: C.muted, fontSize: 12, marginTop: 2 },
  periodRow: { flexDirection: "row", backgroundColor: "#edf3ef", borderRadius: 14, padding: 4, marginBottom: 14 },
  periodBtn: { flex: 1, minHeight: 36, borderRadius: 11, alignItems: "center", justifyContent: "center" },
  periodBtnOn: { backgroundColor: C.white, shadowColor: "#000", shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.08, shadowRadius: 6, elevation: 2 },
  periodBtnText: { color: C.muted, fontSize: 13, fontWeight: "800" },
  periodBtnTextOn: { color: C.ink, fontWeight: "900" },
  metricHero: { backgroundColor: "#f5f8f6", borderRadius: 16, padding: 16, marginBottom: 12 },
  metricHeroLabel: { color: C.muted, fontSize: 12, fontWeight: "800" },
  metricHeroValue: { color: C.green, fontSize: 26, fontWeight: "900", marginTop: 4 },
  metricGrid: { flexDirection: "row", flexWrap: "wrap", gap: 9 },
  metricBox: { width: "48.3%", backgroundColor: "#f8faf9", borderRadius: 14, padding: 12 },
  metricBoxLabel: { color: C.muted, fontSize: 11, fontWeight: "700" },
  metricBoxValue: { color: C.ink, fontSize: 15, fontWeight: "900", marginTop: 3 },
  chartRow: { flexDirection: "row", alignItems: "flex-end", height: 130, gap: 4, paddingTop: 10 },
  chartCol: { flex: 1, height: "100%", justifyContent: "flex-end", alignItems: "center" },
  chartBar: { width: "100%", borderRadius: 4, backgroundColor: C.green, minHeight: 4 },
  chartLabel: { color: "#94a3b8", fontSize: 9, marginTop: 4 },
  topItemRow: { flexDirection: "row", alignItems: "center", paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: "#f4f7f5" },
  topItemRank: { width: 24, height: 24, borderRadius: 12, backgroundColor: C.mint, alignItems: "center", justifyContent: "center", marginRight: 10 },
  topItemRankText: { color: C.green, fontSize: 12, fontWeight: "900" },
  topItemName: { color: C.ink, fontSize: 14, fontWeight: "800" },
  topItemMeta: { color: C.muted, fontSize: 12, marginTop: 2 },
  topItemRevenue: { color: C.ink, fontSize: 14, fontWeight: "900", marginLeft: "auto" },

  // Store Dropdown Selector
  storeDropdownBtn: { minHeight: 52, borderRadius: 16, backgroundColor: "#eef3f0", flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 16, marginBottom: 10 },
  storeDropdownText: { color: C.ink, fontWeight: "900", fontSize: 14 },
  storeDropdownList: { backgroundColor: C.white, borderRadius: 18, padding: 8, marginBottom: 12, borderWidth: 0, shadowColor: "#0f172a", shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.06, shadowRadius: 14, elevation: 3 },
  storeDropdownItem: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingVertical: 13, paddingHorizontal: 14, borderRadius: 13, marginBottom: 2 },
  storeDropdownItemActive: { backgroundColor: "#f0fdf4" },
  storeDropdownName: { color: C.ink, fontSize: 14, fontWeight: "800" },
  storeDropdownNameActive: { color: C.green, fontWeight: "900" },
  storeDropdownActiveBadge: { backgroundColor: C.mint, paddingHorizontal: 8, paddingVertical: 3, borderRadius: 8, marginRight: 8 },
  storeDropdownActiveText: { color: C.green, fontSize: 11, fontWeight: "900" },
});
