"use client";
import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {useZhaoXiLocale,type ZhaoXiLocale} from "@zhaoxi/i18n";
export type SupportRole="customer"|"partner"|"admin"|"driver";
export type SupportMessage={id:string;senderRole:string;body:string;intent?:string;createdAt:string};
export type SupportConversation={id:string;role:SupportRole;subject:string;status:string;lastMessageAt:string;messages?:SupportMessage[]};
type SupportConfig={basicAssistantEnabled:boolean;paidHumanEnabled:boolean;paidHumanFee:number;paidHumanCurrency:string;emergencyPriority:boolean};
const fallbackConfig:SupportConfig={basicAssistantEnabled:true,paidHumanEnabled:true,paidHumanFee:50000,paidHumanCurrency:"VND",emergencyPriority:true};
const copy={
 "zh-CN":{title:"赵喜助手",hint:"订单、配送、付款、账号与生活服务都可以先问赵喜。",placeholder:"请输入问题…",send:"发送",newChat:"新对话",human:"人工 1对1",paid:"付费",loading:"正在回复…",empty:"您好，我是赵喜助手。请告诉我您需要什么帮助。",error:"暂时无法连接客服，请稍后重试。",basic:"基础帮助由赵喜助手免费提供。"},
 "zh-TW":{title:"趙喜助手",hint:"訂單、配送、付款、帳號與生活服務都可以先問趙喜。",placeholder:"請輸入問題…",send:"傳送",newChat:"新對話",human:"人工 1對1",paid:"付費",loading:"正在回覆…",empty:"您好，我是趙喜助手。請告訴我您需要什麼協助。",error:"暫時無法連線客服，請稍後再試。",basic:"基礎協助由趙喜助手免費提供。"},
 "vi-VN":{title:"Trợ lý ZhaoXi",hint:"Có thể hỏi ZhaoXi trước về đơn hàng, giao hàng, thanh toán, tài khoản và dịch vụ đời sống.",placeholder:"Nhập câu hỏi…",send:"Gửi",newChat:"Cuộc trò chuyện mới",human:"Nhân viên 1-1",paid:"Có phí",loading:"Đang trả lời…",empty:"Xin chào, tôi là Trợ lý ZhaoXi. Hãy cho tôi biết bạn cần hỗ trợ gì.",error:"Tạm thời chưa kết nối được trung tâm hỗ trợ.",basic:"Hỗ trợ cơ bản từ Trợ lý ZhaoXi là miễn phí."},
 "en-US":{title:"ZhaoXi Assistant",hint:"Ask ZhaoXi first about orders, delivery, payments, accounts, and life services.",placeholder:"Type your question…",send:"Send",newChat:"New conversation",human:"1-to-1 staff",paid:"Paid",loading:"Replying…",empty:"Hi, I’m the ZhaoXi Assistant. Tell me what you need help with.",error:"Support is temporarily unavailable.",basic:"Basic help from ZhaoXi Assistant is free."}
} as const;
function money(value:number,currency:string){return `${Math.round(value).toLocaleString("vi-VN")} ${currency}`}
export function SupportCenter({role="customer",initialPrompt,initialConversationId}:{role?:SupportRole;initialPrompt?:string;initialConversationId?:string}){
 const {locale}=useZhaoXiLocale();const t=copy[locale];const[conversationId,setConversationId]=useState(initialConversationId||"");const[messages,setMessages]=useState<SupportMessage[]>([]);const[text,setText]=useState(initialPrompt||"");const[busy,setBusy]=useState(false);const[config,setConfig]=useState<SupportConfig>(fallbackConfig);const end=useRef<HTMLDivElement>(null);
 useEffect(()=>{setText(initialPrompt||"")},[initialPrompt]);
 useEffect(()=>{if(!initialConversationId)return;setConversationId(initialConversationId);fetch(`/api/platform-support?conversationId=${encodeURIComponent(initialConversationId)}`,{cache:"no-store"}).then(r=>r.json().catch(()=>null)).then(j=>setMessages(Array.isArray(j?.data?.messages)?j.data.messages:[])).catch(()=>{})},[initialConversationId]);
 useEffect(()=>{end.current?.scrollIntoView({behavior:"smooth"})},[messages,busy]);
 useEffect(()=>{if(role!=="customer")return;fetch("/api/customer-support-config",{cache:"no-store"}).then(r=>r.json().catch(()=>null)).then(j=>{if(j?.ok)setConfig({...fallbackConfig,...j.data})}).catch(()=>{})},[role]);
 const humanLabel=useMemo(()=>config.paidHumanEnabled?`${t.human} · ${t.paid} ${money(config.paidHumanFee,config.paidHumanCurrency)}`:t.human,[config,t]);
 const create=useCallback(async()=>{const r=await fetch('/api/platform-support',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'create',role,locale})});const j=await r.json().catch(()=>null);if(!r.ok||!j?.data?.id)throw new Error('create');setConversationId(String(j.data.id));setMessages([]);return String(j.data.id)},[role,locale]);
 async function submit(message:string,forceHuman=false){const value=message.trim();if(!value&&!forceHuman)return;setBusy(true);try{const id=conversationId||await create();const r=await fetch('/api/platform-support',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:forceHuman?'escalate':'message',conversationId:id,role,locale,message:value,paidHumanFee:forceHuman?config.paidHumanFee:undefined,currency:config.paidHumanCurrency})});const j=await r.json().catch(()=>null);if(!r.ok)throw new Error('send');setMessages(Array.isArray(j?.data?.messages)?j.data.messages:[]);setText('')}catch{setMessages(x=>[...x,{id:`error-${Date.now()}`,senderRole:'system',body:t.error,createdAt:new Date().toISOString()}])}finally{setBusy(false)}}
 return <section className="zx-support-center"><header><div><h1>{t.title}</h1><p>{t.hint}</p></div><button type="button" onClick={()=>{setConversationId('');setMessages([]);setText(initialPrompt||"")}}>{t.newChat}</button></header>{config.basicAssistantEnabled&&<div className="zx-support-basic">✨ {t.basic}</div>}<div className="zx-support-thread">{messages.length===0&&<div className="zx-support-welcome">{t.empty}</div>}{messages.map(m=><div key={m.id} className="zx-support-message" data-sender={m.senderRole}><small>{m.senderRole==='assistant'?'ZhaoXi':m.senderRole==='user'?role:m.senderRole}</small><p>{m.body}</p></div>)}{busy&&<div className="zx-support-message" data-sender="assistant"><p>{t.loading}</p></div>}<div ref={end}/></div><form onSubmit={e=>{e.preventDefault();void submit(text)}}><textarea value={text} onChange={e=>setText(e.target.value)} placeholder={t.placeholder} rows={3}/><div>{config.paidHumanEnabled&&<button type="button" className="secondary" disabled={busy} onClick={()=>void submit('',true)}>👤 {humanLabel}</button>}<button type="submit" className="primary" disabled={busy||!text.trim()}>{t.send}</button></div></form><style>{`.zx-support-center{display:grid;gap:12px}.zx-support-center>header{display:flex;justify-content:space-between;gap:12px;align-items:start}.zx-support-center h1{margin:0;font-size:24px}.zx-support-center header p{margin:6px 0 0;color:#64748b;font-size:12px;line-height:1.45}.zx-support-center button{border:0;border-radius:12px;padding:10px 12px;font-weight:800;cursor:pointer}.zx-support-basic{padding:10px 12px;border-radius:14px;background:#ecfdf5;color:#067647;font-size:12px;font-weight:750}.zx-support-thread{min-height:320px;max-height:55vh;overflow:auto;padding:12px;background:rgba(255,255,255,.72);backdrop-filter:blur(18px);border:1px solid rgba(226,232,240,.9);border-radius:19px;display:flex;flex-direction:column;gap:9px}.zx-support-welcome{padding:13px;border-radius:15px;background:#f0fdf4;color:#166534}.zx-support-message{max-width:84%;padding:10px 13px;border-radius:16px;background:#f1f5f9;align-self:flex-start}.zx-support-message[data-sender=user]{align-self:flex-end;background:#07c160;color:#fff}.zx-support-message small{opacity:.72;font-size:10px}.zx-support-message p{margin:4px 0 0;white-space:pre-wrap}.zx-support-center form{display:grid;gap:8px}.zx-support-center textarea{width:100%;resize:vertical;border:1px solid #d6e0da;border-radius:15px;padding:12px;font:inherit;background:rgba(255,255,255,.84);color:inherit;box-sizing:border-box}.zx-support-center form>div{display:flex;justify-content:flex-end;gap:7px;flex-wrap:wrap}.zx-support-center .primary{background:#07c160;color:white}.zx-support-center .secondary{background:#eef2f7;color:#334155;font-size:11px}`}</style></section>
}
export function supportLabel(locale:ZhaoXiLocale){return copy[locale].title}
