"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState, type ReactNode } from "react";
import { localizeOrganizationName, useZhaoXiLocale } from "@zhaoxi/i18n";
import { useZhaoXiSession } from "@zhaoxi/auth";
import MiniTabBar from "../../_components/MiniTabBar";
import CrossModuleRecommendations from "../../_components/CrossModuleRecommendations";
import FavoriteServiceButton from "../../_components/FavoriteServiceButton";
import { CustomerServiceIcon } from "../../_components/CustomerServiceIcon";
import { getCached, setCached } from "../../_lib/client-cache";

type Listing={id:string;code:string;moduleCode:string;name?:string;summary?:string;description?:string;priceFrom?:string|null;currency?:string;metadata?:Record<string,unknown>;organization?:{id?:string;code?:string;name?:string;phone?:string;address?:string;metadata?:Record<string,unknown>}};
const C={
"zh-CN":{back:"租房",month:"月",verified:"赵喜认证房源",property:"房源信息",bed:"卧室",bath:"卫生间",area:"面积",furnished:"家具",deposit:"押金",available:"可入住日期",lease:"最短租期",district:"区域",amenities:"配套设施",location:"位置",contact:"联系房东/机构",phone:"电话联系",wechat:"微信",favorite:"收藏",favorited:"已收藏",inquiry:"发送租房意向",name:"姓名",mobile:"联系电话",moveIn:"预计入住日期",months:"预计租期（月）",occupants:"入住人数",budget:"月预算",contactBy:"优先联系方式",notes:"补充需求",send:"发送给房源方",sending:"发送中…",sent:"已发送租房意向",sentHint:"房源方已收到您的需求，可在赵喜订单/服务记录中继续跟进。",requestCode:"咨询编号",map:"查看地图",gallery:"房源图片",noImages:"暂无更多图片",yes:"全家具",partial:"部分家具",no:"无家具",notSet:"未填写",support:"让赵喜协助沟通",supportHint:"需要中文/越南语协助时可联系赵喜助手",phoneOpt:"电话",wechatOpt:"微信",whatsappOpt:"WhatsApp",whatsapp:"WhatsApp",statusAvailable:"可租",statusReserved:"已预订",statusRented:"已出租",unavailableHint:"该房源暂不接受新的租房意向"},
"zh-TW":{back:"租房",month:"月",verified:"趙喜認證房源",property:"房源資訊",bed:"臥室",bath:"衛浴",area:"面積",furnished:"家具",deposit:"押金",available:"可入住日期",lease:"最短租期",district:"區域",amenities:"配套設施",location:"位置",contact:"聯絡房東/機構",phone:"電話聯絡",wechat:"微信",favorite:"收藏",favorited:"已收藏",inquiry:"發送租房意向",name:"姓名",mobile:"聯絡電話",moveIn:"預計入住日期",months:"預計租期（月）",occupants:"入住人數",budget:"月預算",contactBy:"優先聯絡方式",notes:"補充需求",send:"發送給房源方",sending:"發送中…",sent:"已發送租房意向",sentHint:"房源方已收到您的需求，可在趙喜訂單/服務記錄中繼續跟進。",requestCode:"諮詢編號",map:"查看地圖",gallery:"房源圖片",noImages:"暫無更多圖片",yes:"全家具",partial:"部分家具",no:"無家具",notSet:"未填寫",support:"讓趙喜協助溝通",supportHint:"需要中文/越南語協助時可聯絡趙喜助手",phoneOpt:"電話",wechatOpt:"微信",whatsappOpt:"WhatsApp",whatsapp:"WhatsApp",statusAvailable:"可租",statusReserved:"已預訂",statusRented:"已出租",unavailableHint:"該房源目前不接受新的租房意向"},
"vi-VN":{back:"Thuê nhà",month:"tháng",verified:"Nhà/Phòng được ZhaoXi xác thực",property:"Thông tin nhà/phòng",bed:"Phòng ngủ",bath:"WC",area:"Diện tích",furnished:"Nội thất",deposit:"Đặt cọc",available:"Có thể vào ở từ",lease:"Thời hạn thuê tối thiểu",district:"Khu vực",amenities:"Tiện ích",location:"Vị trí",contact:"Liên hệ chủ nhà/đơn vị",phone:"Gọi điện",wechat:"WeChat",favorite:"Yêu thích",favorited:"Đã yêu thích",inquiry:"Gửi yêu cầu thuê nhà",name:"Họ tên",mobile:"Số điện thoại",moveIn:"Ngày dự kiến vào ở",months:"Thời gian thuê (tháng)",occupants:"Số người ở",budget:"Ngân sách/tháng",contactBy:"Ưu tiên liên hệ",notes:"Nhu cầu bổ sung",send:"Gửi cho Partner",sending:"Đang gửi…",sent:"Đã gửi yêu cầu thuê nhà",sentHint:"Partner đã nhận nhu cầu của bạn. Bạn có thể tiếp tục theo dõi trong lịch sử đơn/dịch vụ ZhaoXi.",requestCode:"Mã yêu cầu",map:"Xem bản đồ",gallery:"Hình ảnh nhà/phòng",noImages:"Chưa có thêm hình ảnh",yes:"Đầy đủ nội thất",partial:"Nội thất một phần",no:"Không nội thất",notSet:"Chưa cập nhật",support:"Nhờ ZhaoXi hỗ trợ trao đổi",supportHint:"Trợ lý ZhaoXi có thể hỗ trợ khi bạn cần giao tiếp Trung–Việt",phoneOpt:"Điện thoại",wechatOpt:"WeChat",whatsappOpt:"WhatsApp",whatsapp:"WhatsApp",statusAvailable:"Còn trống",statusReserved:"Đã giữ chỗ",statusRented:"Đã cho thuê",unavailableHint:"Nhà/phòng này hiện chưa nhận thêm yêu cầu thuê mới"},
"en-US":{back:"Housing",month:"month",verified:"ZhaoXi verified listing",property:"Property details",bed:"Bedrooms",bath:"Bathrooms",area:"Area",furnished:"Furnishing",deposit:"Deposit",available:"Available from",lease:"Minimum lease",district:"Area",amenities:"Amenities",location:"Location",contact:"Contact landlord/provider",phone:"Call",wechat:"WeChat",favorite:"Favorite",favorited:"Favorited",inquiry:"Send rental inquiry",name:"Name",mobile:"Phone",moveIn:"Expected move-in",months:"Lease length (months)",occupants:"Occupants",budget:"Monthly budget",contactBy:"Preferred contact",notes:"Additional needs",send:"Send to Partner",sending:"Sending…",sent:"Rental inquiry sent",sentHint:"The housing provider has received your request. You can continue tracking it in ZhaoXi service history.",requestCode:"Inquiry code",map:"Open map",gallery:"Property photos",noImages:"No additional photos",yes:"Fully furnished",partial:"Partly furnished",no:"Unfurnished",notSet:"Not specified",support:"Ask ZhaoXi to assist",supportHint:"ZhaoXi Assistant can help with Chinese–Vietnamese communication",phoneOpt:"Phone",wechatOpt:"WeChat",whatsappOpt:"WhatsApp",whatsapp:"WhatsApp",statusAvailable:"Available",statusReserved:"Reserved",statusRented:"Rented",unavailableHint:"This property is not accepting new rental inquiries"}} as const;
const money=(v:number,c="VND")=>`${Math.round(v||0).toLocaleString("vi-VN")} ${c}`;

export default function HousingListingDetail({id}:{id:string}){useEffect(()=>{if(id)fetch(`/api/customer-discovery/views/${id}`,{method:"POST"}).catch(()=>{})},[id]);
 const router = useRouter();
 const session = useZhaoXiSession();
 const isGuest = !session || session.authMethod === "guest" || !session.phone;
 const{locale}=useZhaoXiLocale(),t=C[locale];
 const cacheKey=`housing_listing_${id}_${locale}`;
 const initialHousing=getCached<Listing>(cacheKey);
 const[data,setData]=useState<Listing|null>(()=>initialHousing),[favorite,setFavorite]=useState(false),[loading,setLoading]=useState(()=>!initialHousing),[sending,setSending]=useState(false),[sent,setSent]=useState<{requestCode:string}|null>(null),[error,setError]=useState("");
 const[form,setForm]=useState({customerName:"",customerPhone:"",moveInDate:"",leaseMonths:"12",occupants:"1",budget:"",preferredContact:"phone",wechat:"",whatsapp:"",notes:""});
 useEffect(()=>{if(!initialHousing)setLoading(true);fetch(`/api/platform-services/${id}?locale=${locale}`,{cache:"no-store"}).then(r=>r.json()).then(j=>{if(j?.data){setData(j.data);setCached(cacheKey,j.data)}}).finally(()=>setLoading(false));fetch(`/api/customer-favorites?locale=${encodeURIComponent(locale)}`,{cache:"no-store"}).then(r=>r.json()).then(j=>setFavorite(Array.isArray(j?.data)&&j.data.some((x:any)=>x.id===id))).catch(()=>{});fetch("/api/customer-history",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({serviceId:id})}).catch(()=>{})},[id,locale,cacheKey]);
 useEffect(()=>{fetch("/api/customer-profile",{cache:"no-store"}).then(r=>r.json()).then(j=>{if(!j?.ok||!j.data)return;setForm(v=>({...v,customerName:j.data.user?.displayName||v.customerName,customerPhone:j.data.user?.phone||v.customerPhone}))}).catch(()=>{})},[]);
 async function toggleFavorite(){const next=!favorite;const r=await fetch("/api/customer-favorites",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({serviceId:id,favorite:next})});if(r.ok)setFavorite(next)}
 async function sendInquiry(){if(!data||!form.customerName.trim()||!form.customerPhone.trim())return;setSending(true);setError("");try{const {customerPhone:verifiedPhone,...transactionForm}=form;void verifiedPhone;const r=await fetch("/api/housing-inquiries",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({serviceId:data.id,locale,...transactionForm,leaseMonths:Number(form.leaseMonths||0),occupants:Number(form.occupants||1),budget:Number(form.budget||0)})});const j=await r.json();if(!r.ok||!j?.ok)throw new Error(j?.error?.code||"HOUSING_INQUIRY_FAILED");setSent({requestCode:j.data.requestCode});try{const current=JSON.parse(localStorage.getItem("zhaoxi-request-codes")||"[]") as string[];localStorage.setItem("zhaoxi-request-codes",JSON.stringify(Array.from(new Set([...current,String(j.data.requestCode)])).slice(-100)))}catch{}}catch(e){setError(e instanceof Error?e.message:"HOUSING_INQUIRY_FAILED")}finally{setSending(false)}}
 if(loading)return <main style={shell}><p>…</p></main>;if(!data||data.moduleCode!=="housing")return <main style={shell}><Link href="/housing">‹ {t.back}</Link></main>;
 const m=data.metadata||{},org=data.organization||{},orgMeta=org.metadata||{};
 const rawGallery=Array.isArray(m.galleryUrls)?m.galleryUrls.filter(x=>typeof x==="string"&&x):[],image=String(m.imageUrl||"");const gallery=[...new Set([image,...rawGallery].filter(Boolean))];
 const amenities=Array.isArray(m.amenities)?m.amenities.map(String):String(m.amenities||"").split(/[,;\n]/).map(x=>x.trim()).filter(Boolean);
 const lat=Number(m.latitude),lng=Number(m.longitude),hasMap=Number.isFinite(lat)&&Number.isFinite(lng)&&Math.abs(lat)<=90&&Math.abs(lng)<=180;
 const propertyAddress=String(m.propertyAddress||orgMeta.address||org.address||m.district||"");
 const phone=String(orgMeta.contactPhone||org.phone||""),wechat=String(orgMeta.wechat||"");
 const furnished=String(m.furnished||"");const furnishing=furnished==="yes"?t.yes:furnished==="partial"?t.partial:furnished==="no"?t.no:t.notSet;
 const provider=localizeOrganizationName(locale,org.code,org.name,orgMeta);
 const housingStatus=String(m.housingAvailabilityStatus||"available");
 const canInquire=m.isAvailable!==false&&housingStatus==="available";
 const statusLabel=housingStatus==="reserved"?t.statusReserved:housingStatus==="rented"?t.statusRented:t.statusAvailable;
 return <main style={shell}>
  <header style={top}><Link href="/housing" style={back}>‹</Link><button onClick={()=>void toggleFavorite()} style={{...favBase,background:favorite?"#fff1f2":"#fff",color:favorite?"#e11d48":"#475569"}}>{favorite?"♥":"♡"} {favorite?t.favorited:t.favorite}</button></header>
  <section aria-label={t.gallery} style={galleryWrap}>{gallery.length?gallery.map((src,i)=><img key={`${src}-${i}`} src={src} alt={`${data.name||data.code} ${i+1}`} style={galleryImage}/>):<div style={placeholder}><CustomerServiceIcon serviceId="housing" size={48}/><small>{t.noImages}</small></div>}</section>
  <section style={body}><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"start"}}><div><div style={{display:"flex",gap:6,alignItems:"center",flexWrap:"wrap"}}>{m.adminVerified===true&&<small style={verified}>✓ {t.verified}</small>}<small style={{padding:"4px 7px",borderRadius:999,background:canInquire?"#ecfdf5":housingStatus==="reserved"?"#fff7ed":"#f1f5f9",color:canInquire?"#067647":housingStatus==="reserved"?"#c2410c":"#64748b",fontWeight:900,fontSize:8}}>{statusLabel}</small></div><h1 style={{margin:"7px 0 5px",fontSize:22}}>{data.name||data.code}</h1><p style={{margin:0,color:"#64748b",fontSize:11}}>{data.summary}</p></div></div>
   <strong style={{display:"block",fontSize:18,color:"#ef5a3c",marginTop:12}}>{Number(data.priceFrom||0)>0?`${money(Number(data.priceFrom),data.currency)}/${t.month}`:""}</strong>
   <section style={facts}><Fact icon="🛏" l={t.bed} v={Number(m.bedrooms||0)>0?String(m.bedrooms):t.notSet}/><Fact icon="🚿" l={t.bath} v={Number(m.bathrooms||0)>0?String(m.bathrooms):t.notSet}/><Fact icon="▱" l={t.area} v={Number(m.areaSqm||0)>0?`${m.areaSqm} m²`:t.notSet}/><Fact icon="🛋" l={t.furnished} v={furnishing}/></section>
   <section style={card}><h2 style={h2}>{t.property}</h2><Info l={t.district} v={String(m.district||t.notSet)}/><Info l={t.deposit} v={Number(m.depositMonths||0)>0?`${m.depositMonths} ${t.month}`:t.notSet}/><Info l={t.available} v={String(m.availableFrom||t.notSet)}/><Info l={t.lease} v={Number(m.minLeaseMonths||0)>0?`${m.minLeaseMonths} ${t.month}`:t.notSet}/>{data.description&&<p style={{fontSize:11,lineHeight:1.6,color:"#475569",margin:"10px 0 0"}}>{data.description}</p>}</section>
   {amenities.length>0&&<section style={card}><h2 style={h2}>{t.amenities}</h2><div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{amenities.map(a=><span key={a} style={amenity}>✓ {a}</span>)}</div></section>}
   <section style={card}><h2 style={h2}>{t.location}</h2><p style={{fontSize:11,color:"#475569"}}>⌖ {propertyAddress||t.notSet}</p>{hasMap&&<iframe title={t.location} loading="lazy" referrerPolicy="no-referrer-when-downgrade" src={`https://maps.google.com/maps?q=${encodeURIComponent(`${lat},${lng}`)}&z=15&output=embed`} style={map}/>} {hasMap&&<a target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${lat},${lng}`)}`} style={mapLink}>{t.map} ↗</a>}</section>
   <section style={card}><h2 style={h2}>{t.contact}</h2><b style={{fontSize:12}}>{provider}</b><div style={{display:"flex",gap:7,marginTop:9,flexWrap:"wrap"}}>{phone&&<a href={`tel:${phone}`} style={contactBtn}>☎ {t.phone}</a>}{wechat&&<button onClick={()=>navigator.clipboard?.writeText(wechat)} style={contactBtn}>💬 {t.wechat}: {wechat}</button>}</div></section>
   <section style={card}><h2 style={h2}>{t.inquiry}</h2>{!canInquire?<div style={{padding:11,borderRadius:12,background:"#fff7ed",color:"#9a3412",fontSize:10,fontWeight:800}}>{t.unavailableHint}</div>:sent?<div style={success}><b>✓ {t.sent}</b><p>{t.sentHint}</p><small>{t.requestCode}: {sent.requestCode}</small></div>:<div style={formGrid}><Field l={t.name}><input value={form.customerName} onChange={e=>setForm({...form,customerName:e.target.value})}/></Field><Field l={t.mobile}><input inputMode="tel" value={form.customerPhone} readOnly aria-readonly="true"/></Field><Field l={t.moveIn}><input type="date" value={form.moveInDate} onChange={e=>setForm({...form,moveInDate:e.target.value})}/></Field><Field l={t.months}><input type="number" min={1} max={60} value={form.leaseMonths} onChange={e=>setForm({...form,leaseMonths:e.target.value})}/></Field><Field l={t.occupants}><input type="number" min={1} max={20} value={form.occupants} onChange={e=>setForm({...form,occupants:e.target.value})}/></Field><Field l={t.budget}><input type="number" min={0} value={form.budget} onChange={e=>setForm({...form,budget:e.target.value})}/></Field><Field l={t.contactBy}><select value={form.preferredContact} onChange={e=>setForm({...form,preferredContact:e.target.value})}><option value="phone">{t.phoneOpt}</option><option value="wechat">{t.wechatOpt}</option><option value="whatsapp">{t.whatsappOpt}</option></select></Field>{form.preferredContact==="wechat"&&<Field l={t.wechat}><input value={form.wechat} onChange={e=>setForm({...form,wechat:e.target.value})}/></Field>}{form.preferredContact==="whatsapp"&&<Field l={t.whatsapp}><input value={form.whatsapp} onChange={e=>setForm({...form,whatsapp:e.target.value})}/></Field>}<label style={{...fieldStyle,gridColumn:"1/-1"}}>{t.notes}<textarea rows={4} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label>{error&&<small style={{gridColumn:"1/-1",color:"#b42318"}}>{error}</small>}{isGuest ? <button type="button" onClick={()=>router.push(`/login?redirect=${encodeURIComponent(typeof window!=="undefined"?window.location.pathname:"/housing")}`)} style={send}>Đăng nhập để gửi yêu cầu thuê ›</button> : <button disabled={sending||!form.customerName.trim()||!form.customerPhone.trim()} onClick={()=>void sendInquiry()} style={send}>{sending?t.sending:t.send}</button>}</div>}</section>
  </section><div style={{display:"flex",justifyContent:"flex-end",margin:"8px 0"}}><FavoriteServiceButton serviceId={id}/></div><CrossModuleRecommendations serviceId={id}/><MiniTabBar/>
 </main>
}
function Fact({icon,l,v}:{icon:string;l:string;v:string}){return <div style={{padding:10,borderRadius:13,background:"#f8faf9"}}><span>{icon}</span><small style={{display:"block",fontSize:7,color:"#64748b",marginTop:4}}>{l}</small><b style={{fontSize:9}}>{v}</b></div>}
function Info({l,v}:{l:string;v:string}){return <div style={{display:"flex",justifyContent:"space-between",gap:10,padding:"7px 0",borderBottom:"1px solid #f0f3f1",fontSize:10}}><span style={{color:"#64748b"}}>{l}</span><b style={{textAlign:"right"}}>{v}</b></div>}
function Field({l,children}:{l:string;children:ReactNode}){return <label style={fieldStyle}>{l}{children}</label>}
const shell={minHeight:"100vh",background:"#f5f7f6",paddingBottom:78,fontFamily:"Inter,Arial,sans-serif",color:"#111827"} as const,top={position:"sticky",top:0,zIndex:20,display:"flex",justifyContent:"space-between",alignItems:"center",padding:"10px 14px",background:"rgba(255,255,255,.88)",backdropFilter:"blur(14px)",borderBottom:"1px solid rgba(226,232,240,.8)"} as const,back={display:"inline-flex",alignItems:"center",justifyContent:"center",width:36,height:36,borderRadius:12,background:"#fff",border:"1px solid #e2e8f0",textDecoration:"none",color:"#1e293b",fontSize:20,lineHeight:1,boxShadow:"none"} as const,favBase={border:"1px solid #e2e8f0",borderRadius:999,padding:"7px 13px",fontWeight:750,fontSize:11,cursor:"pointer",boxShadow:"none"} as const,galleryWrap={display:"flex",overflowX:"auto",scrollSnapType:"x mandatory",gap:7,padding:"8px 10px",scrollbarWidth:"none"} as const,galleryImage={flex:"0 0 88%",aspectRatio:"1.28",objectFit:"cover",borderRadius:18,scrollSnapAlign:"center",boxShadow:"0 8px 24px rgba(15,23,42,.08)"} as const,placeholder={height:240,width:"100%",display:"grid",placeItems:"center",background:"#e9f6ed",fontSize:54,borderRadius:18} as const,body={maxWidth:720,margin:"0 auto",padding:"4px 14px 22px"} as const,verified={color:"#078343",fontWeight:850,fontSize:8} as const,facts={display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:7,margin:"12px 0"} as const,card={background:"#fff",border:"1px solid #eef2f6",borderRadius:20,padding:16,marginTop:12,boxShadow:"0 6px 20px rgba(15,23,42,0.04)"} as const,h2={fontSize:13,margin:"0 0 8px"} as const,amenity={padding:"6px 8px",borderRadius:999,background:"#ecfdf5",color:"#067647",fontSize:8,fontWeight:800} as const,map={width:"100%",height:210,border:0,borderRadius:14,display:"block"} as const,mapLink={display:"inline-block",marginTop:8,textDecoration:"none",color:"#078343",fontSize:9,fontWeight:850} as const,contactBtn={border:"1px solid #dbe5df",borderRadius:10,padding:"8px 10px",background:"#fff",textDecoration:"none",color:"#111827",fontSize:9,fontWeight:800} as const,assist={display:"grid",gridTemplateColumns:"32px 1fr auto",gap:8,alignItems:"center",marginTop:10,padding:10,borderRadius:13,background:"#f0fdf4",textDecoration:"none",color:"#111827"} as const,formGrid={display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:8} as const,fieldStyle={display:"grid",gap:4,fontSize:8,color:"#64748b"} as const,send={gridColumn:"1/-1",border:0,borderRadius:999,padding:"13px 18px",background:"#07c160",color:"#fff",fontWeight:800,fontSize:14,boxShadow:"none",cursor:"pointer"} as const,success={padding:12,borderRadius:13,background:"#ecfdf5",color:"#067647",fontSize:10} as const;
