"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import { localizeOrganizationName, useZhaoXiLocale } from "@zhaoxi/i18n";
import { useZhaoXiSession } from "@zhaoxi/auth";
import { getCached, setCached } from "../_lib/client-cache";
import MiniTabBar from "./MiniTabBar";
import {CustomerServiceIcon} from "./CustomerServiceIcon";
import styles from "../services.module.css";
type Detail={id:string;code:string;moduleCode:string;name?:string;summary?:string;description?:string;priceFrom?:string|null;currency?:string;metadata?:Record<string,unknown>;organization?:{id?:string;code?:string;name?:string;description?:string;phone?:string;address?:string;metadata?:Record<string,unknown>}};
const copy={
"zh-CN":{back:"返回",verified:"赵喜认证商家",from:"起",address:"地址",phone:"电话",request:"立即下单",loading:"正在加载…",info:"服务介绍",consult:"在线咨询",assistant:"咨询赵喜助手",favorite:"收藏",favorited:"已收藏",soldOut:"已售罄",paused:"餐厅暂停接单",closed:"餐厅已打烊",busy:"厨房订单已满",promo:"优惠",scheduledOff:"暂未开售",platformPaused:"平台暂时停止接单",property:"房源信息",bedrooms:"卧室",bathrooms:"卫生间",area:"面积",district:"区域",deposit:"押金",furnished:"家具"},
"zh-TW":{back:"返回",verified:"趙喜認證商家",from:"起",address:"地址",phone:"電話",request:"立即下單",loading:"正在載入…",info:"服務介紹",consult:"線上諮詢",assistant:"詢問趙喜助手",favorite:"收藏",favorited:"已收藏",soldOut:"已售罄",paused:"餐廳暫停接單",closed:"餐廳已打烊",busy:"廚房訂單已滿",promo:"優惠",scheduledOff:"暫未開售",platformPaused:"平台暫時停止接單",property:"房源資訊",bedrooms:"臥室",bathrooms:"衛浴",area:"面積",district:"區域",deposit:"押金",furnished:"家具"},
"vi-VN":{back:"Quay lại",verified:"Đối tác ZhaoXi xác thực",from:"Từ",address:"Địa chỉ",phone:"Điện thoại",request:"Đặt dịch vụ",loading:"Đang tải…",info:"Thông tin dịch vụ",consult:"Liên hệ tư vấn",assistant:"Hỏi Trợ lý ZhaoXi",favorite:"Yêu thích",favorited:"Đã yêu thích",soldOut:"Hết món",paused:"Nhà hàng tạm ngưng nhận đơn",closed:"Nhà hàng đã đóng cửa",busy:"Bếp đang quá tải",promo:"Ưu đãi",scheduledOff:"Chưa đến giờ bán",platformPaused:"Platform đang tạm dừng nhận đơn",property:"Thông tin nhà/phòng",bedrooms:"Phòng ngủ",bathrooms:"WC",area:"Diện tích",district:"Khu vực",deposit:"Đặt cọc",furnished:"Nội thất"},
"en-US":{back:"Back",verified:"ZhaoXi verified partner",from:"From",address:"Address",phone:"Phone",request:"Place order",loading:"Loading…",info:"Service information",consult:"Contact for price",assistant:"Ask ZhaoXi Assistant",favorite:"Favorite",favorited:"Favorited",soldOut:"Sold out",paused:"Restaurant paused orders",closed:"Restaurant closed",busy:"Kitchen at capacity",promo:"Promotion",scheduledOff:"Not on sale now",platformPaused:"Platform has temporarily paused orders",property:"Property details",bedrooms:"Bedrooms",bathrooms:"Bathrooms",area:"Area",district:"Area",deposit:"Deposit",furnished:"Furnishing"}} as const;
export default function ServiceDetail({id}:{id:string}){
 const{locale}=useZhaoXiLocale();const session=useZhaoXiSession();const isGuest=!session||session.authMethod==="guest"||!session.phone;
 const cacheKey=`service_detail_${id}_${locale}`;
 const initialData=getCached<Detail>(cacheKey);
 const[data,setData]=useState<Detail|null>(()=>initialData);
 const[favorite,setFavorite]=useState(false);const[restaurantStatus,setRestaurantStatus]=useState<{open:boolean;code:string}|null>(()=>getCached(`res_stat_${data?.organization?.id}`));const[foodPrice,setFoodPrice]=useState<{scheduledAvailable:boolean;promoActive:boolean;promotionLabel:string;baseUnitPrice:number;effectiveUnitPrice:number}|null>(null);const t=copy[locale];
 useEffect(()=>{
   fetch(`/api/platform-services/${id}?locale=${locale}`,{cache:"no-store"}).then(r=>r.json()).then(d=>{if(d?.data){setData(d.data);setCached(cacheKey,d.data)}}).catch(()=>!initialData&&setData(null));
   fetch("/api/customer-favorites?locale="+encodeURIComponent(locale),{cache:"no-store"}).then(r=>r.json()).then(j=>setFavorite(Array.isArray(j?.data)&&j.data.some((x:any)=>x.id===id))).catch(()=>{});
   fetch("/api/customer-history",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({serviceId:id})}).catch(()=>{});
 },[id,locale,cacheKey]);
 useEffect(()=>{if(data?.moduleCode!=="food"||!data.organization?.id){setRestaurantStatus(null);return}let alive=true;const load=()=>fetch(`/api/restaurant-status/${encodeURIComponent(String(data.organization?.id))}`,{cache:"no-store"}).then(r=>r.json()).then(j=>{if(alive&&j?.ok)setRestaurantStatus(j.data)}).catch(()=>{});void load();const timer=setInterval(load,10000);return()=>{alive=false;clearInterval(timer)}},[data?.moduleCode,data?.organization?.id]);
 useEffect(()=>{if(data?.moduleCode!=="food"){setFoodPrice(null);return}let alive=true;const load=()=>fetch(`/api/food-pricing?ids=${encodeURIComponent(data.id)}&q_${encodeURIComponent(data.id)}=1`,{cache:"no-store"}).then(r=>r.json()).then(j=>{if(alive&&j?.ok)setFoodPrice(j.data?.[data.id]||null)}).catch(()=>{});void load();const timer=setInterval(load,10000);return()=>{alive=false;clearInterval(timer)}},[data?.id,data?.moduleCode]);
 async function toggleFavorite(){const next=!favorite;setFavorite(next);try{const r=await fetch("/api/customer-favorites",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({serviceId:id,favorite:next})});if(!r.ok)throw new Error()}catch{setFavorite(!next)}}
 if(!data)return <main className={styles.shell}><div className={styles.state}><div className={styles.stateIcon}><CustomerServiceIcon serviceId="food" size={28}/></div><p>{t.loading}</p></div><MiniTabBar/></main>;
 const displayUnit=foodPrice?.promoActive?foodPrice.effectiveUnitPrice:Number(data.priceFrom||0);const price=data.priceFrom?`${t.from} ${Number(displayUnit).toLocaleString("vi-VN")} ${data.currency||"VND"}`:t.consult;
 const orgName=localizeOrganizationName(locale,data.organization?.code,data.organization?.name,data.organization?.metadata);const image=String(data.metadata?.imageUrl||"");const soldOut=data.moduleCode==="food"&&data.metadata?.isAvailable===false;const restaurantBlocked=data.moduleCode==="food"&&restaurantStatus?.open===false;const scheduledOff=data.moduleCode==="food"&&foodPrice?.scheduledAvailable===false;const unavailableText=soldOut?t.soldOut:scheduledOff?t.scheduledOff:restaurantStatus?.code==="platform_paused"?t.platformPaused:restaurantStatus?.code==="manual_paused"?t.paused:restaurantStatus?.code==="closed_hours"?t.closed:t.busy;
 return <main className={styles.shell}><header className={styles.detailHero}><Link href={`/services/${data.moduleCode}`} className={styles.backButton}>‹</Link><div className={styles.heroEmoji} style={image?{backgroundImage:`url(${image})`,backgroundSize:"cover",backgroundPosition:"center"}:undefined}>{image?<span className={styles.detailServiceBadge}><CustomerServiceIcon serviceId={data.moduleCode} size={42}/></span>:<CustomerServiceIcon serviceId={data.moduleCode} size={76}/>}</div></header><section className={styles.detailBody}><span className={styles.verified}>✓ {t.verified}</span><h1>{data.name||data.code}</h1><p className={styles.summary}>{data.summary}</p><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:10}}><div><strong className={styles.bigPrice}>{price}</strong>{foodPrice?.promoActive&&<small style={{display:"block",marginTop:4,color:"var(--zx-warning)",fontWeight:850}}>{foodPrice.promotionLabel||t.promo}</small>}</div><button type="button" onClick={()=>void toggleFavorite()} style={{border:"1px solid #E2E8F0",borderRadius:999,padding:"8px 14px",background:favorite?"#ECFDF5":"#FFFFFF",color:favorite?"#059669":"#475569",fontWeight:750,fontSize:12,cursor:"pointer"}}>{favorite?"★":"☆"} {favorite?t.favorited:t.favorite}</button></div><article className={styles.merchant}><h2>{orgName}</h2><p>{data.organization?.description}</p>{data.organization?.address&&<div><b>{t.address}</b><span>{data.organization.address}</span></div>}{data.organization?.phone&&<div><b>{t.phone}</b><a href={`tel:${data.organization.phone}`}>{data.organization.phone}</a></div>}</article>{data.moduleCode==="housing"&&<article className={styles.description}><h2>{t.property}</h2><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:8}}>{[[t.bedrooms,data.metadata?.bedrooms],[t.bathrooms,data.metadata?.bathrooms],[t.area,data.metadata?.areaSqm?`${data.metadata.areaSqm} m²`:""],[t.district,data.metadata?.district],[t.deposit,data.metadata?.depositMonths?`${data.metadata.depositMonths} month`:""],[t.furnished,data.metadata?.furnished]].filter(([,v])=>v!==undefined&&v!=="").map(([k,v])=><div key={String(k)} style={{padding:9,borderRadius:10,background:"var(--zx-surface-soft)"}}><small>{String(k)}</small><b style={{display:"block",marginTop:3}}>{String(v)}</b></div>)}</div></article>}<article className={styles.description}><h2>{t.info}</h2><p>{data.description||data.summary}</p></article>{soldOut||scheduledOff||restaurantBlocked?<div className={styles.primaryAction} style={{background:"var(--zx-text-muted)",pointerEvents:"none"}}>{unavailableText}</div>:<Link className={styles.primaryAction} href={isGuest ? `/login?redirect=${encodeURIComponent(`/request/${data.id}`)}` : `/request/${data.id}`}>{t.request}</Link>}</section><MiniTabBar/></main>
}
