"use client";
import {useEffect,useState} from "react";
type Policy={id:string;app:string;enabled:boolean;healthWindowMinutes:number;warningMaxPercent:number;criticalFallbackPercent:number;currentPercent:number;accessMode:string};
type Event={id:string;app:string;healthStatus:string;previousPercent:number;nextPercent:number;action:string;reason:string;createdAt:string};
export default function RolloutGuardPanel(){
 const[policies,setPolicies]=useState<Policy[]>([]);const[events,setEvents]=useState<Event[]>([]);const[busy,setBusy]=useState<string|null>(null);const[error,setError]=useState("");
 const load=async()=>{try{const r=await fetch("/api/platform-rollout-guard",{cache:"no-store"});const x=await r.json();if(!r.ok||!x?.ok)throw new Error(x?.error?.code||"ROLLOUT_GUARD_LOAD_FAILED");setPolicies(x.data?.policies||[]);setEvents(x.data?.events||[]);setError("")}catch(e){setError(e instanceof Error?e.message:"ROLLOUT_GUARD_LOAD_FAILED")}};
 useEffect(()=>{void load()},[]);
 async function patch(p:Policy,body:Partial<Policy>){setBusy(p.app);try{const r=await fetch(`/api/platform-rollout-guard/${p.app}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const x=await r.json();if(!r.ok||!x?.ok)throw new Error(x?.error?.code||"ROLLOUT_GUARD_UPDATE_FAILED");await load()}catch(e){setError(e instanceof Error?e.message:"ROLLOUT_GUARD_UPDATE_FAILED")}finally{setBusy(null)}}
 async function evaluate(){setBusy("evaluate");try{const r=await fetch("/api/platform-rollout-guard/evaluate",{method:"POST"});const x=await r.json();if(!r.ok||!x?.ok)throw new Error(x?.error?.code||"ROLLOUT_GUARD_EVALUATE_FAILED");await load()}catch(e){setError(e instanceof Error?e.message:"ROLLOUT_GUARD_EVALUATE_FAILED")}finally{setBusy(null)}}
 return <section style={{padding:16,borderRadius:18,background:"#fff",border:"1px solid #e5e7eb",marginBottom:14}}>
  <div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"center"}}><div><b>Automatic Rollout Guard</b><small style={{display:"block",color:"#64748b"}}>Blocks unsafe increases and can reduce exposure automatically</small></div><button onClick={()=>void evaluate()} disabled={busy!==null} style={{border:0,borderRadius:10,padding:"8px 10px",background:"#111827",color:"#fff",fontWeight:800}}>Evaluate now</button></div>
  {error&&<div style={{marginTop:10,padding:10,borderRadius:10,background:"#fff1f2",color:"#be123c"}}>{error}</div>}
  <div style={{display:"grid",gap:10,marginTop:12}}>{policies.map(p=><article key={p.id} style={{padding:12,border:"1px solid #edf0ee",borderRadius:12}}>
   <div style={{display:"flex",justifyContent:"space-between",gap:8}}><b>{p.app}</b><button onClick={()=>void patch(p,{enabled:!p.enabled})} disabled={busy!==null} style={{border:0,borderRadius:999,padding:"6px 9px",background:p.enabled?"#dcfce7":"#f1f5f9",fontWeight:800}}>{p.enabled?"GUARD ON":"GUARD OFF"}</button></div>
   <small style={{display:"block",color:"#64748b",marginTop:4}}>Current {p.currentPercent}% · {p.accessMode.toUpperCase()} · Window {p.healthWindowMinutes} min</small>
   <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginTop:9}}><label style={{fontSize:12}}>Warning max<input type="number" min="0" max="100" value={p.warningMaxPercent} onChange={e=>setPolicies(v=>v.map(x=>x.id===p.id?{...x,warningMaxPercent:Number(e.target.value)}:x))} onBlur={()=>void patch(p,{warningMaxPercent:p.warningMaxPercent})} style={{width:"100%",marginTop:4,padding:8,border:"1px solid #dbe3dd",borderRadius:8}}/></label><label style={{fontSize:12}}>Critical fallback<input type="number" min="0" max="100" value={p.criticalFallbackPercent} onChange={e=>setPolicies(v=>v.map(x=>x.id===p.id?{...x,criticalFallbackPercent:Number(e.target.value)}:x))} onBlur={()=>void patch(p,{criticalFallbackPercent:p.criticalFallbackPercent})} style={{width:"100%",marginTop:4,padding:8,border:"1px solid #dbe3dd",borderRadius:8}}/></label></div>
  </article>)}</div>
  {events.length>0&&<div style={{marginTop:12}}><b style={{fontSize:13}}>Recent guard actions</b><div style={{display:"grid",gap:7,marginTop:7}}>{events.slice(0,5).map(e=><div key={e.id} style={{padding:9,borderRadius:9,background:e.healthStatus==="critical"?"#fff1f2":"#fff7ed",fontSize:12}}><b>{e.app}: {e.previousPercent}% → {e.nextPercent}%</b><span style={{display:"block",color:"#64748b"}}>{e.reason} · {new Date(e.createdAt).toLocaleString()}</span></div>)}</div></div>}
 </section>
}