"use client";
import{useEffect,useState}from"react";import{useZhaoXiLocale}from"@zhaoxi/i18n";
type Role="customer"|"partner"|"driver";type App={id:string;role:string;status:string;reviewNote?:string|null};
const copy={
"zh-CN":{step1:"选择身份",step2:"完善资料",name:"姓名",phone:"手机号码",city:"城市",business:"商家 / 门店名称",type:"服务类型",address:"商家地址",vehicle:"车辆类型",plate:"车牌号",notes:"补充信息",submit:"提交",customerDone:"客户资料已完成。",submitted:"申请已提交，等待管理员审核。",submitFailed:"暂时无法提交。"},
"zh-TW":{step1:"選擇身分",step2:"完善資料",name:"姓名",phone:"手機號碼",city:"城市",business:"商家 / 門店名稱",type:"服務類型",address:"商家地址",vehicle:"車輛類型",plate:"車牌號",notes:"補充資訊",submit:"提交",customerDone:"客戶資料已完成。",submitted:"申請已提交，等待管理員審核。",submitFailed:"暫時無法提交。"},
"vi-VN":{step1:"Chọn vai trò",step2:"Hoàn thiện thông tin",name:"Tên hiển thị",phone:"Điện thoại",city:"Thành phố",business:"Tên doanh nghiệp / cửa hàng",type:"Loại dịch vụ",address:"Địa chỉ kinh doanh",vehicle:"Loại xe",plate:"Biển số",notes:"Thông tin bổ sung",submit:"Gửi",customerDone:"Đã hoàn tất thông tin Customer.",submitted:"Đã gửi hồ sơ, chờ Admin duyệt.",submitFailed:"Chưa thể gửi hồ sơ."},
"en-US":{step1:"Choose role",step2:"Complete profile",name:"Display name",phone:"Phone",city:"City",business:"Business / store name",type:"Service type",address:"Business address",vehicle:"Vehicle type",plate:"Plate number",notes:"Additional information",submit:"Submit",customerDone:"Customer profile completed.",submitted:"Application submitted for Admin approval.",submitFailed:"Unable to submit onboarding."}} as const;
export function OnboardingCenter(){const{locale}=useZhaoXiLocale();const t=copy[locale];const[role,setRole]=useState<Role>("customer");const[msg,setMsg]=useState("");const[apps,setApps]=useState<App[]>([]);const[form,setForm]=useState({displayName:"",phone:"",city:"Da Nang",businessName:"",businessType:"food",addressText:"",vehicleType:"motorbike",plateNumber:"",notes:""});
async function load(){try{const r=await fetch("/api/platform-onboarding/status",{cache:"no-store"});const p=await r.json().catch(()=>null);if(r.ok)setApps(p?.data?.applications||[])}catch{}}useEffect(()=>{void load()},[]);
async function submit(){try{const r=await fetch("/api/platform-onboarding/submit",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({role,...form})});const p=await r.json().catch(()=>null);setMsg(r.ok?(role==="customer"?t.customerDone:t.submitted):p?.error?.message||t.submitFailed);if(r.ok)await load()}catch{setMsg(t.submitFailed)}}
const input=(k:keyof typeof form,ph:string)=><input value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} placeholder={ph} style={{padding:12,border:"1px solid #dbe3df",borderRadius:12}}/>;
const partnerStatus=(status:string)=>status==="approved"?"Đã được duyệt — bạn có thể cấu hình gian hàng.":status==="rejected"?"Hồ sơ bị từ chối. Xem ghi chú của Admin và gửi lại.":"Đang chờ Admin duyệt — chưa thể cấu hình gian hàng.";
return <section style={{display:"grid",gap:14}}><div style={{background:"white",padding:14,borderRadius:16,display:"grid",gap:10}}><b>1. {t.step1}</b><select value={role} onChange={e=>setRole(e.target.value as Role)} style={{padding:12,borderRadius:12}}><option value="customer">Customer</option><option value="partner">Partner</option><option value="driver">Driver</option></select></div><div style={{background:"white",padding:14,borderRadius:16,display:"grid",gap:10}}><b>2. {t.step2}</b>{input("displayName",t.name)}{input("phone",t.phone)}{input("city",t.city)}{role==="partner"&&<>{input("businessName",t.business)}{input("businessType",t.type)}{input("addressText",t.address)}</>}{role==="driver"&&<>{input("vehicleType",t.vehicle)}{input("plateNumber",t.plate)}</>}{input("notes",t.notes)}<button onClick={submit} style={{padding:12,border:0,borderRadius:12,background:"#07c160",color:"white",fontWeight:800}}>{t.submit}</button></div>{msg&&<div style={{padding:12,borderRadius:12,background:"#ecfdf5"}}>{msg}</div>}<div style={{display:"grid",gap:8}}>{apps.map(a=><article key={a.id} style={{background:"white",padding:14,borderRadius:14,border:a.role==="partner"?"1px solid #bbf7d0":undefined}}><b>{a.role==="partner"?"Hồ sơ gian hàng":a.role}</b><span style={{marginLeft:8,fontWeight:800,color:a.status==="approved"?"#067647":a.status==="rejected"?"#b42318":"#a16207"}}>{a.status==="approved"?"ĐÃ DUYỆT":a.status==="rejected"?"TỪ CHỐI":"CHỜ DUYỆT"}</span>{a.role==="partner"&&<p style={{margin:"8px 0 0",lineHeight:1.45}}>{partnerStatus(a.status)}</p>}{a.reviewNote&&<small style={{display:"block",marginTop:8}}>Ghi chú Admin: {a.reviewNote}</small>}{a.role==="partner"&&a.status==="approved"&&<a href="/catalog" style={{display:"inline-block",marginTop:10,padding:"9px 12px",borderRadius:10,background:"#087f5b",color:"white",fontWeight:800,textDecoration:"none"}}>Mở cấu hình gian hàng</a>}</article>)}</div></section>}
