"use client";

import { useEffect, useRef, useState } from "react";
import type { ZhaoXiLocale } from "@zhaoxi/i18n";

export type LocationPoint = { latitude: number; longitude: number };
type Suggestion = { coordinate: LocationPoint; label: string };
type Map = { flyTo: (o: { center: [number, number]; zoom?: number }) => void; on: (n: string, cb: (e: { lngLat: { lat: number; lng: number } }) => void) => void; addControl: (c: unknown, p?: string) => void; remove: () => void };
type Marker = { setLngLat: (p: [number, number]) => Marker; addTo: (m: Map) => Marker };
type MapLibre = { Map: new (o: Record<string, unknown>) => Map; Marker: new (o?: Record<string, unknown>) => Marker; NavigationControl: new (o?: Record<string, unknown>) => unknown };
declare global { interface Window { maplibregl?: MapLibre } }

const words = {
  "vi-VN": { title: "Vị trí trên bản đồ", locate: "Dùng vị trí hiện tại", locating: "Đang định vị…", placeholder: "Tìm đường, số nhà hoặc địa điểm", search: "Tìm", searching: "Đang tìm địa chỉ…", hint: "Chọn kết quả tìm kiếm hoặc chạm bản đồ để chỉnh chính xác vị trí.", missing: "Không tìm thấy địa chỉ. Hãy nhập chi tiết hơn.", unavailable: "Không lấy được vị trí hiện tại. Hãy kiểm tra quyền định vị." },
  "en-US": { title: "Map location", locate: "Use current location", locating: "Locating…", placeholder: "Search street, house number or place", search: "Search", searching: "Searching addresses…", hint: "Choose a result or click the map to adjust the exact location.", missing: "Address not found. Add more detail.", unavailable: "Location unavailable. Check browser location permission." },
  "zh-CN": { title: "地图位置", locate: "使用当前位置", locating: "正在定位…", placeholder: "搜索街道、门牌号或地点", search: "搜索", searching: "正在搜索地址…", hint: "选择结果或点击地图，调整准确位置。", missing: "找不到地址，请输入更详细的信息。", unavailable: "无法获取位置，请检查定位权限。" },
  "zh-TW": { title: "地圖位置", locate: "使用目前位置", locating: "正在定位…", placeholder: "搜尋街道、門牌號或地點", search: "搜尋", searching: "正在搜尋地址…", hint: "選擇結果或點擊地圖，調整準確位置。", missing: "找不到地址，請輸入更詳細的資訊。", unavailable: "無法取得位置，請檢查定位權限。" },
} as const;
const DEFAULT: LocationPoint = { latitude: 16.047079, longitude: 108.20623 };

function loadMap() {
  if (window.maplibregl) return Promise.resolve(window.maplibregl);
  return new Promise<MapLibre>((resolve, reject) => {
    if (!document.querySelector("link[data-zx-maplibre]")) { const link = document.createElement("link"); link.rel = "stylesheet"; link.href = "https://unpkg.com/maplibre-gl@5/dist/maplibre-gl.css"; link.dataset.zxMaplibre = "true"; document.head.appendChild(link); }
    const existing = document.querySelector<HTMLScriptElement>("script[data-zx-maplibre]");
    if (existing) { existing.addEventListener("load", () => window.maplibregl ? resolve(window.maplibregl) : reject(), { once: true }); existing.addEventListener("error", reject, { once: true }); return; }
    const script = document.createElement("script"); script.src = "https://unpkg.com/maplibre-gl@5/dist/maplibre-gl.js"; script.async = true; script.dataset.zxMaplibre = "true"; script.onload = () => window.maplibregl ? resolve(window.maplibregl) : reject(); script.onerror = reject; document.body.appendChild(script);
  });
}

export function LocationPicker({ locale, address, point, onAddress, onPoint }: { locale: ZhaoXiLocale; address: string; point: LocationPoint | null; onAddress: (address: string) => void; onPoint: (point: LocationPoint) => void }) {
  const t = words[locale]; const mapNode = useRef<HTMLDivElement>(null); const mapRef = useRef<Map | null>(null); const markerRef = useRef<Marker | null>(null); const selectedRef = useRef("");
  const [busy, setBusy] = useState(false); const [searching, setSearching] = useState(false); const [suggestions, setSuggestions] = useState<Suggestion[]>([]); const [shown, setShown] = useState(false); const [error, setError] = useState("");
  const reverse = async (next: LocationPoint) => { try { const r = await fetch(`/api/delivery-distance?lat=${next.latitude}&lon=${next.longitude}`); const json = await r.json(); const label = String(json?.label || ""); if (label) { selectedRef.current = label; onAddress(label); } } catch {} };
  useEffect(() => { let cancelled = false; void loadMap().then((libre) => { if (cancelled || !mapNode.current || mapRef.current) return; const center = point || DEFAULT; const map = new libre.Map({ container: mapNode.current, style: "https://tiles.openfreemap.org/styles/bright", center: [center.longitude, center.latitude], zoom: 14.2, attributionControl: true }); map.addControl(new libre.NavigationControl({ showCompass: false }), "top-right"); markerRef.current = new libre.Marker({ color: "#079b68", scale: 1.05 }).setLngLat([center.longitude, center.latitude]).addTo(map); map.on("click", (event) => { const next = { latitude: Number(event.lngLat.lat.toFixed(7)), longitude: Number(event.lngLat.lng.toFixed(7)) }; markerRef.current?.setLngLat([next.longitude, next.latitude]); onPoint(next); void reverse(next); }); mapRef.current = map; }).catch(() => setError("")); return () => { cancelled = true; mapRef.current?.remove(); mapRef.current = null; markerRef.current = null; }; }, []);
  useEffect(() => { if (!point) return; mapRef.current?.flyTo({ center: [point.longitude, point.latitude], zoom: 15.5 }); markerRef.current?.setLngLat([point.longitude, point.latitude]); }, [point?.latitude, point?.longitude]);
  useEffect(() => { const query = address.trim(); if (selectedRef.current === query) { selectedRef.current = ""; return; } if (query.length < 3) { setSuggestions([]); setShown(false); setSearching(false); return; } const controller = new AbortController(); const timer = window.setTimeout(async () => { setSearching(true); try { const r = await fetch(`/api/delivery-distance?limit=5&address=${encodeURIComponent(query)}`, { signal: controller.signal }); const json = await r.json(); const found = (json?.results || []) as Suggestion[]; setSuggestions(found); setShown(found.length > 0); } catch { setSuggestions([]); } finally { if (!controller.signal.aborted) setSearching(false); } }, 150); return () => { clearTimeout(timer); controller.abort(); }; }, [address]);
  const choose = (item: Suggestion) => { selectedRef.current = item.label; onAddress(item.label); onPoint(item.coordinate); setSuggestions([]); setShown(false); setError(""); };
  const find = async () => { if (!address.trim()) return; setBusy(true); setError(""); try { const r = await fetch(`/api/delivery-distance?limit=5&address=${encodeURIComponent(address.trim())}`); const json = await r.json(); if (!r.ok || !json?.results?.[0]) throw new Error(); choose(json.results[0]); } catch { setError(t.missing); } finally { setBusy(false); } };
  const current = () => { setBusy(true); setError(""); if (!navigator.geolocation) { setError(t.unavailable); setBusy(false); return; } navigator.geolocation.getCurrentPosition(async (position) => { const next = { latitude: Number(position.coords.latitude.toFixed(7)), longitude: Number(position.coords.longitude.toFixed(7)) }; onPoint(next); await reverse(next); setBusy(false); }, () => { setError(t.unavailable); setBusy(false); }, { enableHighAccuracy: true, timeout: 12000, maximumAge: 60000 }); };
  return <section style={{ display: "grid", gap: 10 }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 8, flexWrap: "wrap" }}><b>{t.title}</b><button type="button" onClick={current} disabled={busy} style={currentButton}>◎ {busy ? t.locating : t.locate}</button></div><div style={{ position: "relative", zIndex: 10 }}><div style={searchShell}><span style={{ color: "#07845a", fontSize: 20 }}>⌕</span><input value={address} required autoComplete="street-address" onChange={(e) => { onAddress(e.target.value); setShown(true); setError(""); }} onKeyDown={(e) => { if (e.key === "Enter") { e.preventDefault(); void find(); } }} placeholder={t.placeholder} style={searchInput}/><button type="button" disabled={busy || searching || !address.trim()} onClick={() => void find()} style={findButton}>{searching ? "…" : t.search}</button></div>{shown && (searching || suggestions.length > 0) && <div style={suggestionBox}>{searching && !suggestions.length && <div style={{ padding: "13px 14px", color: "#648178", fontWeight: 650 }}>{t.searching}</div>}{suggestions.map((item, index) => <button key={`${item.coordinate.latitude}-${item.coordinate.longitude}`} type="button" onMouseDown={(e) => e.preventDefault()} onClick={() => choose(item)} style={{ ...suggestion, borderBottom: index < suggestions.length - 1 ? "1px solid #f1f5f9" : 0 }}><span>📍</span><span>{item.label}</span></button>)}</div>}</div><div ref={mapNode} style={{ height: 320, borderRadius: 22, overflow: "hidden", background: "#eaf3ef", boxShadow: "0 12px 32px rgba(15,70,52,.12)" }}/><small style={{ color: "#64748b" }}>{t.hint}</small>{point && <small style={{ color: "#047857" }}>✓ {point.latitude.toFixed(6)}, {point.longitude.toFixed(6)}</small>}{error && <small style={{ color: "#be123c", fontWeight: 650 }}>{error}</small>}</section>;
}
const currentButton = { border: 0, background: "#ecfdf5", color: "#047857", borderRadius: 12, padding: "9px 14px", fontWeight: 750, cursor: "pointer", boxShadow: "0 2px 8px rgba(4,120,87,.12)" } as const;
const searchShell = { minHeight: 52, display: "flex", alignItems: "center", gap: 9, padding: "0 8px 0 14px", border: 0, borderRadius: 16, background: "#fff", boxShadow: "0 2px 8px rgba(15,23,42,.08),0 8px 24px rgba(15,23,42,.06)" } as const;
const searchInput = { flex: 1, minWidth: 0, height: 48, border: 0, outline: 0, background: "transparent", color: "#153b2f", fontSize: 15, fontWeight: 600 } as const;
const findButton = { minWidth: 58, height: 38, border: 0, borderRadius: 11, padding: "0 12px", background: "#079b68", color: "#fff", fontWeight: 800, cursor: "pointer" } as const;
const suggestionBox = { position: "absolute", top: "calc(100% + 6px)", left: 0, right: 0, zIndex: 9999, maxHeight: 280, overflowY: "auto" as const, borderRadius: 16, background: "#fff", boxShadow: "0 16px 40px rgba(15,23,42,.15)", padding: "4px 0" } as const;
const suggestion = { width: "100%", display: "flex", alignItems: "flex-start", gap: 10, padding: "12px 14px", border: 0, background: "#fff", color: "#1e293b", textAlign: "left" as const, fontWeight: 500, lineHeight: 1.45, cursor: "pointer" } as const;
