"use client";
import {useState,type ReactNode} from "react";
import {useZhaoXiLocale} from "@zhaoxi/i18n";

type Config={timezone:string;promotion:{enabled:boolean;type:"none"|"percent"|"fixed"|"bundle";label:string;percentOff:number;fixedPrice:number;bundleQty:number;bundlePrice:number;minQty:number;startDate:string;endDate:string;startTime:string;endTime:string;weekdays:number[]};saleSchedule:{enabled:boolean;startDate:string;endDate:string;startTime:string;endTime:string;weekdays:number[]}};
const defaults:Config={timezone:"Asia/Ho_Chi_Minh",promotion:{enabled:false,type:"none",label:"",percentOff:10,fixedPrice:0,bundleQty:2,bundlePrice:0,minQty:1,startDate:"",endDate:"",startTime:"00:00",endTime:"23:59",weekdays:[0,1,2,3,4,5,6]},saleSchedule:{enabled:false,startDate:"",endDate:"",startTime:"00:00",endTime:"23:59",weekdays:[0,1,2,3,4,5,6]}};
const copy={
"zh-CN":{button:"促销与售卖时间",title:"菜品促销",promo:"启用促销",type:"优惠类型",none:"无",percent:"百分比优惠",fixed:"促销单价",bundle:"组合优惠",label:"优惠标签",percentOff:"折扣 (%)",fixedPrice:"促销价",bundleQty:"组合数量",bundlePrice:"组合价格",minQty:"最低数量",window:"促销时段",schedule:"限制售卖时间",saleWindow:"可售时段",days:"适用星期",save:"保存",close:"关闭",saved:"已保存",weekday:["日","一","二","三","四","五","六"]},
"zh-TW":{button:"促銷與販售時間",title:"餐點促銷",promo:"啟用促銷",type:"優惠類型",none:"無",percent:"百分比優惠",fixed:"促銷單價",bundle:"組合優惠",label:"優惠標籤",percentOff:"折扣 (%)",fixedPrice:"促銷價",bundleQty:"組合數量",bundlePrice:"組合價格",minQty:"最低數量",window:"促銷時段",schedule:"限制販售時間",saleWindow:"可售時段",days:"適用星期",save:"儲存",close:"關閉",saved:"已儲存",weekday:["日","一","二","三","四","五","六"]},
"vi-VN":{button:"Khuyến mãi & lịch bán",title:"Khuyến mãi món ăn",promo:"Bật khuyến mãi",type:"Loại ưu đãi",none:"Không",percent:"Giảm theo phần trăm",fixed:"Giá ưu đãi cố định",bundle:"Combo theo số lượng",label:"Nhãn ưu đãi",percentOff:"Mức giảm (%)",fixedPrice:"Giá ưu đãi",bundleQty:"Số món/combo",bundlePrice:"Giá combo",minQty:"Số lượng tối thiểu",window:"Khung giờ khuyến mãi",schedule:"Giới hạn thời gian mở bán",saleWindow:"Khung giờ được bán",days:"Ngày áp dụng",save:"Lưu",close:"Đóng",saved:"Đã lưu",weekday:["CN","T2","T3","T4","T5","T6","T7"]},
"en-US":{button:"Promotion & schedule",title:"Food promotion",promo:"Enable promotion",type:"Promotion type",none:"None",percent:"Percentage off",fixed:"Fixed promo price",bundle:"Quantity bundle",label:"Promotion label",percentOff:"Discount (%)",fixedPrice:"Promo price",bundleQty:"Bundle quantity",bundlePrice:"Bundle price",minQty:"Minimum quantity",window:"Promotion window",schedule:"Limit sale schedule",saleWindow:"Sale window",days:"Applicable days",save:"Save",close:"Close",saved:"Saved",weekday:["Sun","Mon","Tue","Wed","Thu","Fri","Sat"]}} as const;

export default function FoodCommercialEditor({serviceId,metadata,onSaved}:{serviceId:string;metadata?:Record<string,unknown>;onSaved?:()=>void}){
 const{locale}=useZhaoXiLocale();const t=copy[locale];const initial=(metadata?.foodCommercial&&typeof metadata.foodCommercial==="object"?metadata.foodCommercial:{}) as Partial<Config>;const[open,setOpen]=useState(false);const[config,setConfig]=useState<Config>({...defaults,...initial,promotion:{...defaults.promotion,...(initial.promotion||{})},saleSchedule:{...defaults.saleSchedule,...(initial.saleSchedule||{})}});const[msg,setMsg]=useState("");
 function days(section:"promotion"|"saleSchedule",day:number){setConfig(v=>{const current=v[section].weekdays.includes(day)?v[section].weekdays.filter(x=>x!==day):[...v[section].weekdays,day].sort();return{...v,[section]:{...v[section],weekdays:current.length?current:[day]}}})}
 async function save(){setMsg("");try{const r=await fetch(`/api/partner-food-commercial/${serviceId}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(config)});const j=await r.json().catch(()=>null);if(r.ok&&j?.ok){setConfig(j.data.config);setMsg(t.saved);onSaved?.()}else setMsg(j?.error?.code||"ERROR")}catch{setMsg("ERROR")}}
 const promo=config.promotion,sale=config.saleSchedule;
 return <>{<button type="button" onClick={()=>setOpen(true)} style={button}>{t.button}</button>}{open&&<div style={overlay}><section style={modal}><header style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><h2 style={{margin:0}}>{t.title}</h2><button onClick={()=>setOpen(false)} style={x}>×</button></header>
  <label style={check}><input type="checkbox" checked={promo.enabled} onChange={e=>setConfig(v=>({...v,promotion:{...v.promotion,enabled:e.target.checked}}))}/>{t.promo}</label>
  {promo.enabled&&<><Field label={t.type}><select value={promo.type} onChange={e=>setConfig(v=>({...v,promotion:{...v.promotion,type:e.target.value as any}}))}><option value="none">{t.none}</option><option value="percent">{t.percent}</option><option value="fixed">{t.fixed}</option><option value="bundle">{t.bundle}</option></select></Field>
  <Field label={t.label}><input value={promo.label} onChange={e=>setConfig(v=>({...v,promotion:{...v.promotion,label:e.target.value}}))}/></Field>
  <div style={grid}>{promo.type==="percent"&&<Field label={t.percentOff}><input type="number" min={0} max={90} value={promo.percentOff} onChange={e=>setConfig(v=>({...v,promotion:{...v.promotion,percentOff:Number(e.target.value)}}))}/></Field>}{promo.type==="fixed"&&<Field label={t.fixedPrice}><input type="number" min={0} value={promo.fixedPrice} onChange={e=>setConfig(v=>({...v,promotion:{...v.promotion,fixedPrice:Number(e.target.value)}}))}/></Field>}{promo.type==="bundle"&&<><Field label={t.bundleQty}><input type="number" min={2} max={20} value={promo.bundleQty} onChange={e=>setConfig(v=>({...v,promotion:{...v.promotion,bundleQty:Number(e.target.value)}}))}/></Field><Field label={t.bundlePrice}><input type="number" min={0} value={promo.bundlePrice} onChange={e=>setConfig(v=>({...v,promotion:{...v.promotion,bundlePrice:Number(e.target.value)}}))}/></Field></>}<Field label={t.minQty}><input type="number" min={1} max={99} value={promo.minQty} onChange={e=>setConfig(v=>({...v,promotion:{...v.promotion,minQty:Number(e.target.value)}}))}/></Field></div>
  <Window title={t.window} startDate={promo.startDate} endDate={promo.endDate} startTime={promo.startTime} endTime={promo.endTime} set={(k,v)=>setConfig(x=>({...x,promotion:{...x.promotion,[k]:v}}))}/><DayButtons title={t.days} values={promo.weekdays} labels={t.weekday} toggle={d=>days("promotion",d)}/></>}
  <hr style={{border:0,borderTop:"1px solid #edf2ef",width:"100%"}}/>
  <label style={check}><input type="checkbox" checked={sale.enabled} onChange={e=>setConfig(v=>({...v,saleSchedule:{...v.saleSchedule,enabled:e.target.checked}}))}/>{t.schedule}</label>
  {sale.enabled&&<><Window title={t.saleWindow} startDate={sale.startDate} endDate={sale.endDate} startTime={sale.startTime} endTime={sale.endTime} set={(k,v)=>setConfig(x=>({...x,saleSchedule:{...x.saleSchedule,[k]:v}}))}/><DayButtons title={t.days} values={sale.weekdays} labels={t.weekday} toggle={d=>days("saleSchedule",d)}/></>}
  <button onClick={()=>void save()} style={{...button,background:"#07c160",color:"#fff",border:0,padding:11}}>{t.save}</button>{msg&&<small style={{color:msg===t.saved?"#078343":"#b42318"}}>{msg}</small>}
 </section></div>}</>
}
function Field({label,children}:{label:string;children:ReactNode}){return <label style={{display:"grid",gap:4,fontSize:18,color:"#64748b"}}>{label}{children}</label>}
function Window({title,startDate,endDate,startTime,endTime,set}:{title:string;startDate:string;endDate:string;startTime:string;endTime:string;set:(k:string,v:string)=>void}){return <section style={{display:"grid",gap:6}}><b style={{fontSize:18}}>{title}</b><div style={grid}><input type="date" value={startDate} onChange={e=>set("startDate",e.target.value)}/><input type="date" value={endDate} onChange={e=>set("endDate",e.target.value)}/><input type="time" value={startTime} onChange={e=>set("startTime",e.target.value)}/><input type="time" value={endTime} onChange={e=>set("endTime",e.target.value)}/></div></section>}
function DayButtons({title,values,labels,toggle}:{title:string;values:number[];labels:readonly string[];toggle:(d:number)=>void}){return <section><b style={{fontSize:18}}>{title}</b><div style={{display:"flex",gap:5,flexWrap:"wrap",marginTop:6}}>{labels.map((x,i)=><button type="button" key={i} onClick={()=>toggle(i)} style={{border:0,borderRadius:999,padding:"6px 8px",background:values.includes(i)?"#dcfce7":"#f1f5f9",color:values.includes(i)?"#067647":"#64748b",fontSize:18,fontWeight:850}}>{x}</button>)}</div></section>}
const button={border:"1px solid #dbe4df",borderRadius:10,padding:"9px 10px",background:"#fff",fontWeight:800,fontSize:18} as const;const overlay={position:"fixed",inset:0,zIndex:100,background:"rgba(15,23,42,.48)",display:"grid",placeItems:"center",padding:16} as const;const modal={width:"min(100%,520px)",maxHeight:"88vh",overflowY:"auto",background:"#fff",borderRadius:20,padding:16,display:"grid",gap:12} as const;const x={border:0,background:"#f1f5f9",borderRadius:999,width:32,height:32,fontSize:18} as const;const check={display:"flex",alignItems:"center",gap:7,fontSize:18,fontWeight:750} as const;const grid={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(250px,1fr))",gap:7} as const;
