"use client";
import{useCallback,useEffect,useState}from"react";import{useZhaoXiLocale}from"@zhaoxi/i18n";
const C={
"zh-CN":{title:"租房业务分析",listings:"房源",available:"可租",reserved:"已预留",rented:"已出租",leads:"客户线索",viewing:"看房转化率",won:"成交率",response:"平均响应",upcoming:"即将看房",minutes:"分钟",funnel:"线索漏斗",new:"新意向",contacted:"已联系",viewingS:"看房",negotiating:"洽谈",wonS:"已成交",lost:"已结束",days7:"7天",days30:"30天",days90:"90天"},
"zh-TW":{title:"租房業務分析",listings:"房源",available:"可租",reserved:"已預留",rented:"已出租",leads:"客戶線索",viewing:"看房轉換率",won:"成交率",response:"平均回應",upcoming:"即將看房",minutes:"分鐘",funnel:"線索漏斗",new:"新意向",contacted:"已聯絡",viewingS:"看房",negotiating:"洽談",wonS:"已成交",lost:"已結束",days7:"7天",days30:"30天",days90:"90天"},
"vi-VN":{title:"Phân tích hiệu quả thuê nhà",listings:"Bất động sản",available:"Còn trống",reserved:"Đã giữ",rented:"Đã thuê",leads:"Lead",viewing:"Tỷ lệ đến xem nhà",won:"Tỷ lệ chốt",response:"Phản hồi trung bình",upcoming:"Lịch xem sắp tới",minutes:"phút",funnel:"Phễu chuyển đổi",new:"Yêu cầu mới",contacted:"Đã liên hệ",viewingS:"Xem nhà",negotiating:"Thương lượng",wonS:"Đã chốt",lost:"Đã kết thúc",days7:"7 ngày",days30:"30 ngày",days90:"90 ngày"},
"en-US":{title:"Housing performance",listings:"Listings",available:"Available",reserved:"Reserved",rented:"Rented",leads:"Leads",viewing:"Viewing conversion",won:"Win rate",response:"Average response",upcoming:"Upcoming viewings",minutes:"min",funnel:"Lead funnel",new:"New",contacted:"Contacted",viewingS:"Viewing",negotiating:"Negotiating",wonS:"Won",lost:"Closed",days7:"7 days",days30:"30 days",days90:"90 days"}} as const;
export default function HousingAnalyticsDashboard({organizationId}:{organizationId:string}){const{locale}=useZhaoXiLocale(),t=C[locale];const[days,setDays]=useState<7|30|90>(30),[data,setData]=useState<any>(null);
 const load=useCallback(async()=>{if(!organizationId)return;const r=await fetch(`/api/partner-housing-analytics?organizationId=${encodeURIComponent(organizationId)}&days=${days}`,{cache:"no-store"}),j=await r.json();if(j?.ok)setData(j.data)},[organizationId,days]);
 useEffect(()=>{void load()},[load]);if(!data)return null;const x=data.organizations?.[0],s=data.summary,f=x?.leads?.funnel||{};
 return <section style={{margin:"16px 0",padding:20,border:"1px solid #dfe8e3",borderRadius:18,background:"#fff"}}><div style={{display:"flex",justifyContent:"space-between",gap:8,alignItems:"center",flexWrap:"wrap"}}><h2 style={{margin:0,fontSize:18}}>📊 {t.title}</h2><div style={{display:"flex",gap:4}}>{([7,30,90] as const).map(v=><button key={v} onClick={()=>setDays(v)} style={pill(days===v)}>{v===7?t.days7:v===30?t.days30:t.days90}</button>)}</div></div><div style={grid}><M l={t.listings} v={s.listings}/><M l={t.available} v={s.available}/><M l={t.reserved} v={s.reserved}/><M l={t.rented} v={s.rented}/><M l={t.leads} v={s.leads}/><M l={t.viewing} v={`${s.viewingConversionRate}%`}/><M l={t.won} v={`${s.winRate}%`}/><M l={t.response} v={s.averageResponseMinutes==null?"—":`${s.averageResponseMinutes} ${t.minutes}`}/><M l={t.upcoming} v={s.upcomingViewings}/></div>{x&&<section style={{marginTop:9,padding:9,borderRadius:12,background:"#f8faf9"}}><b style={{fontSize:18}}>{t.funnel}</b><div style={{...grid,marginTop:6}}><M l={t.new} v={f.new||0}/><M l={t.contacted} v={f.contacted||0}/><M l={t.viewingS} v={f.viewing||0}/><M l={t.negotiating} v={f.negotiating||0}/><M l={t.wonS} v={f.won||0}/><M l={t.lost} v={f.lost||0}/></div></section>}</section>}
function M({l,v}:{l:string;v:string|number}){return <div style={{padding:8,border:"1px solid #edf1ef",borderRadius:11,background:"#fff"}}><small style={{display:"block",fontSize:18,color:"#64748b"}}>{l}</small><b style={{fontSize:18}}>{v}</b></div>}
const grid={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(90px,1fr))",gap:6,marginTop:9} as const;const pill=(a:boolean)=>({border:"1px solid #dbe4df",borderRadius:999,padding:"5px 7px",background:a?"#07c160":"#fff",color:a?"#fff":"#111",fontSize:18,fontWeight:850});
