"use client";
import{useCallback,useEffect,useMemo,useState}from"react";import{useZhaoXiLocale}from"@zhaoxi/i18n";import HousingMessageThread from"./HousingMessageThread";
type Appointment={status:"proposed"|"confirmed"|"completed"|"cancelled";scheduledAt:string;proposedBy:"customer"|"partner";note?:string|null;reminderAt?:string|null};
type History={id?:string;actorRole?:string;action?:string;at?:string;note?:string|null;scheduledAt?:string|null};
type Lead={id:string;requestCode:string;status:string;customerName:string;customerPhone?:string|null;createdAt:string;details?:Record<string,unknown>};
type Stage="new"|"contacted"|"viewing"|"negotiating"|"won"|"lost";
const stages:Stage[]=["new","contacted","viewing","negotiating","won","lost"];
const C={
"zh-CN":{title:"租房客户线索",new:"新意向",contacted:"已联系",viewing:"看房",negotiating:"洽谈",won:"已成交",lost:"已结束",move:"入住",budget:"预算",next:"推进",note:"跟进备注",empty:"暂无租房线索",appointment:"看房预约",customerProposed:"客户提出看房时间",confirm:"确认时间",reschedule:"建议新时间",complete:"完成看房",cancel:"取消预约",time:"看房时间",send:"发送",proposed:"待确认",confirmed:"已确认",completed:"已完成",cancelled:"已取消",history:"跟进记录",reminder:"看房前 2 小时提醒",system:"系统"},
"zh-TW":{title:"租房客戶線索",new:"新意向",contacted:"已聯絡",viewing:"看房",negotiating:"洽談",won:"已成交",lost:"已結束",move:"入住",budget:"預算",next:"推進",note:"跟進備註",empty:"暫無租房線索",appointment:"看房預約",customerProposed:"客戶提出看房時間",confirm:"確認時間",reschedule:"建議新時間",complete:"完成看房",cancel:"取消預約",time:"看房時間",send:"送出",proposed:"待確認",confirmed:"已確認",completed:"已完成",cancelled:"已取消",history:"跟進記錄",reminder:"看房前 2 小時提醒",system:"系統"},
"vi-VN":{title:"Pipeline khách thuê nhà",new:"Yêu cầu mới",contacted:"Đã liên hệ",viewing:"Hẹn xem nhà",negotiating:"Thương lượng",won:"Đã chốt",lost:"Đã kết thúc",move:"Vào ở",budget:"Ngân sách",next:"Chuyển giai đoạn",note:"Ghi chú theo dõi",empty:"Chưa có lead thuê nhà",appointment:"Lịch xem nhà",customerProposed:"Customer đã đề xuất lịch xem nhà",confirm:"Xác nhận lịch",reschedule:"Đề xuất lịch khác",complete:"Hoàn tất xem nhà",cancel:"Hủy lịch",time:"Thời gian xem nhà",send:"Gửi",proposed:"Chờ xác nhận",confirmed:"Đã xác nhận",completed:"Đã xem",cancelled:"Đã hủy",history:"Lịch sử follow-up",reminder:"Đánh dấu nhắc trước 2 giờ",system:"Hệ thống"},
"en-US":{title:"Housing lead pipeline",new:"New",contacted:"Contacted",viewing:"Viewing",negotiating:"Negotiating",won:"Won",lost:"Closed",move:"Move-in",budget:"Budget",next:"Move stage",note:"Follow-up note",empty:"No housing leads",appointment:"Viewing appointment",customerProposed:"Customer proposed a viewing time",confirm:"Confirm time",reschedule:"Propose new time",complete:"Complete viewing",cancel:"Cancel appointment",time:"Viewing time",send:"Send",proposed:"Awaiting confirmation",confirmed:"Confirmed",completed:"Completed",cancelled:"Cancelled",history:"Follow-up history",reminder:"Marked for reminder 2 hours before",system:"System"}} as const;
const money=(v:unknown)=>`${Number(v||0).toLocaleString("vi-VN")} VND`;
const localInput=(iso?:string)=>{if(!iso)return"";const d=new Date(iso);if(Number.isNaN(d.getTime()))return"";const off=d.getTimezoneOffset();return new Date(d.getTime()-off*60000).toISOString().slice(0,16)};
const showDate=(iso?:string)=>iso?new Date(iso).toLocaleString():"—";

export default function HousingLeadPipeline({organizationId}:{organizationId:string}){
 const{locale}=useZhaoXiLocale(),t=C[locale];const[rows,setRows]=useState<Lead[]>([]),[busy,setBusy]=useState(""),[notes,setNotes]=useState<Record<string,string>>({}),[times,setTimes]=useState<Record<string,string>>({});
 const load=useCallback(async()=>{if(!organizationId)return;const r=await fetch(`/api/partner-housing-leads?organizationId=${encodeURIComponent(organizationId)}`,{cache:"no-store"}),j=await r.json();if(j?.ok)setRows(j.data||[])},[organizationId]);
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),12000);return()=>clearInterval(timer)},[load]);
 const grouped=useMemo(()=>Object.fromEntries(stages.map(s=>[s,rows.filter(r=>String(r.details?.housingLeadStage||"new")===s)])) as Record<Stage,Lead[]>,[rows]);
 async function move(row:Lead,stage:Stage){setBusy(row.id+stage);try{await fetch(`/api/partner-housing-leads/${row.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({organizationId,stage,note:notes[row.id]||""})});setNotes(v=>({...v,[row.id]:""}));await load()}finally{setBusy("")}}
 async function appointment(row:Lead,action:"confirm"|"reschedule"|"complete"|"cancel"|"note",scheduledAt?:string){setBusy(row.id+action);try{const payload:any={organizationId,action,note:notes[row.id]||""};if(scheduledAt)payload.scheduledAt=new Date(scheduledAt).toISOString();const r=await fetch(`/api/partner-housing-leads/${row.id}/appointment`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});if(r.ok){setNotes(v=>({...v,[row.id]:""}));setTimes(v=>({...v,[row.id]:""}));await load()}}finally{setBusy("")}}
 if(!rows.length)return null;
 return <section className="zx-native-workspace zx-native-complete" style={{margin:"16px 0",padding:20,border:"1px solid #dfe8e3",borderRadius:18,background:"#f8faf9"}}><h2 style={{margin:"0 0 10px",fontSize:18}}>🏠 {t.title}</h2><div style={{display:"grid",gridTemplateColumns:"repeat(6,minmax(230px,1fr))",gap:8,overflowX:"auto",paddingBottom:4}}>{stages.map(stage=><section key={stage} style={{minWidth:230,background:"#fff",border:"1px solid #e8eeeb",borderRadius:14,padding:8}}><header style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:7}}><b style={{fontSize:18}}>{t[stage]}</b><span style={{fontSize:18,padding:"3px 6px",borderRadius:999,background:"#eef2f6"}}>{grouped[stage].length}</span></header><div style={{display:"grid",gap:7}}>{grouped[stage].map(r=>{const d=r.details||{},appt=(d.housingAppointment&&typeof d.housingAppointment==="object"?d.housingAppointment:null) as Appointment|null,history=Array.isArray(d.housingFollowupHistory)?d.housingFollowupHistory.filter(x=>x&&typeof x==="object") as History[]:[],messages=Array.isArray(d.housingMessages)?d.housingMessages.filter(x=>x&&typeof x==="object") as any[]:[];return <article key={r.id} style={{padding:8,border:"1px solid #edf1ef",borderRadius:11}}><b style={{fontSize:18}}>{r.customerName}</b><small style={{display:"block",color:"#64748b",marginTop:2}}>{r.customerPhone||"—"}</small><small style={{display:"block",marginTop:5}}>{t.move}: {String(d.requestedMoveInDate||"—")}</small><small style={{display:"block"}}>{t.budget}: {d.budget?money(d.budget):"—"}</small>
 <section style={{marginTop:7,padding:7,borderRadius:10,background:"#f8faf9"}}><div style={{display:"flex",justifyContent:"space-between",gap:5}}><b style={{fontSize:18}}>📅 {t.appointment}</b><span style={{fontSize:18,fontWeight:850}}>{appt?String(t[appt.status]):"—"}</span></div>{appt&&<><small style={{display:"block",marginTop:4}}>{t.time}: {showDate(appt.scheduledAt)}</small>{appt.status==="confirmed"&&appt.reminderAt&&<small style={{display:"block",color:"#078343"}}>⏰ {t.reminder}</small>}{appt.status==="proposed"&&appt.proposedBy==="customer"&&<small style={{display:"block",marginTop:4,color:"#1d4ed8"}}>{t.customerProposed}</small>}<div style={{display:"flex",gap:5,flexWrap:"wrap",marginTop:5}}>{appt.status==="proposed"&&appt.proposedBy==="customer"&&<button disabled={!!busy} onClick={()=>void appointment(r,"confirm")} style={good}>{t.confirm}</button>}{appt.status==="confirmed"&&<button disabled={!!busy} onClick={()=>void appointment(r,"complete")} style={good}>{t.complete}</button>}{!["completed","cancelled"].includes(appt.status)&&<button disabled={!!busy} onClick={()=>void appointment(r,"cancel")} style={danger}>{t.cancel}</button>}</div></>}
 <div style={{display:"grid",gap:4,marginTop:6}}><input type="datetime-local" min={localInput(new Date(Date.now()+5*60000).toISOString())} value={times[r.id]||""} onChange={e=>setTimes(v=>({...v,[r.id]:e.target.value}))} style={input}/><button disabled={!times[r.id]||!!busy} onClick={()=>void appointment(r,"reschedule",times[r.id])} style={neutral}>{t.reschedule}</button></div></section>
 <HousingMessageThread organizationId={organizationId} requestId={r.id} messages={messages} onChanged={()=>void load()}/>
 <input value={notes[r.id]||""} onChange={e=>setNotes(v=>({...v,[r.id]:e.target.value}))} placeholder={t.note} style={{...input,marginTop:6}}/><select disabled={busy.startsWith(r.id)} defaultValue="" onChange={e=>{if(e.target.value)void move(r,e.target.value as Stage);e.currentTarget.value=""}} style={{...input,marginTop:5}}><option value="">{t.next}</option>{stages.filter(s=>s!==stage).map(s=><option key={s} value={s}>{t[s]}</option>)}</select>
 {history.length>0&&<details style={{marginTop:6}}><summary style={{fontSize:18,fontWeight:850,cursor:"pointer"}}>{t.history} · {history.length}</summary><div style={{display:"grid",gap:3,marginTop:4}}>{[...history].reverse().slice(0,8).map((h,i)=><small key={h.id||i} style={{padding:4,borderRadius:6,background:"#fff"}}>{String(h.actorRole||"")} · {String(h.action||"")} · {h.at?new Date(h.at).toLocaleString():""}{h.note&&<span> · {String(h.note)}</span>}</small>)}</div></details>}
 </article>})}</div></section>)}</div></section>
}
const input={width:"100%",boxSizing:"border-box",border:"1px solid #dbe5df",borderRadius:8,padding:6,fontSize:18} as const;
const good={border:0,borderRadius:8,padding:"10px 12px",background:"#07c160",color:"#fff",fontWeight:850,fontSize:18} as const;
const neutral={border:0,borderRadius:8,padding:"10px 12px",background:"#eff6ff",color:"#1d4ed8",fontWeight:850,fontSize:18} as const;
const danger={border:0,borderRadius:8,padding:"10px 12px",background:"#fff1f2",color:"#b42318",fontWeight:850,fontSize:18} as const;
