"use client";
import{useEffect,useMemo,useState}from"react";import{useZhaoXiLocale}from"@zhaoxi/i18n";
type Message={id:string;senderRole:"customer"|"partner";body:string;createdAt:string;customerReadAt?:string|null;partnerReadAt?:string|null};
const C={
"zh-CN":{title:"客户消息",placeholder:"回复客户…",send:"发送",me:"我",customer:"客户",empty:"暂无消息",unread:"新消息"},
"zh-TW":{title:"客戶訊息",placeholder:"回覆客戶…",send:"傳送",me:"我",customer:"客戶",empty:"暫無訊息",unread:"新訊息"},
"vi-VN":{title:"Tin nhắn Customer",placeholder:"Trả lời Customer…",send:"Gửi",me:"Partner",customer:"Customer",empty:"Chưa có tin nhắn",unread:"Tin mới"},
"en-US":{title:"Customer messages",placeholder:"Reply to customer…",send:"Send",me:"Partner",customer:"Customer",empty:"No messages yet",unread:"New"}} as const;
export default function HousingMessageThread({organizationId,requestId,messages,onChanged}:{organizationId:string;requestId:string;messages:Message[];onChanged:()=>void}){const{locale}=useZhaoXiLocale(),t=C[locale];const[text,setText]=useState(""),[busy,setBusy]=useState(false);const unread=useMemo(()=>messages.filter(m=>m.senderRole==="customer"&&!m.partnerReadAt).length,[messages]);
 useEffect(()=>{if(!unread)return;fetch(`/api/partner-housing-leads/${requestId}/messages`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({organizationId})}).then(()=>onChanged()).catch(()=>{})},[organizationId,requestId,unread]);
 async function send(){if(!text.trim())return;setBusy(true);try{const r=await fetch(`/api/partner-housing-leads/${requestId}/messages`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({organizationId,message:text})});if(r.ok){setText("");onChanged()}}finally{setBusy(false)}}
 return <section style={{marginTop:7,padding:7,borderRadius:10,background:"#fff",border:"1px solid #edf1ef"}}><div style={{display:"flex",justifyContent:"space-between"}}><b style={{fontSize:18}}>💬 {t.title}</b>{unread>0&&<span style={{fontSize:18,color:"#b42318",fontWeight:900}}>{t.unread} {unread}</span>}</div><div style={{display:"grid",gap:4,maxHeight:145,overflowY:"auto",marginTop:5}}>{!messages.length?<small style={{color:"#94a3b8"}}>{t.empty}</small>:messages.slice(-20).map(m=><div key={m.id} style={{justifySelf:m.senderRole==="partner"?"end":"start",maxWidth:"86%",padding:"5px 6px",borderRadius:8,background:m.senderRole==="partner"?"#dcfce7":"#f1f5f9",fontSize:18}}><b>{m.senderRole==="partner"?t.me:t.customer}</b><div>{m.body}</div><small style={{color:"#64748b"}}>{new Date(m.createdAt).toLocaleString()}</small></div>)}</div><div style={{display:"grid",gridTemplateColumns:"1fr auto",gap:4,marginTop:5}}><input value={text} onChange={e=>setText(e.target.value)} placeholder={t.placeholder} maxLength={2000} style={{border:"1px solid #dbe5df",borderRadius:8,padding:6,fontSize:18}}/><button disabled={busy||!text.trim()} onClick={()=>void send()} style={{border:0,borderRadius:8,padding:"10px 12px",background:"#07c160",color:"#fff",fontWeight:850,fontSize:18}}>{t.send}</button></div></section>
}
