"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {useZhaoXiSession} from "@zhaoxi/auth";
import {createZhaoXiSdk,type ServiceRequestRow} from "@zhaoxi/sdk";
import {statusLabels,useZhaoXiLocale} from "@zhaoxi/i18n";
import {ActionButton,EmptyState,MetricCard,StatusBadge,Surface,appShellStyle} from "@zhaoxi/ui";
import {getCached,setCached} from "./_lib/client-cache";
import PartnerWorkspaceNav from "./PartnerWorkspaceNav";
import PartnerOrderAlerts from "./PartnerOrderAlerts";
import HousingLeadPipeline from "./HousingLeadPipeline";
import HousingAnalyticsDashboard from "./HousingAnalyticsDashboard";
import TravelLeadPipeline from "./TravelLeadPipeline";
import TravelPlatformFeeOverview from "./TravelPlatformFeeOverview";
import PartnerPaymentGatewaySettings from "./PartnerPaymentGatewaySettings";
import PartnerPaymentFailoverSettings from "./PartnerPaymentFailoverSettings";
import PartnerPaymentOperationsPanel from "./PartnerPaymentOperationsPanel";
import PartnerPaymentSupportPanel from "./PartnerPaymentSupportPanel";
import PartnerPaymentSupportAnalytics from "./PartnerPaymentSupportAnalytics";
import PartnerQualityRiskCard from "./PartnerQualityRiskCard";
import PartnerComplianceCases from "./PartnerComplianceCases";
import PartnerTrustProfile from "./PartnerTrustProfile";
import PartnerVerificationBadges from "./PartnerVerificationBadges";
import PartnerPublicStorefrontSettings from "./PartnerPublicStorefrontSettings";
import PartnerPaymentTransactionPanel from "./PartnerPaymentTransactionPanel";
import KitchenQueue from "./KitchenQueue";
import {paymentMethodLabel,paymentStatusLabel} from "@zhaoxi/payment";

const sdk=createZhaoXiSdk();
const copy={
"zh-CN":{title:"合作伙伴服务中心",subtitle:"统一管理餐饮订单、租房咨询及其他合作伙伴服务请求。",waiting:"待接单",preparing:"备餐中",ready:"待取餐",requests:"服务订单",refresh:"刷新",empty:"暂无新订单",accept:"接单",start:"开始备餐",readyAction:"餐品已备好",courier:"登记配送员",handoff:"已交接配送",delivered:"已送达",cancel:"取消订单",quantity:"数量",items:"商品金额",itemOriginal:"商品原价",itemDiscount:"菜品优惠",couponDiscount:"优惠券优惠",gross:"配送费原价",subsidy:"商家配送补贴",customerShip:"客户配送费",total:"订单总额",distance:"配送距离",courierName:"配送员/平台",courierPhone:"联系电话",courierRef:"配送单号",saveCourier:"保存配送信息",external:"外部配送",missing:"缺少联系电话或地址",housingInquiry:"租房意向",moveIn:"入住日期",lease:"租期",occupants:"入住人数",budget:"预算",contactPref:"优先联系",housingAccept:"接收意向",housingStart:"开始联系客户",housingComplete:"完成跟进",housingReject:"无法承接",bookCourier:"预约",customerDirectShip:"客户自付运费",courierModalHint:"此订单客户选择通过外部平台配送，运费由客户直接支付给骑手。"},
"zh-TW":{title:"合作夥伴服務中心",subtitle:"統一管理餐飲訂單、租房諮詢與其他合作夥伴服務請求。",waiting:"待接單",preparing:"備餐中",ready:"待取餐",requests:"服務訂單",refresh:"重新整理",empty:"暫無新訂單",accept:"接單",start:"開始備餐",readyAction:"餐點已備好",courier:"登記配送員",handoff:"已交接配送",delivered:"已送達",cancel:"取消訂單",quantity:"數量",items:"商品金額",itemOriginal:"商品原價",itemDiscount:"餐點優惠",couponDiscount:"優惠券優惠",gross:"配送費原價",subsidy:"商家配送補貼",customerShip:"客戶配送費",total:"訂單總額",distance:"配送距離",courierName:"配送員/平台",courierPhone:"聯絡電話",courierRef:"配送單號",saveCourier:"儲存配送資訊",external:"外部配送",missing:"缺少聯絡電話或地址",housingInquiry:"租房意向",moveIn:"入住日期",lease:"租期",occupants:"入住人數",budget:"預算",contactPref:"優先聯絡",housingAccept:"接收意向",housingStart:"開始聯絡客戶",housingComplete:"完成跟進",housingReject:"無法承接",bookCourier:"預約",customerDirectShip:"客戶自付運費",courierModalHint:"此訂單客戶選擇透過外部平台配送，運費由客戶直接支付給外送員。"},
"vi-VN":{title:"Trung tâm xử lý dịch vụ",subtitle:"Quản lý tập trung đơn món ăn, yêu cầu thuê nhà và các dịch vụ Partner khác.",waiting:"Chờ nhận",preparing:"Đang chuẩn bị",ready:"Chờ lấy món",requests:"Đơn nhà hàng",refresh:"Làm mới",empty:"Chưa có đơn mới",accept:"Nhận đơn",start:"Bắt đầu chuẩn bị",readyAction:"Món đã sẵn sàng",courier:"Ghi nhận đơn vị giao",handoff:"Đã bàn giao",delivered:"Đã giao đến khách",cancel:"Hủy đơn",quantity:"Số lượng",items:"Tiền món",itemOriginal:"Giá món gốc",itemDiscount:"Ưu đãi món",couponDiscount:"Giảm bằng coupon",gross:"Phí giao hàng gốc",subsidy:"Nhà hàng trợ giá",customerShip:"Khách trả phí giao",total:"Tổng đơn",distance:"Quãng đường",courierName:"Đơn vị/Người giao",courierPhone:"Số điện thoại",courierRef:"Mã chuyến giao",saveCourier:"Lưu thông tin giao",external:"Giao hàng bên ngoài",missing:"Thiếu số điện thoại hoặc địa chỉ",housingInquiry:"Yêu cầu thuê nhà",moveIn:"Ngày vào ở",lease:"Thời gian thuê",occupants:"Số người ở",budget:"Ngân sách",contactPref:"Ưu tiên liên hệ",housingAccept:"Nhận yêu cầu",housingStart:"Bắt đầu liên hệ khách",housingComplete:"Hoàn tất tư vấn",housingReject:"Không thể tiếp nhận",bookCourier:"Book",customerDirectShip:"Khách tự trả ship",courierModalHint:"Đơn này khách yêu cầu ship qua đối tác giao hàng, tiền ship khách tự thanh toán cho tài xế."},
"en-US":{title:"Partner service center",subtitle:"Manage food orders, housing inquiries and other Partner service requests in one place.",waiting:"Waiting",preparing:"Preparing",ready:"Ready for pickup",requests:"Restaurant orders",refresh:"Refresh",empty:"No new orders",accept:"Accept",start:"Start preparing",readyAction:"Food ready",courier:"Add courier",handoff:"Handed off",delivered:"Delivered",cancel:"Cancel order",quantity:"Quantity",items:"Items",itemOriginal:"Original items",itemDiscount:"Food promotion",couponDiscount:"Coupon discount",gross:"Gross delivery fee",subsidy:"Restaurant subsidy",customerShip:"Customer delivery fee",total:"Order total",distance:"Distance",courierName:"Courier/provider",courierPhone:"Phone",courierRef:"Delivery reference",saveCourier:"Save courier",external:"External delivery",missing:"Missing phone or address",housingInquiry:"Rental inquiry",moveIn:"Move-in",lease:"Lease",occupants:"Occupants",budget:"Budget",contactPref:"Preferred contact",housingAccept:"Accept inquiry",housingStart:"Start contacting customer",housingComplete:"Complete follow-up",housingReject:"Cannot accept",bookCourier:"Book",customerDirectShip:"Customer pays courier",courierModalHint:"This order uses 3rd-party delivery; customer pays the delivery fee directly to the courier."}
} as const;
const money=(v:unknown)=>Number(v||0).toLocaleString("vi-VN")+" VND";

export default function OperationsBoard(){
 const session=useZhaoXiSession();const{locale}=useZhaoXiLocale();const t=copy[locale];const orgId=session?.organizationId||"";
 const cacheKey=`partner_requests_${orgId}_${locale}`;
 const[rows,setRows]=useState<ServiceRequestRow[]>(()=>getCached<ServiceRequestRow[]>(cacheKey)||[]);
 const[loading,setLoading]=useState(()=>getCached<ServiceRequestRow[]>(cacheKey)===null);
 const[busy,setBusy]=useState("");const[error,setError]=useState("");const[courierOrder,setCourierOrder]=useState<ServiceRequestRow|null>(null);const[courier,setCourier]=useState({courierName:"",courierPhone:"",courierReference:""});
 const load=useCallback(async()=>{if(!orgId){setLoading(false);return}try{const r=await sdk.listRequests({scope:"operations",organizationId:orgId,locale});const next=r.data||[];setRows(next);setCached(cacheKey,next);setError("")}catch(e){const msg=e instanceof Error?e.message:"ERROR";setError(msg.includes("<!DOCTYPE")||msg.includes("Unexpected token")?"Hệ thống đang đồng bộ. Vui lòng thử lại sau vài giây.":msg)}finally{setLoading(false)}},[orgId,locale,cacheKey]);
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),8000);return()=>clearInterval(timer)},[load]);
 const metrics=useMemo(()=>({waiting:rows.filter(r=>r.status==="assigned").length,preparing:rows.filter(r=>String(r.details?.fulfillmentStage||"")==="preparing").length,ready:rows.filter(r=>["ready_for_pickup","courier_booked"].includes(String(r.details?.fulfillmentStage||""))).length}),[rows]);
 async function genericUpdate(row:ServiceRequestRow,status:"accepted"|"in_progress"|"waiting_customer"|"completed"|"rejected"){setBusy(row.id+status);setError("");try{await sdk.updateStatus(row.id,status,`partner:${status}`);await load()}catch(e){const msg=e instanceof Error?e.message:"UPDATE_FAILED";setError(msg.includes("<!DOCTYPE")||msg.includes("Unexpected token")?"Hệ thống đang đồng bộ. Vui lòng thử lại sau vài giây.":msg)}finally{setBusy("")}}
 async function action(row:ServiceRequestRow,action:string,extra:Record<string,unknown>={}){setBusy(row.id+action);setError("");try{const r=await fetch(`/api/partner-fulfillment/${row.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action,...extra})});const j=await r.json().catch(()=>null);if(!r.ok||!j?.ok)throw new Error(j?.error?.code||"FULFILLMENT_FAILED");await load()}catch(e){const msg=e instanceof Error?e.message:"FULFILLMENT_FAILED";setError(msg.includes("<!DOCTYPE")||msg.includes("Unexpected token")?"Hệ thống đang đồng bộ. Vui lòng thử lại sau vài giây.":msg)}finally{setBusy("")}}
 async function saveCourier(){if(!courierOrder)return;await action(courierOrder,"courier_booked",courier);setCourierOrder(null);setCourier({courierName:"",courierPhone:"",courierReference:""})}
 return <main className="zx-native-workspace" style={{...appShellStyle,maxWidth:1180,margin:"0 auto",padding:"24px 18px"}}>
  <header style={{textAlign:"center",padding:"10px 0 4px"}}><small style={{color:"#07c160",fontWeight:900}}>ZHAOXI PARTNER</small><h1 style={{margin:"7px 0 6px"}}>{t.title}</h1><p style={{margin:0,color:"#64748b"}}>{t.subtitle}</p></header>
  <PartnerWorkspaceNav/>
  <KitchenQueue organizationId={orgId}/>
  <section style={{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:12}}><MetricCard label={t.waiting} value={metrics.waiting}/><MetricCard label={t.preparing} value={metrics.preparing}/><MetricCard label={t.ready} value={metrics.ready}/></section>
  <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",margin:"26px 0 12px"}}><h2>{t.requests}</h2><ActionButton tone="neutral" onClick={()=>void load()}>{t.refresh}</ActionButton></div>
  {error&&<p style={{background:"#fff1f2",color:"#be123c",padding:20,borderRadius:12}}>{error}</p>}
  {loading?<p>…</p>:!rows.length?<Surface><EmptyState title={t.empty}/></Surface>:<section style={{display:"grid",gap:12}}>{rows.map(r=>{const d=r.details||{};const stage=String(d.fulfillmentStage||"");const external=d.deliveryFulfillmentMode==="external_manual";const housing=r.moduleCode==="housing"&&d.inquiryType==="rental_inquiry";const displayPhone=(typeof d.recipientPhone==="string"&&d.recipientPhone.trim())?d.recipientPhone.trim():(r.customerPhone||"—");const isFriend=Boolean(typeof d.recipientPhone==="string"&&d.recipientPhone.trim()&&d.recipientPhone.trim()!==r.customerPhone);const valid=Boolean(displayPhone!=="—"&&r.addressText?.trim());return <Surface key={r.id}><div style={{display:"flex",justifyContent:"space-between",gap:10,flexWrap:"wrap"}}><b>{r.requestCode}</b><StatusBadge>{statusLabels[locale][r.status]||r.status}</StatusBadge></div><h3>{r.serviceName||r.title}</h3><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:10,padding:"9px 12px",borderRadius:12,background:"#f0fdf4",border:"1px solid #bbf7d0",margin:"8px 0",flexWrap:"wrap"}}><span style={{color:"#166534",fontSize:13,fontWeight:700}}>👤 {r.customerName}</span><a href={`tel:${displayPhone}`} style={{display:"inline-flex",alignItems:"center",gap:5,background:"#07c160",color:"#fff",padding:"5px 12px",borderRadius:999,textDecoration:"none",fontSize:13,fontWeight:800}}>📞 {displayPhone}{isFriend?" (Nhận hộ)":""}</a></div><p style={{color:valid?"#64748b":"#be123c",fontSize:13,margin:"4px 0"}}>📍 {r.addressText||t.missing}</p>{external&&<small style={{display:"inline-flex",padding:"4px 8px",borderRadius:999,background:"#ecfdf5",color:"#067647",fontWeight:800}}>{t.external} · {stage||"assigned"}</small>}{Boolean(d.deliveryProvider)&&<small style={{display:"inline-flex",alignItems:"center",gap:6,padding:"3px 8px",borderRadius:999,background:d.deliveryProvider==="grab"?"#dcfce7":"#ccfbf1",color:d.deliveryProvider==="grab"?"#15803d":"#0f766e",fontWeight:850}}><img src={d.deliveryProvider==="grab"?"/couriers/grab.png":"/couriers/green-sm.png"} alt={d.deliveryProvider==="grab"?"Grab":"Green SM"} style={{height:14,width:"auto",objectFit:"contain",verticalAlign:"middle"}}/><span>{t.bookCourier} {d.deliveryProvider==="grab"?"Grab":"Xanh SM"} ({t.customerDirectShip})</span></small>}{housing&&<small style={{display:"inline-flex",padding:"4px 8px",borderRadius:999,background:"#eff6ff",color:"#1d4ed8",fontWeight:800}}>{t.housingInquiry}</small>}
    {housing&&<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(145px,1fr))",gap:7,padding:"10px 0",fontSize:18}}><span>{t.moveIn}: <b>{String(d.requestedMoveInDate||"—")}</b></span><span>{t.lease}: <b>{d.requestedLeaseMonths?`${String(d.requestedLeaseMonths)} ${locale==="vi-VN"?"tháng":locale==="en-US"?"months":"个月"}`:"—"}</b></span><span>{t.occupants}: <b>{String(d.occupants||1)}</b></span><span>{t.budget}: <b>{d.budget?money(d.budget):"—"}</b></span><span>{t.contactPref}: <b>{String(d.preferredContact||"phone")}</b></span>{Boolean(d.wechat)&&<span>WeChat: <b>{String(d.wechat)}</b></span>}{Boolean(d.whatsapp)&&<span>WhatsApp: <b>{String(d.whatsapp)}</b></span>}</div>}
    {!housing&&<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(145px,1fr))",gap:8,padding:"12px 0",marginTop:10,borderTop:"1px solid #edf0ee",borderBottom:"1px solid #edf0ee"}}><span>{t.quantity}: <b>{String(d.quantity||1)}</b></span><span>{Number(d.itemDiscount||0)>0?t.itemOriginal:t.items}: <b>{money(Number(d.itemDiscount||0)>0?d.itemBaseSubtotal:(d.itemSubtotalBeforeCoupon??d.itemSubtotal))}</b></span>{Number(d.itemDiscount||0)>0&&<span style={{color:"#c2410c"}}>{t.itemDiscount}: <b>−{money(d.itemDiscount)}</b></span>}{Number(d.couponDiscount||0)>0&&<span style={{color:"#c2410c"}}>{t.couponDiscount}{d.couponCode?` (${String(d.couponCode)})`:""}: <b>−{money(d.couponDiscount)}</b></span>}{d.deliveryGrossFee!=null&&<span>{t.gross}: <b>{money(d.deliveryGrossFee)}</b></span>}{Number(d.deliverySubsidy||0)>0&&<span style={{color:"#078343"}}>{t.subsidy}: <b>−{money(d.deliverySubsidy)}</b></span>}{d.deliveryCustomerFee!=null&&<span>{t.customerShip}: <b>{d.deliveryPricingMode==="customer_direct_pay"?"Khách tự trả":money(d.deliveryCustomerFee)}</b></span>}{d.deliveryDistanceKm!=null&&<span>{t.distance}: <b>{Number(d.deliveryDistanceKm).toFixed(1)} km</b></span>}{d.totalAmount!=null&&<span>{t.total}: <b style={{color:"#07a856"}}>{money(d.totalAmount)}</b></span>}{Boolean(d.paymentStatus)&&<span>💳 <b>{paymentMethodLabel(String(d.paymentMethod||"cash_on_delivery"),locale)}</b> · {paymentStatusLabel(String(d.paymentStatus),locale)}</span>}</div>}
    <div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:12}}>{external?<>{r.status==="assigned"&&<ActionButton disabled={!!busy||!valid} onClick={()=>window.dispatchEvent(new CustomEvent("zhaoxi-open-order",{detail:r}))}>{t.accept}</ActionButton>}{r.status==="in_progress"&&(!stage||stage==="preparing")&&<ActionButton disabled={!!busy} onClick={()=>void action(r,"ready_for_pickup")}>{t.readyAction}</ActionButton>}{stage==="ready_for_pickup"&&<ActionButton disabled={!!busy} onClick={()=>{setCourierOrder(r);const p=String(d.deliveryProviderLabel||(d.deliveryProvider==="grab"?"Grab":d.deliveryProvider==="green_sm"?"Xanh SM":""));setCourier({courierName:p,courierPhone:"",courierReference:""})}}>{t.courier}</ActionButton>}{stage==="courier_booked"&&<ActionButton disabled={!!busy} onClick={()=>void action(r,"handed_off")}>{t.handoff}</ActionButton>}{stage==="handed_off"&&<ActionButton tone="dark" disabled={!!busy} onClick={()=>void action(r,"delivered")}>{t.delivered}</ActionButton>}{!["completed","cancelled","rejected"].includes(r.status)&&<ActionButton tone="danger" disabled={!!busy} onClick={()=>void action(r,"cancelled")}>{t.cancel}</ActionButton>}</>:housing?<>{r.status==="assigned"&&<ActionButton disabled={!!busy||!valid} onClick={()=>void genericUpdate(r,"accepted")}>{t.housingAccept}</ActionButton>}{r.status==="accepted"&&<ActionButton disabled={!!busy} onClick={()=>void genericUpdate(r,"in_progress")}>{t.housingStart}</ActionButton>}{r.status==="in_progress"&&<ActionButton tone="dark" disabled={!!busy} onClick={()=>void genericUpdate(r,"completed")}>{t.housingComplete}</ActionButton>}{!["completed","cancelled","rejected"].includes(r.status)&&<ActionButton tone="danger" disabled={!!busy} onClick={()=>void genericUpdate(r,"rejected")}>{t.housingReject}</ActionButton>}</>:<>{r.status==="assigned"&&<ActionButton disabled={!!busy||!valid} onClick={()=>void genericUpdate(r,"accepted")}>{t.accept}</ActionButton>}{r.status==="accepted"&&<ActionButton disabled={!!busy} onClick={()=>void genericUpdate(r,"in_progress")}>{t.start}</ActionButton>}{r.status==="in_progress"&&<ActionButton tone="dark" disabled={!!busy} onClick={()=>void genericUpdate(r,"completed")}>{t.delivered}</ActionButton>}{!["completed","cancelled","rejected"].includes(r.status)&&<ActionButton tone="danger" disabled={!!busy} onClick={()=>void genericUpdate(r,"rejected")}>{t.cancel}</ActionButton>}</>}</div>
   </Surface>})}</section>}
  <section className="zx-partner-home-shortcuts"><a href="/catalog">Dịch vụ</a><a href="/housing-inventory">Nhà ở</a><a href="/travel-inventory">Du lịch</a><a href="/settlements">Đối soát</a><a href="/tools">Công cụ</a></section>
  {courierOrder&&<div style={{position:"fixed",inset:0,zIndex:80,background:"rgba(15,23,42,.42)",display:"grid",placeItems:"center",padding:20}}><section style={{width:"min(100%,420px)",background:"#fff",borderRadius:20,padding:18,display:"grid",gap:10}}><h2 style={{margin:0}}>{t.courier}</h2>{Boolean(courierOrder.details?.deliveryProvider)&&<small style={{display:"block",color:"#067647",fontWeight:750,background:"#ecfdf5",border:"1px solid #bbf7d0",padding:"8px 12px",borderRadius:10}}>ℹ {t.courierModalHint}</small>}<label>{t.courierName}<input value={courier.courierName} onChange={e=>setCourier(v=>({...v,courierName:e.target.value}))}/></label><label>{t.courierPhone}<input value={courier.courierPhone} onChange={e=>setCourier(v=>({...v,courierPhone:e.target.value}))}/></label><label>{t.courierRef}<input value={courier.courierReference} onChange={e=>setCourier(v=>({...v,courierReference:e.target.value}))}/></label><div style={{display:"flex",gap:8}}><button onClick={()=>setCourierOrder(null)} style={{flex:1,padding:11,borderRadius:12,border:"1px solid #dbe4df",background:"#fff"}}>×</button><button onClick={()=>void saveCourier()} style={{flex:2,padding:11,borderRadius:12,border:0,background:"#07c160",color:"#fff",fontWeight:850}}>{t.saveCourier}</button></div></section></div>}
 </main>
}
