"use client";
import {useEffect,useMemo,useState} from "react";
import {useZhaoXiLocale} from "@zhaoxi/i18n";

type Day={enabled:boolean;open:string;close:string};
type Config={
 businessHoursEnabled:boolean;timezone:string;weeklyHours:Record<string,Day>;manualPaused:boolean;pauseReason:string;
 maxActiveKitchenOrders:number;autoPauseWhenCapacity:boolean;
};
type Status={open:boolean;code:string;activeKitchenOrders:number;capacityRemaining:number;config:Config;platformControl?:{paused:boolean;reason:string}};
const defaultConfig:Config={businessHoursEnabled:false,timezone:"Asia/Ho_Chi_Minh",weeklyHours:Object.fromEntries(Array.from({length:7},(_,i)=>[String(i),{enabled:true,open:"07:00",close:"22:00"}])),manualPaused:false,pauseReason:"",maxActiveKitchenOrders:30,autoPauseWhenCapacity:true};
const copy={
"zh-CN":{title:"营业与接单控制",hint:"设置营业时间、暂停接单和厨房容量。",hours:"按营业时间控制",pause:"暂停接单",pauseReason:"暂停原因",capacity:"厨房同时处理上限",autoCapacity:"达到上限时自动暂停新订单",timezone:"时区",save:"保存设置",saved:"已保存",open:"正在接单",manual_paused:"已暂停接单",closed_hours:"非营业时间",at_capacity:"厨房已满",orders:"厨房处理中",remaining:"剩余容量",days:["周日","周一","周二","周三","周四","周五","周六"],closed:"休息",platform_paused:"平台已暂停接单",platformReason:"平台原因"},
"zh-TW":{title:"營業與接單控制",hint:"設定營業時間、暫停接單與廚房容量。",hours:"依營業時間控制",pause:"暫停接單",pauseReason:"暫停原因",capacity:"廚房同時處理上限",autoCapacity:"達到上限時自動暫停新訂單",timezone:"時區",save:"儲存設定",saved:"已儲存",open:"正在接單",manual_paused:"已暫停接單",closed_hours:"非營業時間",at_capacity:"廚房已滿",orders:"廚房處理中",remaining:"剩餘容量",days:["週日","週一","週二","週三","週四","週五","週六"],closed:"休息",platform_paused:"平台已暫停接單",platformReason:"平台原因"},
"vi-VN":{title:"Giờ hoạt động & nhận đơn",hint:"Thiết lập giờ mở cửa, tạm ngưng nhận đơn và giới hạn công suất bếp.",hours:"Áp dụng giờ hoạt động",pause:"Tạm ngưng nhận đơn",pauseReason:"Lý do tạm ngưng",capacity:"Số đơn bếp tối đa cùng lúc",autoCapacity:"Tự ngưng nhận đơn khi bếp đạt giới hạn",timezone:"Múi giờ",save:"Lưu cài đặt",saved:"Đã lưu",open:"Đang nhận đơn",manual_paused:"Đang tạm ngưng",closed_hours:"Ngoài giờ hoạt động",at_capacity:"Bếp đang quá tải",orders:"Đơn đang xử lý",remaining:"Sức chứa còn lại",days:["Chủ nhật","Thứ hai","Thứ ba","Thứ tư","Thứ năm","Thứ sáu","Thứ bảy"],closed:"Nghỉ",platform_paused:"Platform đã tạm dừng nhận đơn",platformReason:"Lý do từ Platform"},
"en-US":{title:"Business hours & order control",hint:"Configure opening hours, order pause and kitchen capacity.",hours:"Enforce business hours",pause:"Pause new orders",pauseReason:"Pause reason",capacity:"Maximum concurrent kitchen orders",autoCapacity:"Automatically pause at kitchen capacity",timezone:"Timezone",save:"Save settings",saved:"Saved",open:"Accepting orders",manual_paused:"Orders paused",closed_hours:"Outside business hours",at_capacity:"Kitchen at capacity",orders:"Active kitchen orders",remaining:"Capacity remaining",days:["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],closed:"Closed",platform_paused:"Platform paused orders",platformReason:"Platform reason"}} as const;

export default function RestaurantOperationsPanel({organizationId}:{organizationId:string}){
 const{locale}=useZhaoXiLocale();const t=copy[locale];const[config,setConfig]=useState<Config>(defaultConfig);const[status,setStatus]=useState<Status|null>(null);const[msg,setMsg]=useState("");const[busy,setBusy]=useState(false);
 async function load(syncConfig=true){if(!organizationId)return;try{const r=await fetch(`/api/partner-restaurant-operations?organizationId=${encodeURIComponent(organizationId)}`,{cache:"no-store"});const j=await r.json();if(j?.ok){setStatus(j.data);if(syncConfig)setConfig({...defaultConfig,...j.data.config,weeklyHours:{...defaultConfig.weeklyHours,...(j.data.config?.weeklyHours||{})}})}}catch{}}
 useEffect(()=>{void load(true);const timer=setInterval(()=>void load(false),10000);return()=>clearInterval(timer)},[organizationId]);
 function dayPatch(day:string,patch:Partial<Day>){setConfig(v=>({...v,weeklyHours:{...v.weeklyHours,[day]:{...v.weeklyHours[day],...patch}}}))}
 async function save(){setBusy(true);setMsg("");try{const r=await fetch("/api/partner-restaurant-operations",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({organizationId,config})});const j=await r.json();if(!r.ok||!j?.ok)throw new Error(j?.error?.code||"SAVE_FAILED");setStatus(j.data.status);setConfig(j.data.config);setMsg(t.saved)}catch(e){setMsg(e instanceof Error?e.message:"SAVE_FAILED")}finally{setBusy(false)}}
 const statusText=status?t[status.code as keyof typeof t]||status.code:t.open;
 const badgeColor=status?.open?"#067647":"#b42318",badgeBg=status?.open?"#ecfdf5":"#fff1f2";
 const rows=useMemo(()=>Object.keys(config.weeklyHours).sort((a,b)=>Number(a)-Number(b)),[config.weeklyHours]);
 return <section style={{margin:"18px 0",padding:16,border:"1px solid #dfe7e3",borderRadius:18,background:"#fff",display:"grid",gap:14}}>
   <header style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"start"}}><div><h2 style={{margin:"0 0 5px"}}>{t.title}</h2><p style={{margin:0,color:"#64748b",fontSize:18}}>{t.hint}</p></div><span style={{padding:"6px 9px",borderRadius:999,background:badgeBg,color:badgeColor,fontSize:18,fontWeight:900,whiteSpace:"nowrap"}}>{statusText}</span></header>
   {status?.code==="platform_paused"&&<div style={{padding:10,borderRadius:12,background:"#fff1f2",color:"#b42318",fontSize:18,fontWeight:800}}>{t.platformReason}: {status.platformControl?.reason||t.platform_paused}</div>}
   <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(250px,1fr))",gap:8}}><div style={{padding:10,borderRadius:13,background:"#f8faf9"}}><small style={{color:"#64748b"}}>{t.orders}</small><b style={{display:"block",marginTop:4}}>{status?.activeKitchenOrders??0}</b></div><div style={{padding:10,borderRadius:13,background:"#f8faf9"}}><small style={{color:"#64748b"}}>{t.remaining}</small><b style={{display:"block",marginTop:4}}>{status?.capacityRemaining??config.maxActiveKitchenOrders}</b></div></div>
   <label style={check}><input type="checkbox" checked={config.manualPaused} onChange={e=>setConfig(v=>({...v,manualPaused:e.target.checked}))}/>{t.pause}</label>
   {config.manualPaused&&<label style={field}>{t.pauseReason}<input value={config.pauseReason} onChange={e=>setConfig(v=>({...v,pauseReason:e.target.value}))} maxLength={240}/></label>}
   <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:9}}><label style={field}>{t.capacity}<input type="number" min={1} max={200} value={config.maxActiveKitchenOrders} onChange={e=>setConfig(v=>({...v,maxActiveKitchenOrders:Math.max(1,Number(e.target.value)||1)}))}/></label><label style={field}>{t.timezone}<input value={config.timezone} onChange={e=>setConfig(v=>({...v,timezone:e.target.value}))}/></label></div>
   <label style={check}><input type="checkbox" checked={config.autoPauseWhenCapacity} onChange={e=>setConfig(v=>({...v,autoPauseWhenCapacity:e.target.checked}))}/>{t.autoCapacity}</label>
   <label style={check}><input type="checkbox" checked={config.businessHoursEnabled} onChange={e=>setConfig(v=>({...v,businessHoursEnabled:e.target.checked}))}/>{t.hours}</label>
   {config.businessHoursEnabled&&<section style={{display:"grid",gap:7}}>{rows.map(day=>{const d=config.weeklyHours[day];return <div key={day} style={{display:"grid",gridTemplateColumns:"90px 72px 1fr 1fr",gap:7,alignItems:"center",padding:"7px 0",borderBottom:"1px solid #eef2ef"}}><b style={{fontSize:18}}>{t.days[Number(day)]}</b><label style={{display:"flex",alignItems:"center",gap:5,fontSize:18}}><input type="checkbox" checked={d.enabled} onChange={e=>dayPatch(day,{enabled:e.target.checked})}/>{d.enabled?"ON":t.closed}</label><input type="time" disabled={!d.enabled} value={d.open} onChange={e=>dayPatch(day,{open:e.target.value})}/><input type="time" disabled={!d.enabled} value={d.close} onChange={e=>dayPatch(day,{close:e.target.value})}/></div>})}</section>}
   <button disabled={busy} onClick={()=>void save()} style={{border:0,borderRadius:13,padding:"11px 14px",background:"#07c160",color:"#fff",fontWeight:850}}>{busy?"…":t.save}</button>{msg&&<small style={{color:msg===t.saved?"#078343":"#b42318",fontWeight:800}}>{msg}</small>}
 </section>
}
const field={display:"grid",gap:5,fontSize:18,color:"#64748b"} as const;const check={display:"flex",alignItems:"center",gap:8,fontSize:18,fontWeight:750} as const;
