"use client";
import { useCallback,useEffect,useState } from "react";
import { Surface,ActionButton } from "@zhaoxi/ui";
import { useZhaoXiLocale } from "@zhaoxi/i18n";
import type { IncidentSummary,RuntimeEvent } from "@zhaoxi/observability";
const copy={
 "vi-VN":{title:"Trung tâm sự cố Beta",sub:"Theo dõi lỗi runtime của Customer, Partner, Admin và Driver.",total:"Sự kiện",unresolved:"Chưa xử lý",critical:"Nghiêm trọng",errors:"Lỗi",refresh:"Làm mới",empty:"Chưa ghi nhận lỗi runtime trong khoảng thời gian này.",hours:"Khoảng thời gian",h24:"24 giờ",h72:"72 giờ",h168:"7 ngày"},
 "en-US":{title:"Beta Incident Center",sub:"Runtime visibility across Customer, Partner, Admin and Driver.",total:"Events",unresolved:"Unresolved",critical:"Critical",errors:"Errors",refresh:"Refresh",empty:"No runtime errors recorded in this period.",hours:"Period",h24:"24 hours",h72:"72 hours",h168:"7 days"},
 "zh-CN":{title:"Beta 事故中心",sub:"统一查看顾客端、商家端、管理端和司机端运行错误。",total:"事件",unresolved:"未处理",critical:"严重",errors:"错误",refresh:"刷新",empty:"当前时间范围内没有运行错误。",hours:"时间范围",h24:"24小时",h72:"72小时",h168:"7天"},
 "zh-TW":{title:"Beta 事故中心",sub:"統一查看顧客端、商家端、管理端與司機端執行錯誤。",total:"事件",unresolved:"未處理",critical:"嚴重",errors:"錯誤",refresh:"重新整理",empty:"目前時間範圍沒有執行錯誤。",hours:"時間範圍",h24:"24小時",h72:"72小時",h168:"7天"}
} as const;
function Metric({label,value}:{label:string;value:number}){return <Surface style={{padding:14}}><small style={{color:"#64748b"}}>{label}</small><strong style={{display:"block",fontSize:24,marginTop:5}}>{value}</strong></Surface>}
function EventCard({e}:{e:RuntimeEvent}){const accent=e.severity==="critical"?"#be123c":e.severity==="error"?"#ea580c":"#0f766e";return <Surface style={{padding:14,borderLeft:`4px solid ${accent}`}}><div style={{display:"flex",justifyContent:"space-between",gap:8,flexWrap:"wrap"}}><b>{e.app} · {e.eventType}</b><code style={{fontSize:11}}>{e.severity}</code></div><p style={{margin:"8px 0",wordBreak:"break-word"}}>{e.message}</p><small style={{color:"#64748b"}}>{new Date(e.createdAt).toLocaleString()} {e.route?`· ${e.route}`:""} {e.digest?`· #${e.digest}`:""}</small></Surface>}
export default function IncidentCenter(){const{locale}=useZhaoXiLocale();const t=copy[locale];const[hours,setHours]=useState(24);const[data,setData]=useState<IncidentSummary|null>(null);const[error,setError]=useState("");const load=useCallback(async()=>{try{const r=await fetch(`/api/platform-observability?hours=${hours}`,{cache:"no-store"});const p=await r.json();if(!r.ok)throw new Error(p?.error?.message||"Load failed");setData(p.data);setError("")}catch(e){setError(e instanceof Error?e.message:"Load failed")}},[hours]);useEffect(()=>{void load();const timer=window.setInterval(load,30000);return()=>window.clearInterval(timer)},[load]);return <main style={{width:"min(100%,430px)",margin:"0 auto",minHeight:"100dvh",padding:"20px 14px 40px",background:"#f6faf7"}}><header style={{marginBottom:16}}><small style={{fontWeight:800,color:"#07a856"}}>ZHAOXI · BETA 15.1</small><h1 style={{margin:"6px 0"}}>{t.title}</h1><p style={{margin:0,color:"#64748b"}}>{t.sub}</p></header><div style={{display:"flex",gap:8,marginBottom:12}}><select value={hours} onChange={e=>setHours(Number(e.target.value))} style={{flex:1,padding:10,borderRadius:12,border:"1px solid #dbe3df"}}><option value={24}>{t.h24}</option><option value={72}>{t.h72}</option><option value={168}>{t.h168}</option></select><ActionButton tone="neutral" onClick={load}>{t.refresh}</ActionButton></div>{error&&<p style={{background:"#fff1f2",color:"#be123c",padding:12,borderRadius:12}}>{error}</p>}{data&&<><section style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,marginBottom:14}}><Metric label={t.total} value={data.total}/><Metric label={t.unresolved} value={data.unresolved}/><Metric label={t.critical} value={data.critical}/><Metric label={t.errors} value={data.error}/></section><section style={{display:"grid",gap:10}}>{data.recent.length?data.recent.map(e=><EventCard key={e.id} e={e}/>):<Surface>{t.empty}</Surface>}</section></>}</main>}
